/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/admin.proto */

#ifndef PROTOBUF_C_meshtastic_2fadmin_2eproto__INCLUDED
#define PROTOBUF_C_meshtastic_2fadmin_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "meshtastic/channel.pb-c.h"
#include "meshtastic/config.pb-c.h"
#include "meshtastic/connection_status.pb-c.h"
#include "meshtastic/mesh.pb-c.h"
#include "meshtastic/module_config.pb-c.h"

typedef struct Meshtastic__AdminMessage Meshtastic__AdminMessage;
typedef struct Meshtastic__HamParameters Meshtastic__HamParameters;
typedef struct Meshtastic__NodeRemoteHardwarePinsResponse Meshtastic__NodeRemoteHardwarePinsResponse;


/* --- enums --- */

/*
 * TODO: REPLACE
 */
typedef enum _Meshtastic__AdminMessage__ConfigType {
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__DEVICE_CONFIG = 0,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__POSITION_CONFIG = 1,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__POWER_CONFIG = 2,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__NETWORK_CONFIG = 3,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__DISPLAY_CONFIG = 4,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__LORA_CONFIG = 5,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__BLUETOOTH_CONFIG = 6,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__SECURITY_CONFIG = 7,
  /*
   */
  MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE__SESSIONKEY_CONFIG = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__ADMIN_MESSAGE__CONFIG_TYPE)
} Meshtastic__AdminMessage__ConfigType;
/*
 * TODO: REPLACE
 */
typedef enum _Meshtastic__AdminMessage__ModuleConfigType {
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__MQTT_CONFIG = 0,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__SERIAL_CONFIG = 1,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__EXTNOTIF_CONFIG = 2,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__STOREFORWARD_CONFIG = 3,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__RANGETEST_CONFIG = 4,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__TELEMETRY_CONFIG = 5,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__CANNEDMSG_CONFIG = 6,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__AUDIO_CONFIG = 7,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__REMOTEHARDWARE_CONFIG = 8,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__NEIGHBORINFO_CONFIG = 9,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__AMBIENTLIGHTING_CONFIG = 10,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__DETECTIONSENSOR_CONFIG = 11,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE__PAXCOUNTER_CONFIG = 12
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__ADMIN_MESSAGE__MODULE_CONFIG_TYPE)
} Meshtastic__AdminMessage__ModuleConfigType;

/* --- messages --- */

typedef enum {
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT__NOT_SET = 0,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_CHANNEL_REQUEST = 1,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_CHANNEL_RESPONSE = 2,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_OWNER_REQUEST = 3,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_OWNER_RESPONSE = 4,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_CONFIG_REQUEST = 5,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_CONFIG_RESPONSE = 6,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_MODULE_CONFIG_REQUEST = 7,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_MODULE_CONFIG_RESPONSE = 8,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_CANNED_MESSAGE_MODULE_MESSAGES_REQUEST = 10,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_CANNED_MESSAGE_MODULE_MESSAGES_RESPONSE = 11,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_DEVICE_METADATA_REQUEST = 12,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_DEVICE_METADATA_RESPONSE = 13,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_RINGTONE_REQUEST = 14,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_RINGTONE_RESPONSE = 15,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_DEVICE_CONNECTION_STATUS_REQUEST = 16,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_DEVICE_CONNECTION_STATUS_RESPONSE = 17,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_HAM_MODE = 18,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_NODE_REMOTE_HARDWARE_PINS_REQUEST = 19,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_GET_NODE_REMOTE_HARDWARE_PINS_RESPONSE = 20,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_ENTER_DFU_MODE_REQUEST = 21,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_DELETE_FILE_REQUEST = 22,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_SCALE = 23,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_OWNER = 32,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_CHANNEL = 33,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_CONFIG = 34,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_MODULE_CONFIG = 35,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_CANNED_MESSAGE_MODULE_MESSAGES = 36,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_RINGTONE_MESSAGE = 37,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_REMOVE_BY_NODENUM = 38,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_FAVORITE_NODE = 39,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_REMOVE_FAVORITE_NODE = 40,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_FIXED_POSITION = 41,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_REMOVE_FIXED_POSITION = 42,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SET_TIME_ONLY = 43,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_BEGIN_EDIT_SETTINGS = 64,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_COMMIT_EDIT_SETTINGS = 65,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_FACTORY_RESET_DEVICE = 94,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_REBOOT_OTA_SECONDS = 95,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_EXIT_SIMULATOR = 96,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_REBOOT_SECONDS = 97,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_SHUTDOWN_SECONDS = 98,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_FACTORY_RESET_CONFIG = 99,
  MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT_NODEDB_RESET = 100
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT__CASE)
} Meshtastic__AdminMessage__PayloadVariantCase;

/*
 * This message is handled by the Admin module and is responsible for all settings/channel read/write operations.
 * This message is used to do settings operations to both remote AND local nodes.
 * (Prior to 1.2 these operations were done via special ToRadio operations)
 */
struct  Meshtastic__AdminMessage
{
  ProtobufCMessage base;
  /*
   * The node generates this key and sends it with any get_x_response packets.
   * The client MUST include the same key with any set_x commands. Key expires after 300 seconds.
   * Prevents replay attacks for admin messages.
   */
  ProtobufCBinaryData session_passkey;
  Meshtastic__AdminMessage__PayloadVariantCase payload_variant_case;
  union {
    /*
     * Delete the file by the specified path from the device
     */
    char *delete_file_request;
    /*
     * Get the Canned Message Module messages in the response to this message.
     */
    char *get_canned_message_module_messages_response;
    /*
     * Get the Ringtone in the response to this message.
     */
    char *get_ringtone_response;
    /*
     * Set the Canned Message Module messages text.
     */
    char *set_canned_message_module_messages;
    /*
     * Set the ringtone for ExternalNotification.
     */
    char *set_ringtone_message;
    /*
     * TODO: REPLACE
     */
    Meshtastic__Channel *get_channel_response;
    /*
     * Send the current Config in the response to this message.
     */
    Meshtastic__Config *get_config_response;
    /*
     * Device connection status response
     */
    Meshtastic__DeviceConnectionStatus *get_device_connection_status_response;
    /*
     * Device metadata response
     */
    Meshtastic__DeviceMetadata *get_device_metadata_response;
    /*
     * Send the current Config in the response to this message.
     */
    Meshtastic__ModuleConfig *get_module_config_response;
    /*
     * Respond with the mesh's nodes with their available gpio pins for RemoteHardware module use
     */
    Meshtastic__NodeRemoteHardwarePinsResponse *get_node_remote_hardware_pins_response;
    /*
     * TODO: REPLACE
     */
    Meshtastic__User *get_owner_response;
    /*
     * Set channels (using the new API).
     * A special channel is the "primary channel".
     * The other records are secondary channels.
     * Note: only one channel can be marked as primary.
     * If the client sets a particular channel to be primary, the previous channel will be set to SECONDARY automatically.
     */
    Meshtastic__Channel *set_channel;
    /*
     * Set the current Config
     */
    Meshtastic__Config *set_config;
    /*
     * Set fixed position data on the node and then set the position.fixed_position = true
     */
    Meshtastic__Position *set_fixed_position;
    /*
     * Setup a node for licensed amateur (ham) radio operation
     */
    Meshtastic__HamParameters *set_ham_mode;
    /*
     * Set the current Config
     */
    Meshtastic__ModuleConfig *set_module_config;
    /*
     * Set the owner for this node
     */
    Meshtastic__User *set_owner;
    /*
     * Tell the node to factory reset config; all device state and configuration will be returned to factory defaults; BLE bonds will be preserved.
     */
    int32_t factory_reset_config;
    /*
     * Tell the node to factory reset config everything; all device state and configuration will be returned to factory defaults and BLE bonds will be cleared.
     */
    int32_t factory_reset_device;
    /*
     * Send the specified channel in the response to this message
     * NOTE: This field is sent with the channel index + 1 (to ensure we never try to send 'zero' - which protobufs treats as not present)
     */
    uint32_t get_channel_request;
    /*
     * Tell the node to reset the nodedb.
     */
    int32_t nodedb_reset;
    /*
     * Tell the node to reboot into the OTA Firmware in this many seconds (or <0 to cancel reboot)
     * Only Implemented for ESP32 Devices. This needs to be issued to send a new main firmware via bluetooth.
     */
    int32_t reboot_ota_seconds;
    /*
     * Tell the node to reboot in this many seconds (or <0 to cancel reboot)
     */
    int32_t reboot_seconds;
    /*
     * Remove the node by the specified node-num from the NodeDB on the device
     */
    uint32_t remove_by_nodenum;
    /*
     * Set specified node-num to be un-favorited on the NodeDB on the device
     */
    uint32_t remove_favorite_node;
    /*
     * Set specified node-num to be favorited on the NodeDB on the device
     */
    uint32_t set_favorite_node;
    /*
     * Set zero and offset for scale chips
     */
    uint32_t set_scale;
    /*
     * Set time only on the node
     * Convenience method to set the time on the node (as Net quality) without any other position data
     */
    uint32_t set_time_only;
    /*
     * Tell the node to shutdown in this many seconds (or <0 to cancel shutdown)
     */
    int32_t shutdown_seconds;
    /*
     * Ask for the following config data to be sent
     */
    Meshtastic__AdminMessage__ConfigType get_config_request;
    /*
     * Ask for the following config data to be sent
     */
    Meshtastic__AdminMessage__ModuleConfigType get_module_config_request;
    /*
     * Begins an edit transaction for config, module config, owner, and channel settings changes
     * This will delay the standard *implicit* save to the file system and subsequent reboot behavior until committed (commit_edit_settings)
     */
    protobuf_c_boolean begin_edit_settings;
    /*
     * Commits an open transaction for any edits made to config, module config, owner, and channel settings
     */
    protobuf_c_boolean commit_edit_settings;
    /*
     * Enter (UF2) DFU mode
     * Only implemented on NRF52 currently
     */
    protobuf_c_boolean enter_dfu_mode_request;
    /*
     * This message is only supported for the simulator Portduino build.
     * If received the simulator will exit successfully.
     */
    protobuf_c_boolean exit_simulator;
    /*
     * Get the Canned Message Module messages in the response to this message.
     */
    protobuf_c_boolean get_canned_message_module_messages_request;
    /*
     * Request the node to send it's connection status
     */
    protobuf_c_boolean get_device_connection_status_request;
    /*
     * Request the node to send device metadata (firmware, protobuf version, etc)
     */
    protobuf_c_boolean get_device_metadata_request;
    /*
     * Get the mesh's nodes with their available gpio pins for RemoteHardware module use
     */
    protobuf_c_boolean get_node_remote_hardware_pins_request;
    /*
     * Send the current owner data in the response to this message.
     */
    protobuf_c_boolean get_owner_request;
    /*
     * Get the Ringtone in the response to this message.
     */
    protobuf_c_boolean get_ringtone_request;
    /*
     * Clear fixed position coordinates and then set position.fixed_position = false
     */
    protobuf_c_boolean remove_fixed_position;
  };
};
#define MESHTASTIC__ADMIN_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__admin_message__descriptor) \
    , {0,NULL}, MESHTASTIC__ADMIN_MESSAGE__PAYLOAD_VARIANT__NOT_SET, {0} }


/*
 * Parameters for setting up Meshtastic for ameteur radio usage
 */
struct  Meshtastic__HamParameters
{
  ProtobufCMessage base;
  /*
   * Amateur radio call sign, eg. KD2ABC
   */
  char *call_sign;
  /*
   * Transmit power in dBm at the LoRA transceiver, not including any amplification
   */
  int32_t tx_power;
  /*
   * The selected frequency of LoRA operation
   * Please respect your local laws, regulations, and band plans.
   * Ensure your radio is capable of operating of the selected frequency before setting this.
   */
  float frequency;
  /*
   * Optional short name of user
   */
  char *short_name;
};
#define MESHTASTIC__HAM_PARAMETERS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__ham_parameters__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


/*
 * Response envelope for node_remote_hardware_pins
 */
struct  Meshtastic__NodeRemoteHardwarePinsResponse
{
  ProtobufCMessage base;
  /*
   * Nodes and their respective remote hardware GPIO pins
   */
  size_t n_node_remote_hardware_pins;
  Meshtastic__NodeRemoteHardwarePin **node_remote_hardware_pins;
};
#define MESHTASTIC__NODE_REMOTE_HARDWARE_PINS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__node_remote_hardware_pins_response__descriptor) \
    , 0,NULL }


/* Meshtastic__AdminMessage methods */
void   meshtastic__admin_message__init
                     (Meshtastic__AdminMessage         *message);
size_t meshtastic__admin_message__get_packed_size
                     (const Meshtastic__AdminMessage   *message);
size_t meshtastic__admin_message__pack
                     (const Meshtastic__AdminMessage   *message,
                      uint8_t             *out);
size_t meshtastic__admin_message__pack_to_buffer
                     (const Meshtastic__AdminMessage   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__AdminMessage *
       meshtastic__admin_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__admin_message__free_unpacked
                     (Meshtastic__AdminMessage *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__HamParameters methods */
void   meshtastic__ham_parameters__init
                     (Meshtastic__HamParameters         *message);
size_t meshtastic__ham_parameters__get_packed_size
                     (const Meshtastic__HamParameters   *message);
size_t meshtastic__ham_parameters__pack
                     (const Meshtastic__HamParameters   *message,
                      uint8_t             *out);
size_t meshtastic__ham_parameters__pack_to_buffer
                     (const Meshtastic__HamParameters   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__HamParameters *
       meshtastic__ham_parameters__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__ham_parameters__free_unpacked
                     (Meshtastic__HamParameters *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__NodeRemoteHardwarePinsResponse methods */
void   meshtastic__node_remote_hardware_pins_response__init
                     (Meshtastic__NodeRemoteHardwarePinsResponse         *message);
size_t meshtastic__node_remote_hardware_pins_response__get_packed_size
                     (const Meshtastic__NodeRemoteHardwarePinsResponse   *message);
size_t meshtastic__node_remote_hardware_pins_response__pack
                     (const Meshtastic__NodeRemoteHardwarePinsResponse   *message,
                      uint8_t             *out);
size_t meshtastic__node_remote_hardware_pins_response__pack_to_buffer
                     (const Meshtastic__NodeRemoteHardwarePinsResponse   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__NodeRemoteHardwarePinsResponse *
       meshtastic__node_remote_hardware_pins_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__node_remote_hardware_pins_response__free_unpacked
                     (Meshtastic__NodeRemoteHardwarePinsResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Meshtastic__AdminMessage_Closure)
                 (const Meshtastic__AdminMessage *message,
                  void *closure_data);
typedef void (*Meshtastic__HamParameters_Closure)
                 (const Meshtastic__HamParameters *message,
                  void *closure_data);
typedef void (*Meshtastic__NodeRemoteHardwarePinsResponse_Closure)
                 (const Meshtastic__NodeRemoteHardwarePinsResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor meshtastic__admin_message__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__admin_message__config_type__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__admin_message__module_config_type__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__ham_parameters__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__node_remote_hardware_pins_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshtastic_2fadmin_2eproto__INCLUDED */
