/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/apponly.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/apponly.pb-c.h"
void   meshtastic__channel_set__init
                     (Meshtastic__ChannelSet         *message)
{
  static const Meshtastic__ChannelSet init_value = MESHTASTIC__CHANNEL_SET__INIT;
  *message = init_value;
}
size_t meshtastic__channel_set__get_packed_size
                     (const Meshtastic__ChannelSet *message)
{
  assert(message->base.descriptor == &meshtastic__channel_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__channel_set__pack
                     (const Meshtastic__ChannelSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__channel_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__channel_set__pack_to_buffer
                     (const Meshtastic__ChannelSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__channel_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__ChannelSet *
       meshtastic__channel_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__ChannelSet *)
     protobuf_c_message_unpack (&meshtastic__channel_set__descriptor,
                                allocator, len, data);
}
void   meshtastic__channel_set__free_unpacked
                     (Meshtastic__ChannelSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__channel_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor meshtastic__channel_set__field_descriptors[2] =
{
  {
    "settings",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ChannelSet, n_settings),
    offsetof(Meshtastic__ChannelSet, settings),
    &meshtastic__channel_settings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lora_config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ChannelSet, lora_config),
    &meshtastic__config__lo_ra_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__channel_set__field_indices_by_name[] = {
  1,   /* field[1] = lora_config */
  0,   /* field[0] = settings */
};
static const ProtobufCIntRange meshtastic__channel_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor meshtastic__channel_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ChannelSet",
  "ChannelSet",
  "Meshtastic__ChannelSet",
  "meshtastic",
  sizeof(Meshtastic__ChannelSet),
  2,
  meshtastic__channel_set__field_descriptors,
  meshtastic__channel_set__field_indices_by_name,
  1,  meshtastic__channel_set__number_ranges,
  (ProtobufCMessageInit) meshtastic__channel_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
