/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/atak.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/atak.pb-c.h"
void   meshtastic__takpacket__init
                     (Meshtastic__TAKPacket         *message)
{
  static const Meshtastic__TAKPacket init_value = MESHTASTIC__TAKPACKET__INIT;
  *message = init_value;
}
size_t meshtastic__takpacket__get_packed_size
                     (const Meshtastic__TAKPacket *message)
{
  assert(message->base.descriptor == &meshtastic__takpacket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__takpacket__pack
                     (const Meshtastic__TAKPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__takpacket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__takpacket__pack_to_buffer
                     (const Meshtastic__TAKPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__takpacket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__TAKPacket *
       meshtastic__takpacket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__TAKPacket *)
     protobuf_c_message_unpack (&meshtastic__takpacket__descriptor,
                                allocator, len, data);
}
void   meshtastic__takpacket__free_unpacked
                     (Meshtastic__TAKPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__takpacket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__geo_chat__init
                     (Meshtastic__GeoChat         *message)
{
  static const Meshtastic__GeoChat init_value = MESHTASTIC__GEO_CHAT__INIT;
  *message = init_value;
}
size_t meshtastic__geo_chat__get_packed_size
                     (const Meshtastic__GeoChat *message)
{
  assert(message->base.descriptor == &meshtastic__geo_chat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__geo_chat__pack
                     (const Meshtastic__GeoChat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__geo_chat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__geo_chat__pack_to_buffer
                     (const Meshtastic__GeoChat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__geo_chat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__GeoChat *
       meshtastic__geo_chat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__GeoChat *)
     protobuf_c_message_unpack (&meshtastic__geo_chat__descriptor,
                                allocator, len, data);
}
void   meshtastic__geo_chat__free_unpacked
                     (Meshtastic__GeoChat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__geo_chat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__group__init
                     (Meshtastic__Group         *message)
{
  static const Meshtastic__Group init_value = MESHTASTIC__GROUP__INIT;
  *message = init_value;
}
size_t meshtastic__group__get_packed_size
                     (const Meshtastic__Group *message)
{
  assert(message->base.descriptor == &meshtastic__group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__group__pack
                     (const Meshtastic__Group *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__group__pack_to_buffer
                     (const Meshtastic__Group *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__Group *
       meshtastic__group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__Group *)
     protobuf_c_message_unpack (&meshtastic__group__descriptor,
                                allocator, len, data);
}
void   meshtastic__group__free_unpacked
                     (Meshtastic__Group *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__status__init
                     (Meshtastic__Status         *message)
{
  static const Meshtastic__Status init_value = MESHTASTIC__STATUS__INIT;
  *message = init_value;
}
size_t meshtastic__status__get_packed_size
                     (const Meshtastic__Status *message)
{
  assert(message->base.descriptor == &meshtastic__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__status__pack
                     (const Meshtastic__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__status__pack_to_buffer
                     (const Meshtastic__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__Status *
       meshtastic__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__Status *)
     protobuf_c_message_unpack (&meshtastic__status__descriptor,
                                allocator, len, data);
}
void   meshtastic__status__free_unpacked
                     (Meshtastic__Status *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__contact__init
                     (Meshtastic__Contact         *message)
{
  static const Meshtastic__Contact init_value = MESHTASTIC__CONTACT__INIT;
  *message = init_value;
}
size_t meshtastic__contact__get_packed_size
                     (const Meshtastic__Contact *message)
{
  assert(message->base.descriptor == &meshtastic__contact__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__contact__pack
                     (const Meshtastic__Contact *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__contact__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__contact__pack_to_buffer
                     (const Meshtastic__Contact *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__contact__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__Contact *
       meshtastic__contact__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__Contact *)
     protobuf_c_message_unpack (&meshtastic__contact__descriptor,
                                allocator, len, data);
}
void   meshtastic__contact__free_unpacked
                     (Meshtastic__Contact *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__contact__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__pli__init
                     (Meshtastic__PLI         *message)
{
  static const Meshtastic__PLI init_value = MESHTASTIC__PLI__INIT;
  *message = init_value;
}
size_t meshtastic__pli__get_packed_size
                     (const Meshtastic__PLI *message)
{
  assert(message->base.descriptor == &meshtastic__pli__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__pli__pack
                     (const Meshtastic__PLI *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__pli__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__pli__pack_to_buffer
                     (const Meshtastic__PLI *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__pli__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__PLI *
       meshtastic__pli__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__PLI *)
     protobuf_c_message_unpack (&meshtastic__pli__descriptor,
                                allocator, len, data);
}
void   meshtastic__pli__free_unpacked
                     (Meshtastic__PLI *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__pli__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor meshtastic__takpacket__field_descriptors[7] =
{
  {
    "is_compressed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__TAKPacket, is_compressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contact",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__TAKPacket, contact),
    &meshtastic__contact__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__TAKPacket, group),
    &meshtastic__group__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__TAKPacket, status),
    &meshtastic__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pli",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__TAKPacket, payload_variant_case),
    offsetof(Meshtastic__TAKPacket, pli),
    &meshtastic__pli__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chat",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__TAKPacket, payload_variant_case),
    offsetof(Meshtastic__TAKPacket, chat),
    &meshtastic__geo_chat__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detail",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Meshtastic__TAKPacket, payload_variant_case),
    offsetof(Meshtastic__TAKPacket, detail),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__takpacket__field_indices_by_name[] = {
  5,   /* field[5] = chat */
  1,   /* field[1] = contact */
  6,   /* field[6] = detail */
  2,   /* field[2] = group */
  0,   /* field[0] = is_compressed */
  4,   /* field[4] = pli */
  3,   /* field[3] = status */
};
static const ProtobufCIntRange meshtastic__takpacket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor meshtastic__takpacket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.TAKPacket",
  "TAKPacket",
  "Meshtastic__TAKPacket",
  "meshtastic",
  sizeof(Meshtastic__TAKPacket),
  7,
  meshtastic__takpacket__field_descriptors,
  meshtastic__takpacket__field_indices_by_name,
  1,  meshtastic__takpacket__number_ranges,
  (ProtobufCMessageInit) meshtastic__takpacket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__geo_chat__field_descriptors[3] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__GeoChat, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Meshtastic__GeoChat, _to_case),
    offsetof(Meshtastic__GeoChat, to),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to_callsign",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Meshtastic__GeoChat, _to_callsign_case),
    offsetof(Meshtastic__GeoChat, to_callsign),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__geo_chat__field_indices_by_name[] = {
  0,   /* field[0] = message */
  1,   /* field[1] = to */
  2,   /* field[2] = to_callsign */
};
static const ProtobufCIntRange meshtastic__geo_chat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor meshtastic__geo_chat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.GeoChat",
  "GeoChat",
  "Meshtastic__GeoChat",
  "meshtastic",
  sizeof(Meshtastic__GeoChat),
  3,
  meshtastic__geo_chat__field_descriptors,
  meshtastic__geo_chat__field_indices_by_name,
  1,  meshtastic__geo_chat__number_ranges,
  (ProtobufCMessageInit) meshtastic__geo_chat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__group__field_descriptors[2] =
{
  {
    "role",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Group, role),
    &meshtastic__member_role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Group, team),
    &meshtastic__team__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__group__field_indices_by_name[] = {
  0,   /* field[0] = role */
  1,   /* field[1] = team */
};
static const ProtobufCIntRange meshtastic__group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor meshtastic__group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Group",
  "Group",
  "Meshtastic__Group",
  "meshtastic",
  sizeof(Meshtastic__Group),
  2,
  meshtastic__group__field_descriptors,
  meshtastic__group__field_indices_by_name,
  1,  meshtastic__group__number_ranges,
  (ProtobufCMessageInit) meshtastic__group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__status__field_descriptors[1] =
{
  {
    "battery",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Status, battery),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__status__field_indices_by_name[] = {
  0,   /* field[0] = battery */
};
static const ProtobufCIntRange meshtastic__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor meshtastic__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Status",
  "Status",
  "Meshtastic__Status",
  "meshtastic",
  sizeof(Meshtastic__Status),
  1,
  meshtastic__status__field_descriptors,
  meshtastic__status__field_indices_by_name,
  1,  meshtastic__status__number_ranges,
  (ProtobufCMessageInit) meshtastic__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__contact__field_descriptors[2] =
{
  {
    "callsign",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Contact, callsign),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_callsign",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Contact, device_callsign),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__contact__field_indices_by_name[] = {
  0,   /* field[0] = callsign */
  1,   /* field[1] = device_callsign */
};
static const ProtobufCIntRange meshtastic__contact__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor meshtastic__contact__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Contact",
  "Contact",
  "Meshtastic__Contact",
  "meshtastic",
  sizeof(Meshtastic__Contact),
  2,
  meshtastic__contact__field_descriptors,
  meshtastic__contact__field_indices_by_name,
  1,  meshtastic__contact__number_ranges,
  (ProtobufCMessageInit) meshtastic__contact__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__pli__field_descriptors[5] =
{
  {
    "latitude_i",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SFIXED32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__PLI, latitude_i),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude_i",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SFIXED32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__PLI, longitude_i),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__PLI, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__PLI, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "course",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__PLI, course),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__pli__field_indices_by_name[] = {
  2,   /* field[2] = altitude */
  4,   /* field[4] = course */
  0,   /* field[0] = latitude_i */
  1,   /* field[1] = longitude_i */
  3,   /* field[3] = speed */
};
static const ProtobufCIntRange meshtastic__pli__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor meshtastic__pli__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.PLI",
  "PLI",
  "Meshtastic__PLI",
  "meshtastic",
  sizeof(Meshtastic__PLI),
  5,
  meshtastic__pli__field_descriptors,
  meshtastic__pli__field_indices_by_name,
  1,  meshtastic__pli__number_ranges,
  (ProtobufCMessageInit) meshtastic__pli__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__team__enum_values_by_number[15] =
{
  { "Unspecifed_Color", "MESHTASTIC__TEAM__Unspecifed_Color", 0 },
  { "White", "MESHTASTIC__TEAM__White", 1 },
  { "Yellow", "MESHTASTIC__TEAM__Yellow", 2 },
  { "Orange", "MESHTASTIC__TEAM__Orange", 3 },
  { "Magenta", "MESHTASTIC__TEAM__Magenta", 4 },
  { "Red", "MESHTASTIC__TEAM__Red", 5 },
  { "Maroon", "MESHTASTIC__TEAM__Maroon", 6 },
  { "Purple", "MESHTASTIC__TEAM__Purple", 7 },
  { "Dark_Blue", "MESHTASTIC__TEAM__Dark_Blue", 8 },
  { "Blue", "MESHTASTIC__TEAM__Blue", 9 },
  { "Cyan", "MESHTASTIC__TEAM__Cyan", 10 },
  { "Teal", "MESHTASTIC__TEAM__Teal", 11 },
  { "Green", "MESHTASTIC__TEAM__Green", 12 },
  { "Dark_Green", "MESHTASTIC__TEAM__Dark_Green", 13 },
  { "Brown", "MESHTASTIC__TEAM__Brown", 14 },
};
static const ProtobufCIntRange meshtastic__team__value_ranges[] = {
{0, 0},{0, 15}
};
static const ProtobufCEnumValueIndex meshtastic__team__enum_values_by_name[15] =
{
  { "Blue", 9 },
  { "Brown", 14 },
  { "Cyan", 10 },
  { "Dark_Blue", 8 },
  { "Dark_Green", 13 },
  { "Green", 12 },
  { "Magenta", 4 },
  { "Maroon", 6 },
  { "Orange", 3 },
  { "Purple", 7 },
  { "Red", 5 },
  { "Teal", 11 },
  { "Unspecifed_Color", 0 },
  { "White", 1 },
  { "Yellow", 2 },
};
const ProtobufCEnumDescriptor meshtastic__team__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Team",
  "Team",
  "Meshtastic__Team",
  "meshtastic",
  15,
  meshtastic__team__enum_values_by_number,
  15,
  meshtastic__team__enum_values_by_name,
  1,
  meshtastic__team__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__member_role__enum_values_by_number[9] =
{
  { "Unspecifed", "MESHTASTIC__MEMBER_ROLE__Unspecifed", 0 },
  { "TeamMember", "MESHTASTIC__MEMBER_ROLE__TeamMember", 1 },
  { "TeamLead", "MESHTASTIC__MEMBER_ROLE__TeamLead", 2 },
  { "HQ", "MESHTASTIC__MEMBER_ROLE__HQ", 3 },
  { "Sniper", "MESHTASTIC__MEMBER_ROLE__Sniper", 4 },
  { "Medic", "MESHTASTIC__MEMBER_ROLE__Medic", 5 },
  { "ForwardObserver", "MESHTASTIC__MEMBER_ROLE__ForwardObserver", 6 },
  { "RTO", "MESHTASTIC__MEMBER_ROLE__RTO", 7 },
  { "K9", "MESHTASTIC__MEMBER_ROLE__K9", 8 },
};
static const ProtobufCIntRange meshtastic__member_role__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex meshtastic__member_role__enum_values_by_name[9] =
{
  { "ForwardObserver", 6 },
  { "HQ", 3 },
  { "K9", 8 },
  { "Medic", 5 },
  { "RTO", 7 },
  { "Sniper", 4 },
  { "TeamLead", 2 },
  { "TeamMember", 1 },
  { "Unspecifed", 0 },
};
const ProtobufCEnumDescriptor meshtastic__member_role__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.MemberRole",
  "MemberRole",
  "Meshtastic__MemberRole",
  "meshtastic",
  9,
  meshtastic__member_role__enum_values_by_number,
  9,
  meshtastic__member_role__enum_values_by_name,
  1,
  meshtastic__member_role__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
