/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/atak.proto */

#ifndef PROTOBUF_C_meshtastic_2fatak_2eproto__INCLUDED
#define PROTOBUF_C_meshtastic_2fatak_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Meshtastic__TAKPacket Meshtastic__TAKPacket;
typedef struct Meshtastic__GeoChat Meshtastic__GeoChat;
typedef struct Meshtastic__Group Meshtastic__Group;
typedef struct Meshtastic__Status Meshtastic__Status;
typedef struct Meshtastic__Contact Meshtastic__Contact;
typedef struct Meshtastic__PLI Meshtastic__PLI;


/* --- enums --- */

typedef enum _Meshtastic__Team {
  /*
   * Unspecifed
   */
  MESHTASTIC__TEAM__Unspecifed_Color = 0,
  /*
   * White
   */
  MESHTASTIC__TEAM__White = 1,
  /*
   * Yellow
   */
  MESHTASTIC__TEAM__Yellow = 2,
  /*
   * Orange
   */
  MESHTASTIC__TEAM__Orange = 3,
  /*
   * Magenta
   */
  MESHTASTIC__TEAM__Magenta = 4,
  /*
   * Red
   */
  MESHTASTIC__TEAM__Red = 5,
  /*
   * Maroon
   */
  MESHTASTIC__TEAM__Maroon = 6,
  /*
   * Purple
   */
  MESHTASTIC__TEAM__Purple = 7,
  /*
   * Dark Blue
   */
  MESHTASTIC__TEAM__Dark_Blue = 8,
  /*
   * Blue
   */
  MESHTASTIC__TEAM__Blue = 9,
  /*
   * Cyan
   */
  MESHTASTIC__TEAM__Cyan = 10,
  /*
   * Teal
   */
  MESHTASTIC__TEAM__Teal = 11,
  /*
   * Green
   */
  MESHTASTIC__TEAM__Green = 12,
  /*
   * Dark Green
   */
  MESHTASTIC__TEAM__Dark_Green = 13,
  /*
   * Brown
   */
  MESHTASTIC__TEAM__Brown = 14
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__TEAM)
} Meshtastic__Team;
/*
 * Role of the group member
 */
typedef enum _Meshtastic__MemberRole {
  /*
   * Unspecifed
   */
  MESHTASTIC__MEMBER_ROLE__Unspecifed = 0,
  /*
   * Team Member
   */
  MESHTASTIC__MEMBER_ROLE__TeamMember = 1,
  /*
   * Team Lead
   */
  MESHTASTIC__MEMBER_ROLE__TeamLead = 2,
  /*
   * Headquarters
   */
  MESHTASTIC__MEMBER_ROLE__HQ = 3,
  /*
   * Airsoft enthusiast
   */
  MESHTASTIC__MEMBER_ROLE__Sniper = 4,
  /*
   * Medic
   */
  MESHTASTIC__MEMBER_ROLE__Medic = 5,
  /*
   * ForwardObserver
   */
  MESHTASTIC__MEMBER_ROLE__ForwardObserver = 6,
  /*
   * Radio Telephone Operator
   */
  MESHTASTIC__MEMBER_ROLE__RTO = 7,
  /*
   * Doggo
   */
  MESHTASTIC__MEMBER_ROLE__K9 = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__MEMBER_ROLE)
} Meshtastic__MemberRole;

/* --- messages --- */

typedef enum {
  MESHTASTIC__TAKPACKET__PAYLOAD_VARIANT__NOT_SET = 0,
  MESHTASTIC__TAKPACKET__PAYLOAD_VARIANT_PLI = 5,
  MESHTASTIC__TAKPACKET__PAYLOAD_VARIANT_CHAT = 6,
  MESHTASTIC__TAKPACKET__PAYLOAD_VARIANT_DETAIL = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__TAKPACKET__PAYLOAD_VARIANT__CASE)
} Meshtastic__TAKPacket__PayloadVariantCase;

/*
 * Packets for the official ATAK Plugin
 */
struct  Meshtastic__TAKPacket
{
  ProtobufCMessage base;
  /*
   * Are the payloads strings compressed for LoRA transport?
   */
  protobuf_c_boolean is_compressed;
  /*
   * The contact / callsign for ATAK user
   */
  Meshtastic__Contact *contact;
  /*
   * The group for ATAK user
   */
  Meshtastic__Group *group;
  /*
   * The status of the ATAK EUD
   */
  Meshtastic__Status *status;
  Meshtastic__TAKPacket__PayloadVariantCase payload_variant_case;
  union {
    /*
     * Generic CoT detail XML
     * May be compressed / truncated by the sender (EUD)
     */
    ProtobufCBinaryData detail;
    /*
     * ATAK GeoChat message
     */
    Meshtastic__GeoChat *chat;
    /*
     * TAK position report
     */
    Meshtastic__PLI *pli;
  };
};
#define MESHTASTIC__TAKPACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__takpacket__descriptor) \
    , 0, NULL, NULL, NULL, MESHTASTIC__TAKPACKET__PAYLOAD_VARIANT__NOT_SET, { {0} } }


typedef enum {
  MESHTASTIC__GEO_CHAT___TO__NOT_SET = 0,
  MESHTASTIC__GEO_CHAT___TO_TO = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__GEO_CHAT___TO__CASE)
} Meshtastic__GeoChat__ToCase;

typedef enum {
  MESHTASTIC__GEO_CHAT___TO_CALLSIGN__NOT_SET = 0,
  MESHTASTIC__GEO_CHAT___TO_CALLSIGN_TO_CALLSIGN = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__GEO_CHAT___TO_CALLSIGN__CASE)
} Meshtastic__GeoChat__ToCallsignCase;

/*
 * ATAK GeoChat message
 */
struct  Meshtastic__GeoChat
{
  ProtobufCMessage base;
  /*
   * The text message
   */
  char *message;
  Meshtastic__GeoChat__ToCase _to_case;
  union {
    /*
     * Uid recipient of the message
     */
    char *to;
  };
  Meshtastic__GeoChat__ToCallsignCase _to_callsign_case;
  union {
    /*
     * Callsign of the recipient for the message
     */
    char *to_callsign;
  };
};
#define MESHTASTIC__GEO_CHAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__geo_chat__descriptor) \
    , (char *)protobuf_c_empty_string, MESHTASTIC__GEO_CHAT___TO__NOT_SET, {0}, MESHTASTIC__GEO_CHAT___TO_CALLSIGN__NOT_SET, {0} }


/*
 * ATAK Group
 * <__group role='Team Member' name='Cyan'/>
 */
struct  Meshtastic__Group
{
  ProtobufCMessage base;
  /*
   * Role of the group member
   */
  Meshtastic__MemberRole role;
  /*
   * Team (color)
   * Default Cyan
   */
  Meshtastic__Team team;
};
#define MESHTASTIC__GROUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__group__descriptor) \
    , MESHTASTIC__MEMBER_ROLE__Unspecifed, MESHTASTIC__TEAM__Unspecifed_Color }


/*
 * ATAK EUD Status
 * <status battery='100' />
 */
struct  Meshtastic__Status
{
  ProtobufCMessage base;
  /*
   * Battery level
   */
  uint32_t battery;
};
#define MESHTASTIC__STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__status__descriptor) \
    , 0 }


/*
 * ATAK Contact
 * <contact endpoint='0.0.0.0:4242:tcp' phone='+12345678' callsign='FALKE'/>
 */
struct  Meshtastic__Contact
{
  ProtobufCMessage base;
  /*
   * Callsign
   */
  char *callsign;
  /*
   * Device callsign
   */
  /*
   * IP address of endpoint in integer form (0.0.0.0 default)
   */
  char *device_callsign;
};
#define MESHTASTIC__CONTACT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__contact__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Position Location Information from ATAK
 */
struct  Meshtastic__PLI
{
  ProtobufCMessage base;
  /*
   * The new preferred location encoding, multiply by 1e-7 to get degrees
   * in floating point
   */
  int32_t latitude_i;
  /*
   * The new preferred location encoding, multiply by 1e-7 to get degrees
   * in floating point
   */
  int32_t longitude_i;
  /*
   * Altitude (ATAK prefers HAE)
   */
  int32_t altitude;
  /*
   * Speed
   */
  uint32_t speed;
  /*
   * Course in degrees
   */
  uint32_t course;
};
#define MESHTASTIC__PLI__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__pli__descriptor) \
    , 0, 0, 0, 0, 0 }


/* Meshtastic__TAKPacket methods */
void   meshtastic__takpacket__init
                     (Meshtastic__TAKPacket         *message);
size_t meshtastic__takpacket__get_packed_size
                     (const Meshtastic__TAKPacket   *message);
size_t meshtastic__takpacket__pack
                     (const Meshtastic__TAKPacket   *message,
                      uint8_t             *out);
size_t meshtastic__takpacket__pack_to_buffer
                     (const Meshtastic__TAKPacket   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__TAKPacket *
       meshtastic__takpacket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__takpacket__free_unpacked
                     (Meshtastic__TAKPacket *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__GeoChat methods */
void   meshtastic__geo_chat__init
                     (Meshtastic__GeoChat         *message);
size_t meshtastic__geo_chat__get_packed_size
                     (const Meshtastic__GeoChat   *message);
size_t meshtastic__geo_chat__pack
                     (const Meshtastic__GeoChat   *message,
                      uint8_t             *out);
size_t meshtastic__geo_chat__pack_to_buffer
                     (const Meshtastic__GeoChat   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__GeoChat *
       meshtastic__geo_chat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__geo_chat__free_unpacked
                     (Meshtastic__GeoChat *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__Group methods */
void   meshtastic__group__init
                     (Meshtastic__Group         *message);
size_t meshtastic__group__get_packed_size
                     (const Meshtastic__Group   *message);
size_t meshtastic__group__pack
                     (const Meshtastic__Group   *message,
                      uint8_t             *out);
size_t meshtastic__group__pack_to_buffer
                     (const Meshtastic__Group   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__Group *
       meshtastic__group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__group__free_unpacked
                     (Meshtastic__Group *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__Status methods */
void   meshtastic__status__init
                     (Meshtastic__Status         *message);
size_t meshtastic__status__get_packed_size
                     (const Meshtastic__Status   *message);
size_t meshtastic__status__pack
                     (const Meshtastic__Status   *message,
                      uint8_t             *out);
size_t meshtastic__status__pack_to_buffer
                     (const Meshtastic__Status   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__Status *
       meshtastic__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__status__free_unpacked
                     (Meshtastic__Status *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__Contact methods */
void   meshtastic__contact__init
                     (Meshtastic__Contact         *message);
size_t meshtastic__contact__get_packed_size
                     (const Meshtastic__Contact   *message);
size_t meshtastic__contact__pack
                     (const Meshtastic__Contact   *message,
                      uint8_t             *out);
size_t meshtastic__contact__pack_to_buffer
                     (const Meshtastic__Contact   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__Contact *
       meshtastic__contact__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__contact__free_unpacked
                     (Meshtastic__Contact *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__PLI methods */
void   meshtastic__pli__init
                     (Meshtastic__PLI         *message);
size_t meshtastic__pli__get_packed_size
                     (const Meshtastic__PLI   *message);
size_t meshtastic__pli__pack
                     (const Meshtastic__PLI   *message,
                      uint8_t             *out);
size_t meshtastic__pli__pack_to_buffer
                     (const Meshtastic__PLI   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__PLI *
       meshtastic__pli__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__pli__free_unpacked
                     (Meshtastic__PLI *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Meshtastic__TAKPacket_Closure)
                 (const Meshtastic__TAKPacket *message,
                  void *closure_data);
typedef void (*Meshtastic__GeoChat_Closure)
                 (const Meshtastic__GeoChat *message,
                  void *closure_data);
typedef void (*Meshtastic__Group_Closure)
                 (const Meshtastic__Group *message,
                  void *closure_data);
typedef void (*Meshtastic__Status_Closure)
                 (const Meshtastic__Status *message,
                  void *closure_data);
typedef void (*Meshtastic__Contact_Closure)
                 (const Meshtastic__Contact *message,
                  void *closure_data);
typedef void (*Meshtastic__PLI_Closure)
                 (const Meshtastic__PLI *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    meshtastic__team__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__member_role__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__takpacket__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__geo_chat__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__group__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__status__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__contact__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__pli__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshtastic_2fatak_2eproto__INCLUDED */
