/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/cannedmessages.proto */

#ifndef PROTOBUF_C_meshtastic_2fcannedmessages_2eproto__INCLUDED
#define PROTOBUF_C_meshtastic_2fcannedmessages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Meshtastic__CannedMessageModuleConfig Meshtastic__CannedMessageModuleConfig;


/* --- enums --- */


/* --- messages --- */

/*
 * Canned message module configuration.
 */
struct  Meshtastic__CannedMessageModuleConfig
{
  ProtobufCMessage base;
  /*
   * Predefined messages for canned message module separated by '|' characters.
   */
  char *messages;
};
#define MESHTASTIC__CANNED_MESSAGE_MODULE_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__canned_message_module_config__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Meshtastic__CannedMessageModuleConfig methods */
void   meshtastic__canned_message_module_config__init
                     (Meshtastic__CannedMessageModuleConfig         *message);
size_t meshtastic__canned_message_module_config__get_packed_size
                     (const Meshtastic__CannedMessageModuleConfig   *message);
size_t meshtastic__canned_message_module_config__pack
                     (const Meshtastic__CannedMessageModuleConfig   *message,
                      uint8_t             *out);
size_t meshtastic__canned_message_module_config__pack_to_buffer
                     (const Meshtastic__CannedMessageModuleConfig   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__CannedMessageModuleConfig *
       meshtastic__canned_message_module_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__canned_message_module_config__free_unpacked
                     (Meshtastic__CannedMessageModuleConfig *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Meshtastic__CannedMessageModuleConfig_Closure)
                 (const Meshtastic__CannedMessageModuleConfig *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor meshtastic__canned_message_module_config__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshtastic_2fcannedmessages_2eproto__INCLUDED */
