/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/config.pb-c.h"
void   meshtastic__config__device_config__init
                     (Meshtastic__Config__DeviceConfig         *message)
{
  static const Meshtastic__Config__DeviceConfig init_value = MESHTASTIC__CONFIG__DEVICE_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__position_config__init
                     (Meshtastic__Config__PositionConfig         *message)
{
  static const Meshtastic__Config__PositionConfig init_value = MESHTASTIC__CONFIG__POSITION_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__power_config__init
                     (Meshtastic__Config__PowerConfig         *message)
{
  static const Meshtastic__Config__PowerConfig init_value = MESHTASTIC__CONFIG__POWER_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__network_config__ip_v4_config__init
                     (Meshtastic__Config__NetworkConfig__IpV4Config         *message)
{
  static const Meshtastic__Config__NetworkConfig__IpV4Config init_value = MESHTASTIC__CONFIG__NETWORK_CONFIG__IP_V4_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__network_config__init
                     (Meshtastic__Config__NetworkConfig         *message)
{
  static const Meshtastic__Config__NetworkConfig init_value = MESHTASTIC__CONFIG__NETWORK_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__display_config__init
                     (Meshtastic__Config__DisplayConfig         *message)
{
  static const Meshtastic__Config__DisplayConfig init_value = MESHTASTIC__CONFIG__DISPLAY_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__lo_ra_config__init
                     (Meshtastic__Config__LoRaConfig         *message)
{
  static const Meshtastic__Config__LoRaConfig init_value = MESHTASTIC__CONFIG__LO_RA_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__bluetooth_config__init
                     (Meshtastic__Config__BluetoothConfig         *message)
{
  static const Meshtastic__Config__BluetoothConfig init_value = MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__security_config__init
                     (Meshtastic__Config__SecurityConfig         *message)
{
  static const Meshtastic__Config__SecurityConfig init_value = MESHTASTIC__CONFIG__SECURITY_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__sessionkey_config__init
                     (Meshtastic__Config__SessionkeyConfig         *message)
{
  static const Meshtastic__Config__SessionkeyConfig init_value = MESHTASTIC__CONFIG__SESSIONKEY_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__config__init
                     (Meshtastic__Config         *message)
{
  static const Meshtastic__Config init_value = MESHTASTIC__CONFIG__INIT;
  *message = init_value;
}
size_t meshtastic__config__get_packed_size
                     (const Meshtastic__Config *message)
{
  assert(message->base.descriptor == &meshtastic__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__config__pack
                     (const Meshtastic__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__config__pack_to_buffer
                     (const Meshtastic__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__Config *
       meshtastic__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__Config *)
     protobuf_c_message_unpack (&meshtastic__config__descriptor,
                                allocator, len, data);
}
void   meshtastic__config__free_unpacked
                     (Meshtastic__Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue meshtastic__config__device_config__role__enum_values_by_number[11] =
{
  { "CLIENT", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT", 0 },
  { "CLIENT_MUTE", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT_MUTE", 1 },
  { "ROUTER", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__ROUTER", 2 },
  { "ROUTER_CLIENT", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__ROUTER_CLIENT", 3 },
  { "REPEATER", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__REPEATER", 4 },
  { "TRACKER", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__TRACKER", 5 },
  { "SENSOR", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__SENSOR", 6 },
  { "TAK", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__TAK", 7 },
  { "CLIENT_HIDDEN", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT_HIDDEN", 8 },
  { "LOST_AND_FOUND", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__LOST_AND_FOUND", 9 },
  { "TAK_TRACKER", "MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__TAK_TRACKER", 10 },
};
static const ProtobufCIntRange meshtastic__config__device_config__role__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex meshtastic__config__device_config__role__enum_values_by_name[11] =
{
  { "CLIENT", 0 },
  { "CLIENT_HIDDEN", 8 },
  { "CLIENT_MUTE", 1 },
  { "LOST_AND_FOUND", 9 },
  { "REPEATER", 4 },
  { "ROUTER", 2 },
  { "ROUTER_CLIENT", 3 },
  { "SENSOR", 6 },
  { "TAK", 7 },
  { "TAK_TRACKER", 10 },
  { "TRACKER", 5 },
};
const ProtobufCEnumDescriptor meshtastic__config__device_config__role__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DeviceConfig.Role",
  "Role",
  "Meshtastic__Config__DeviceConfig__Role",
  "meshtastic",
  11,
  meshtastic__config__device_config__role__enum_values_by_number,
  11,
  meshtastic__config__device_config__role__enum_values_by_name,
  1,
  meshtastic__config__device_config__role__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__config__device_config__rebroadcast_mode__enum_values_by_number[4] =
{
  { "ALL", "MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__ALL", 0 },
  { "ALL_SKIP_DECODING", "MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__ALL_SKIP_DECODING", 1 },
  { "LOCAL_ONLY", "MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__LOCAL_ONLY", 2 },
  { "KNOWN_ONLY", "MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__KNOWN_ONLY", 3 },
};
static const ProtobufCIntRange meshtastic__config__device_config__rebroadcast_mode__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex meshtastic__config__device_config__rebroadcast_mode__enum_values_by_name[4] =
{
  { "ALL", 0 },
  { "ALL_SKIP_DECODING", 1 },
  { "KNOWN_ONLY", 3 },
  { "LOCAL_ONLY", 2 },
};
const ProtobufCEnumDescriptor meshtastic__config__device_config__rebroadcast_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DeviceConfig.RebroadcastMode",
  "RebroadcastMode",
  "Meshtastic__Config__DeviceConfig__RebroadcastMode",
  "meshtastic",
  4,
  meshtastic__config__device_config__rebroadcast_mode__enum_values_by_number,
  4,
  meshtastic__config__device_config__rebroadcast_mode__enum_values_by_name,
  1,
  meshtastic__config__device_config__rebroadcast_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__config__device_config__field_descriptors[11] =
{
  {
    "role",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, role),
    &meshtastic__config__device_config__role__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_enabled",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, serial_enabled),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "button_gpio",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, button_gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buzzer_gpio",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, buzzer_gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rebroadcast_mode",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, rebroadcast_mode),
    &meshtastic__config__device_config__rebroadcast_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_info_broadcast_secs",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, node_info_broadcast_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_tap_as_button_press",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, double_tap_as_button_press),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_managed",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, is_managed),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disable_triple_click",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, disable_triple_click),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tzdef",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, tzdef),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "led_heartbeat_disabled",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DeviceConfig, led_heartbeat_disabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__device_config__field_indices_by_name[] = {
  2,   /* field[2] = button_gpio */
  3,   /* field[3] = buzzer_gpio */
  8,   /* field[8] = disable_triple_click */
  6,   /* field[6] = double_tap_as_button_press */
  7,   /* field[7] = is_managed */
  10,   /* field[10] = led_heartbeat_disabled */
  5,   /* field[5] = node_info_broadcast_secs */
  4,   /* field[4] = rebroadcast_mode */
  0,   /* field[0] = role */
  1,   /* field[1] = serial_enabled */
  9,   /* field[9] = tzdef */
};
static const ProtobufCIntRange meshtastic__config__device_config__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor meshtastic__config__device_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DeviceConfig",
  "DeviceConfig",
  "Meshtastic__Config__DeviceConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__DeviceConfig),
  11,
  meshtastic__config__device_config__field_descriptors,
  meshtastic__config__device_config__field_indices_by_name,
  2,  meshtastic__config__device_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__device_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__config__position_config__position_flags__enum_values_by_number[11] =
{
  { "UNSET", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__UNSET", 0 },
  { "ALTITUDE", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__ALTITUDE", 1 },
  { "ALTITUDE_MSL", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__ALTITUDE_MSL", 2 },
  { "GEOIDAL_SEPARATION", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__GEOIDAL_SEPARATION", 4 },
  { "DOP", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__DOP", 8 },
  { "HVDOP", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__HVDOP", 16 },
  { "SATINVIEW", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__SATINVIEW", 32 },
  { "SEQ_NO", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__SEQ_NO", 64 },
  { "TIMESTAMP", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__TIMESTAMP", 128 },
  { "HEADING", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__HEADING", 256 },
  { "SPEED", "MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__SPEED", 512 },
};
static const ProtobufCIntRange meshtastic__config__position_config__position_flags__value_ranges[] = {
{0, 0},{4, 3},{8, 4},{16, 5},{32, 6},{64, 7},{128, 8},{256, 9},{512, 10},{0, 11}
};
static const ProtobufCEnumValueIndex meshtastic__config__position_config__position_flags__enum_values_by_name[11] =
{
  { "ALTITUDE", 1 },
  { "ALTITUDE_MSL", 2 },
  { "DOP", 4 },
  { "GEOIDAL_SEPARATION", 3 },
  { "HEADING", 9 },
  { "HVDOP", 5 },
  { "SATINVIEW", 6 },
  { "SEQ_NO", 7 },
  { "SPEED", 10 },
  { "TIMESTAMP", 8 },
  { "UNSET", 0 },
};
const ProtobufCEnumDescriptor meshtastic__config__position_config__position_flags__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.PositionConfig.PositionFlags",
  "PositionFlags",
  "Meshtastic__Config__PositionConfig__PositionFlags",
  "meshtastic",
  11,
  meshtastic__config__position_config__position_flags__enum_values_by_number,
  11,
  meshtastic__config__position_config__position_flags__enum_values_by_name,
  9,
  meshtastic__config__position_config__position_flags__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__config__position_config__gps_mode__enum_values_by_number[3] =
{
  { "DISABLED", "MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE__DISABLED", 0 },
  { "ENABLED", "MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE__ENABLED", 1 },
  { "NOT_PRESENT", "MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE__NOT_PRESENT", 2 },
};
static const ProtobufCIntRange meshtastic__config__position_config__gps_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex meshtastic__config__position_config__gps_mode__enum_values_by_name[3] =
{
  { "DISABLED", 0 },
  { "ENABLED", 1 },
  { "NOT_PRESENT", 2 },
};
const ProtobufCEnumDescriptor meshtastic__config__position_config__gps_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.PositionConfig.GpsMode",
  "GpsMode",
  "Meshtastic__Config__PositionConfig__GpsMode",
  "meshtastic",
  3,
  meshtastic__config__position_config__gps_mode__enum_values_by_number,
  3,
  meshtastic__config__position_config__gps_mode__enum_values_by_name,
  1,
  meshtastic__config__position_config__gps_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__config__position_config__field_descriptors[13] =
{
  {
    "position_broadcast_secs",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, position_broadcast_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_broadcast_smart_enabled",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, position_broadcast_smart_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_position",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, fixed_position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_enabled",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, gps_enabled),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_update_interval",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, gps_update_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_attempt_time",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, gps_attempt_time),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_DEPRECATED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_flags",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, position_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_gpio",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, rx_gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_gpio",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, tx_gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcast_smart_minimum_distance",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, broadcast_smart_minimum_distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "broadcast_smart_minimum_interval_secs",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, broadcast_smart_minimum_interval_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_en_gpio",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, gps_en_gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_mode",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PositionConfig, gps_mode),
    &meshtastic__config__position_config__gps_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__position_config__field_indices_by_name[] = {
  9,   /* field[9] = broadcast_smart_minimum_distance */
  10,   /* field[10] = broadcast_smart_minimum_interval_secs */
  2,   /* field[2] = fixed_position */
  5,   /* field[5] = gps_attempt_time */
  11,   /* field[11] = gps_en_gpio */
  3,   /* field[3] = gps_enabled */
  12,   /* field[12] = gps_mode */
  4,   /* field[4] = gps_update_interval */
  0,   /* field[0] = position_broadcast_secs */
  1,   /* field[1] = position_broadcast_smart_enabled */
  6,   /* field[6] = position_flags */
  7,   /* field[7] = rx_gpio */
  8,   /* field[8] = tx_gpio */
};
static const ProtobufCIntRange meshtastic__config__position_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor meshtastic__config__position_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.PositionConfig",
  "PositionConfig",
  "Meshtastic__Config__PositionConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__PositionConfig),
  13,
  meshtastic__config__position_config__field_descriptors,
  meshtastic__config__position_config__field_indices_by_name,
  1,  meshtastic__config__position_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__position_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__config__power_config__field_descriptors[9] =
{
  {
    "is_power_saving",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, is_power_saving),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "on_battery_shutdown_after_secs",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, on_battery_shutdown_after_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adc_multiplier_override",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, adc_multiplier_override),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wait_bluetooth_secs",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, wait_bluetooth_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sds_secs",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, sds_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ls_secs",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, ls_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_wake_secs",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, min_wake_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_battery_ina_address",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, device_battery_ina_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "powermon_enables",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__PowerConfig, powermon_enables),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__power_config__field_indices_by_name[] = {
  2,   /* field[2] = adc_multiplier_override */
  7,   /* field[7] = device_battery_ina_address */
  0,   /* field[0] = is_power_saving */
  5,   /* field[5] = ls_secs */
  6,   /* field[6] = min_wake_secs */
  1,   /* field[1] = on_battery_shutdown_after_secs */
  8,   /* field[8] = powermon_enables */
  4,   /* field[4] = sds_secs */
  3,   /* field[3] = wait_bluetooth_secs */
};
static const ProtobufCIntRange meshtastic__config__power_config__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 32, 8 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor meshtastic__config__power_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.PowerConfig",
  "PowerConfig",
  "Meshtastic__Config__PowerConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__PowerConfig),
  9,
  meshtastic__config__power_config__field_descriptors,
  meshtastic__config__power_config__field_indices_by_name,
  3,  meshtastic__config__power_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__power_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__config__network_config__ip_v4_config__field_descriptors[4] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig__IpV4Config, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig__IpV4Config, gateway),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subnet",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig__IpV4Config, subnet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dns",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig__IpV4Config, dns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__network_config__ip_v4_config__field_indices_by_name[] = {
  3,   /* field[3] = dns */
  1,   /* field[1] = gateway */
  0,   /* field[0] = ip */
  2,   /* field[2] = subnet */
};
static const ProtobufCIntRange meshtastic__config__network_config__ip_v4_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor meshtastic__config__network_config__ip_v4_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.NetworkConfig.IpV4Config",
  "IpV4Config",
  "Meshtastic__Config__NetworkConfig__IpV4Config",
  "meshtastic",
  sizeof(Meshtastic__Config__NetworkConfig__IpV4Config),
  4,
  meshtastic__config__network_config__ip_v4_config__field_descriptors,
  meshtastic__config__network_config__ip_v4_config__field_indices_by_name,
  1,  meshtastic__config__network_config__ip_v4_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__network_config__ip_v4_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__config__network_config__address_mode__enum_values_by_number[2] =
{
  { "DHCP", "MESHTASTIC__CONFIG__NETWORK_CONFIG__ADDRESS_MODE__DHCP", 0 },
  { "STATIC", "MESHTASTIC__CONFIG__NETWORK_CONFIG__ADDRESS_MODE__STATIC", 1 },
};
static const ProtobufCIntRange meshtastic__config__network_config__address_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex meshtastic__config__network_config__address_mode__enum_values_by_name[2] =
{
  { "DHCP", 0 },
  { "STATIC", 1 },
};
const ProtobufCEnumDescriptor meshtastic__config__network_config__address_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.NetworkConfig.AddressMode",
  "AddressMode",
  "Meshtastic__Config__NetworkConfig__AddressMode",
  "meshtastic",
  2,
  meshtastic__config__network_config__address_mode__enum_values_by_number,
  2,
  meshtastic__config__network_config__address_mode__enum_values_by_name,
  1,
  meshtastic__config__network_config__address_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__config__network_config__field_descriptors[8] =
{
  {
    "wifi_enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, wifi_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_ssid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, wifi_ssid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_psk",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, wifi_psk),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ntp_server",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, ntp_server),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eth_enabled",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, eth_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_mode",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, address_mode),
    &meshtastic__config__network_config__address_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_config",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, ipv4_config),
    &meshtastic__config__network_config__ip_v4_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsyslog_server",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__NetworkConfig, rsyslog_server),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__network_config__field_indices_by_name[] = {
  5,   /* field[5] = address_mode */
  4,   /* field[4] = eth_enabled */
  6,   /* field[6] = ipv4_config */
  3,   /* field[3] = ntp_server */
  7,   /* field[7] = rsyslog_server */
  0,   /* field[0] = wifi_enabled */
  2,   /* field[2] = wifi_psk */
  1,   /* field[1] = wifi_ssid */
};
static const ProtobufCIntRange meshtastic__config__network_config__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor meshtastic__config__network_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.NetworkConfig",
  "NetworkConfig",
  "Meshtastic__Config__NetworkConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__NetworkConfig),
  8,
  meshtastic__config__network_config__field_descriptors,
  meshtastic__config__network_config__field_indices_by_name,
  2,  meshtastic__config__network_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__network_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__config__display_config__gps_coordinate_format__enum_values_by_number[6] =
{
  { "DEC", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__DEC", 0 },
  { "DMS", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__DMS", 1 },
  { "UTM", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__UTM", 2 },
  { "MGRS", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__MGRS", 3 },
  { "OLC", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__OLC", 4 },
  { "OSGR", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__OSGR", 5 },
};
static const ProtobufCIntRange meshtastic__config__display_config__gps_coordinate_format__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex meshtastic__config__display_config__gps_coordinate_format__enum_values_by_name[6] =
{
  { "DEC", 0 },
  { "DMS", 1 },
  { "MGRS", 3 },
  { "OLC", 4 },
  { "OSGR", 5 },
  { "UTM", 2 },
};
const ProtobufCEnumDescriptor meshtastic__config__display_config__gps_coordinate_format__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DisplayConfig.GpsCoordinateFormat",
  "GpsCoordinateFormat",
  "Meshtastic__Config__DisplayConfig__GpsCoordinateFormat",
  "meshtastic",
  6,
  meshtastic__config__display_config__gps_coordinate_format__enum_values_by_number,
  6,
  meshtastic__config__display_config__gps_coordinate_format__enum_values_by_name,
  1,
  meshtastic__config__display_config__gps_coordinate_format__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__config__display_config__display_units__enum_values_by_number[2] =
{
  { "METRIC", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_UNITS__METRIC", 0 },
  { "IMPERIAL", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_UNITS__IMPERIAL", 1 },
};
static const ProtobufCIntRange meshtastic__config__display_config__display_units__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex meshtastic__config__display_config__display_units__enum_values_by_name[2] =
{
  { "IMPERIAL", 1 },
  { "METRIC", 0 },
};
const ProtobufCEnumDescriptor meshtastic__config__display_config__display_units__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DisplayConfig.DisplayUnits",
  "DisplayUnits",
  "Meshtastic__Config__DisplayConfig__DisplayUnits",
  "meshtastic",
  2,
  meshtastic__config__display_config__display_units__enum_values_by_number,
  2,
  meshtastic__config__display_config__display_units__enum_values_by_name,
  1,
  meshtastic__config__display_config__display_units__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__config__display_config__oled_type__enum_values_by_number[4] =
{
  { "OLED_AUTO", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_AUTO", 0 },
  { "OLED_SSD1306", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_SSD1306", 1 },
  { "OLED_SH1106", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_SH1106", 2 },
  { "OLED_SH1107", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_SH1107", 3 },
};
static const ProtobufCIntRange meshtastic__config__display_config__oled_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex meshtastic__config__display_config__oled_type__enum_values_by_name[4] =
{
  { "OLED_AUTO", 0 },
  { "OLED_SH1106", 2 },
  { "OLED_SH1107", 3 },
  { "OLED_SSD1306", 1 },
};
const ProtobufCEnumDescriptor meshtastic__config__display_config__oled_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DisplayConfig.OledType",
  "OledType",
  "Meshtastic__Config__DisplayConfig__OledType",
  "meshtastic",
  4,
  meshtastic__config__display_config__oled_type__enum_values_by_number,
  4,
  meshtastic__config__display_config__oled_type__enum_values_by_name,
  1,
  meshtastic__config__display_config__oled_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__config__display_config__display_mode__enum_values_by_number[4] =
{
  { "DEFAULT", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__DEFAULT", 0 },
  { "TWOCOLOR", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__TWOCOLOR", 1 },
  { "INVERTED", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__INVERTED", 2 },
  { "COLOR", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__COLOR", 3 },
};
static const ProtobufCIntRange meshtastic__config__display_config__display_mode__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex meshtastic__config__display_config__display_mode__enum_values_by_name[4] =
{
  { "COLOR", 3 },
  { "DEFAULT", 0 },
  { "INVERTED", 2 },
  { "TWOCOLOR", 1 },
};
const ProtobufCEnumDescriptor meshtastic__config__display_config__display_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DisplayConfig.DisplayMode",
  "DisplayMode",
  "Meshtastic__Config__DisplayConfig__DisplayMode",
  "meshtastic",
  4,
  meshtastic__config__display_config__display_mode__enum_values_by_number,
  4,
  meshtastic__config__display_config__display_mode__enum_values_by_name,
  1,
  meshtastic__config__display_config__display_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__config__display_config__compass_orientation__enum_values_by_number[8] =
{
  { "DEGREES_0", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_0", 0 },
  { "DEGREES_90", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_90", 1 },
  { "DEGREES_180", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_180", 2 },
  { "DEGREES_270", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_270", 3 },
  { "DEGREES_0_INVERTED", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_0_INVERTED", 4 },
  { "DEGREES_90_INVERTED", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_90_INVERTED", 5 },
  { "DEGREES_180_INVERTED", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_180_INVERTED", 6 },
  { "DEGREES_270_INVERTED", "MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_270_INVERTED", 7 },
};
static const ProtobufCIntRange meshtastic__config__display_config__compass_orientation__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex meshtastic__config__display_config__compass_orientation__enum_values_by_name[8] =
{
  { "DEGREES_0", 0 },
  { "DEGREES_0_INVERTED", 4 },
  { "DEGREES_180", 2 },
  { "DEGREES_180_INVERTED", 6 },
  { "DEGREES_270", 3 },
  { "DEGREES_270_INVERTED", 7 },
  { "DEGREES_90", 1 },
  { "DEGREES_90_INVERTED", 5 },
};
const ProtobufCEnumDescriptor meshtastic__config__display_config__compass_orientation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DisplayConfig.CompassOrientation",
  "CompassOrientation",
  "Meshtastic__Config__DisplayConfig__CompassOrientation",
  "meshtastic",
  8,
  meshtastic__config__display_config__compass_orientation__enum_values_by_number,
  8,
  meshtastic__config__display_config__compass_orientation__enum_values_by_name,
  1,
  meshtastic__config__display_config__compass_orientation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__config__display_config__field_descriptors[11] =
{
  {
    "screen_on_secs",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, screen_on_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_format",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, gps_format),
    &meshtastic__config__display_config__gps_coordinate_format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_screen_carousel_secs",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, auto_screen_carousel_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compass_north_top",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, compass_north_top),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flip_screen",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, flip_screen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "units",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, units),
    &meshtastic__config__display_config__display_units__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oled",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, oled),
    &meshtastic__config__display_config__oled_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "displaymode",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, displaymode),
    &meshtastic__config__display_config__display_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading_bold",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, heading_bold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wake_on_tap_or_motion",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, wake_on_tap_or_motion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compass_orientation",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__DisplayConfig, compass_orientation),
    &meshtastic__config__display_config__compass_orientation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__display_config__field_indices_by_name[] = {
  2,   /* field[2] = auto_screen_carousel_secs */
  3,   /* field[3] = compass_north_top */
  10,   /* field[10] = compass_orientation */
  7,   /* field[7] = displaymode */
  4,   /* field[4] = flip_screen */
  1,   /* field[1] = gps_format */
  8,   /* field[8] = heading_bold */
  6,   /* field[6] = oled */
  0,   /* field[0] = screen_on_secs */
  5,   /* field[5] = units */
  9,   /* field[9] = wake_on_tap_or_motion */
};
static const ProtobufCIntRange meshtastic__config__display_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor meshtastic__config__display_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.DisplayConfig",
  "DisplayConfig",
  "Meshtastic__Config__DisplayConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__DisplayConfig),
  11,
  meshtastic__config__display_config__field_descriptors,
  meshtastic__config__display_config__field_indices_by_name,
  1,  meshtastic__config__display_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__display_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__config__lo_ra_config__region_code__enum_values_by_number[19] =
{
  { "UNSET", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UNSET", 0 },
  { "US", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__US", 1 },
  { "EU_433", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__EU_433", 2 },
  { "EU_868", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__EU_868", 3 },
  { "CN", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__CN", 4 },
  { "JP", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__JP", 5 },
  { "ANZ", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__ANZ", 6 },
  { "KR", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__KR", 7 },
  { "TW", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__TW", 8 },
  { "RU", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__RU", 9 },
  { "IN", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__IN", 10 },
  { "NZ_865", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__NZ_865", 11 },
  { "TH", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__TH", 12 },
  { "LORA_24", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__LORA_24", 13 },
  { "UA_433", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UA_433", 14 },
  { "UA_868", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UA_868", 15 },
  { "MY_433", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__MY_433", 16 },
  { "MY_919", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__MY_919", 17 },
  { "SG_923", "MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__SG_923", 18 },
};
static const ProtobufCIntRange meshtastic__config__lo_ra_config__region_code__value_ranges[] = {
{0, 0},{0, 19}
};
static const ProtobufCEnumValueIndex meshtastic__config__lo_ra_config__region_code__enum_values_by_name[19] =
{
  { "ANZ", 6 },
  { "CN", 4 },
  { "EU_433", 2 },
  { "EU_868", 3 },
  { "IN", 10 },
  { "JP", 5 },
  { "KR", 7 },
  { "LORA_24", 13 },
  { "MY_433", 16 },
  { "MY_919", 17 },
  { "NZ_865", 11 },
  { "RU", 9 },
  { "SG_923", 18 },
  { "TH", 12 },
  { "TW", 8 },
  { "UA_433", 14 },
  { "UA_868", 15 },
  { "UNSET", 0 },
  { "US", 1 },
};
const ProtobufCEnumDescriptor meshtastic__config__lo_ra_config__region_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.LoRaConfig.RegionCode",
  "RegionCode",
  "Meshtastic__Config__LoRaConfig__RegionCode",
  "meshtastic",
  19,
  meshtastic__config__lo_ra_config__region_code__enum_values_by_number,
  19,
  meshtastic__config__lo_ra_config__region_code__enum_values_by_name,
  1,
  meshtastic__config__lo_ra_config__region_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__config__lo_ra_config__modem_preset__enum_values_by_number[9] =
{
  { "LONG_FAST", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_FAST", 0 },
  { "LONG_SLOW", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_SLOW", 1 },
  { "VERY_LONG_SLOW", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__VERY_LONG_SLOW", 2 },
  { "MEDIUM_SLOW", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__MEDIUM_SLOW", 3 },
  { "MEDIUM_FAST", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__MEDIUM_FAST", 4 },
  { "SHORT_SLOW", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__SHORT_SLOW", 5 },
  { "SHORT_FAST", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__SHORT_FAST", 6 },
  { "LONG_MODERATE", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_MODERATE", 7 },
  { "SHORT_TURBO", "MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__SHORT_TURBO", 8 },
};
static const ProtobufCIntRange meshtastic__config__lo_ra_config__modem_preset__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex meshtastic__config__lo_ra_config__modem_preset__enum_values_by_name[9] =
{
  { "LONG_FAST", 0 },
  { "LONG_MODERATE", 7 },
  { "LONG_SLOW", 1 },
  { "MEDIUM_FAST", 4 },
  { "MEDIUM_SLOW", 3 },
  { "SHORT_FAST", 6 },
  { "SHORT_SLOW", 5 },
  { "SHORT_TURBO", 8 },
  { "VERY_LONG_SLOW", 2 },
};
const ProtobufCEnumDescriptor meshtastic__config__lo_ra_config__modem_preset__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.LoRaConfig.ModemPreset",
  "ModemPreset",
  "Meshtastic__Config__LoRaConfig__ModemPreset",
  "meshtastic",
  9,
  meshtastic__config__lo_ra_config__modem_preset__enum_values_by_number,
  9,
  meshtastic__config__lo_ra_config__modem_preset__enum_values_by_name,
  1,
  meshtastic__config__lo_ra_config__modem_preset__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__config__lo_ra_config__field_descriptors[18] =
{
  {
    "use_preset",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, use_preset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modem_preset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, modem_preset),
    &meshtastic__config__lo_ra_config__modem_preset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spread_factor",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, spread_factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coding_rate",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, coding_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frequency_offset",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, frequency_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "region",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, region),
    &meshtastic__config__lo_ra_config__region_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hop_limit",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, hop_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_enabled",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, tx_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_power",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, tx_power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_num",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, channel_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "override_duty_cycle",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, override_duty_cycle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sx126x_rx_boosted_gain",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, sx126x_rx_boosted_gain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "override_frequency",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, override_frequency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pa_fan_disabled",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, pa_fan_disabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ignore_incoming",
    103,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Meshtastic__Config__LoRaConfig, n_ignore_incoming),
    offsetof(Meshtastic__Config__LoRaConfig, ignore_incoming),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ignore_mqtt",
    104,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, ignore_mqtt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config_ok_to_mqtt",
    105,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__LoRaConfig, config_ok_to_mqtt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__lo_ra_config__field_indices_by_name[] = {
  2,   /* field[2] = bandwidth */
  10,   /* field[10] = channel_num */
  4,   /* field[4] = coding_rate */
  17,   /* field[17] = config_ok_to_mqtt */
  5,   /* field[5] = frequency_offset */
  7,   /* field[7] = hop_limit */
  15,   /* field[15] = ignore_incoming */
  16,   /* field[16] = ignore_mqtt */
  1,   /* field[1] = modem_preset */
  11,   /* field[11] = override_duty_cycle */
  13,   /* field[13] = override_frequency */
  14,   /* field[14] = pa_fan_disabled */
  6,   /* field[6] = region */
  3,   /* field[3] = spread_factor */
  12,   /* field[12] = sx126x_rx_boosted_gain */
  8,   /* field[8] = tx_enabled */
  9,   /* field[9] = tx_power */
  0,   /* field[0] = use_preset */
};
static const ProtobufCIntRange meshtastic__config__lo_ra_config__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 103, 15 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor meshtastic__config__lo_ra_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.LoRaConfig",
  "LoRaConfig",
  "Meshtastic__Config__LoRaConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__LoRaConfig),
  18,
  meshtastic__config__lo_ra_config__field_descriptors,
  meshtastic__config__lo_ra_config__field_indices_by_name,
  2,  meshtastic__config__lo_ra_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__lo_ra_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__config__bluetooth_config__pairing_mode__enum_values_by_number[3] =
{
  { "RANDOM_PIN", "MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE__RANDOM_PIN", 0 },
  { "FIXED_PIN", "MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE__FIXED_PIN", 1 },
  { "NO_PIN", "MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE__NO_PIN", 2 },
};
static const ProtobufCIntRange meshtastic__config__bluetooth_config__pairing_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex meshtastic__config__bluetooth_config__pairing_mode__enum_values_by_name[3] =
{
  { "FIXED_PIN", 1 },
  { "NO_PIN", 2 },
  { "RANDOM_PIN", 0 },
};
const ProtobufCEnumDescriptor meshtastic__config__bluetooth_config__pairing_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.Config.BluetoothConfig.PairingMode",
  "PairingMode",
  "Meshtastic__Config__BluetoothConfig__PairingMode",
  "meshtastic",
  3,
  meshtastic__config__bluetooth_config__pairing_mode__enum_values_by_number,
  3,
  meshtastic__config__bluetooth_config__pairing_mode__enum_values_by_name,
  1,
  meshtastic__config__bluetooth_config__pairing_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__config__bluetooth_config__field_descriptors[3] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__BluetoothConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__BluetoothConfig, mode),
    &meshtastic__config__bluetooth_config__pairing_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_pin",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__BluetoothConfig, fixed_pin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__bluetooth_config__field_indices_by_name[] = {
  0,   /* field[0] = enabled */
  2,   /* field[2] = fixed_pin */
  1,   /* field[1] = mode */
};
static const ProtobufCIntRange meshtastic__config__bluetooth_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor meshtastic__config__bluetooth_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.BluetoothConfig",
  "BluetoothConfig",
  "Meshtastic__Config__BluetoothConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__BluetoothConfig),
  3,
  meshtastic__config__bluetooth_config__field_descriptors,
  meshtastic__config__bluetooth_config__field_indices_by_name,
  1,  meshtastic__config__bluetooth_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__bluetooth_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__config__security_config__field_descriptors[7] =
{
  {
    "public_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__SecurityConfig, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__SecurityConfig, private_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "admin_key",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Meshtastic__Config__SecurityConfig, n_admin_key),
    offsetof(Meshtastic__Config__SecurityConfig, admin_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_managed",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__SecurityConfig, is_managed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_enabled",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__SecurityConfig, serial_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "debug_log_api_enabled",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__SecurityConfig, debug_log_api_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "admin_channel_enabled",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Config__SecurityConfig, admin_channel_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__security_config__field_indices_by_name[] = {
  6,   /* field[6] = admin_channel_enabled */
  2,   /* field[2] = admin_key */
  5,   /* field[5] = debug_log_api_enabled */
  3,   /* field[3] = is_managed */
  1,   /* field[1] = private_key */
  0,   /* field[0] = public_key */
  4,   /* field[4] = serial_enabled */
};
static const ProtobufCIntRange meshtastic__config__security_config__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor meshtastic__config__security_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.SecurityConfig",
  "SecurityConfig",
  "Meshtastic__Config__SecurityConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__SecurityConfig),
  7,
  meshtastic__config__security_config__field_descriptors,
  meshtastic__config__security_config__field_indices_by_name,
  2,  meshtastic__config__security_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__security_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define meshtastic__config__sessionkey_config__field_descriptors NULL
#define meshtastic__config__sessionkey_config__field_indices_by_name NULL
#define meshtastic__config__sessionkey_config__number_ranges NULL
const ProtobufCMessageDescriptor meshtastic__config__sessionkey_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config.SessionkeyConfig",
  "SessionkeyConfig",
  "Meshtastic__Config__SessionkeyConfig",
  "meshtastic",
  sizeof(Meshtastic__Config__SessionkeyConfig),
  0,
  meshtastic__config__sessionkey_config__field_descriptors,
  meshtastic__config__sessionkey_config__field_indices_by_name,
  0,  meshtastic__config__sessionkey_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__sessionkey_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__config__field_descriptors[9] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, device),
    &meshtastic__config__device_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, position),
    &meshtastic__config__position_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, power),
    &meshtastic__config__power_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, network),
    &meshtastic__config__network_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, display),
    &meshtastic__config__display_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lora",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, lora),
    &meshtastic__config__lo_ra_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bluetooth",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, bluetooth),
    &meshtastic__config__bluetooth_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "security",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, security),
    &meshtastic__config__security_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sessionkey",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__Config, payload_variant_case),
    offsetof(Meshtastic__Config, sessionkey),
    &meshtastic__config__sessionkey_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__config__field_indices_by_name[] = {
  6,   /* field[6] = bluetooth */
  0,   /* field[0] = device */
  4,   /* field[4] = display */
  5,   /* field[5] = lora */
  3,   /* field[3] = network */
  1,   /* field[1] = position */
  2,   /* field[2] = power */
  7,   /* field[7] = security */
  8,   /* field[8] = sessionkey */
};
static const ProtobufCIntRange meshtastic__config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor meshtastic__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Config",
  "Config",
  "Meshtastic__Config",
  "meshtastic",
  sizeof(Meshtastic__Config),
  9,
  meshtastic__config__field_descriptors,
  meshtastic__config__field_indices_by_name,
  1,  meshtastic__config__number_ranges,
  (ProtobufCMessageInit) meshtastic__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
