/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/config.proto */

#ifndef PROTOBUF_C_meshtastic_2fconfig_2eproto__INCLUDED
#define PROTOBUF_C_meshtastic_2fconfig_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Meshtastic__Config Meshtastic__Config;
typedef struct Meshtastic__Config__DeviceConfig Meshtastic__Config__DeviceConfig;
typedef struct Meshtastic__Config__PositionConfig Meshtastic__Config__PositionConfig;
typedef struct Meshtastic__Config__PowerConfig Meshtastic__Config__PowerConfig;
typedef struct Meshtastic__Config__NetworkConfig Meshtastic__Config__NetworkConfig;
typedef struct Meshtastic__Config__NetworkConfig__IpV4Config Meshtastic__Config__NetworkConfig__IpV4Config;
typedef struct Meshtastic__Config__DisplayConfig Meshtastic__Config__DisplayConfig;
typedef struct Meshtastic__Config__LoRaConfig Meshtastic__Config__LoRaConfig;
typedef struct Meshtastic__Config__BluetoothConfig Meshtastic__Config__BluetoothConfig;
typedef struct Meshtastic__Config__SecurityConfig Meshtastic__Config__SecurityConfig;
typedef struct Meshtastic__Config__SessionkeyConfig Meshtastic__Config__SessionkeyConfig;


/* --- enums --- */

/*
 * Defines the device's role on the Mesh network
 */
typedef enum _Meshtastic__Config__DeviceConfig__Role {
  /*
   * Description: App connected or stand alone messaging device.
   * Technical Details: Default Role
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT = 0,
  /*
   *  Description: Device that does not forward packets from other devices.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT_MUTE = 1,
  /*
   * Description: Infrastructure node for extending network coverage by relaying messages. Visible in Nodes list.
   * Technical Details: Mesh packets will prefer to be routed over this node. This node will not be used by client apps.
   *   The wifi radio and the oled screen will be put to sleep.
   *   This mode may still potentially have higher power usage due to it's preference in message rebroadcasting on the mesh.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__ROUTER = 2,
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__ROUTER_CLIENT = 3,
  /*
   * Description: Infrastructure node for extending network coverage by relaying messages with minimal overhead. Not visible in Nodes list.
   * Technical Details: Mesh packets will simply be rebroadcasted over this node. Nodes configured with this role will not originate NodeInfo, Position, Telemetry
   *   or any other packet type. They will simply rebroadcast any mesh packets on the same frequency, channel num, spread factor, and coding rate.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__REPEATER = 4,
  /*
   * Description: Broadcasts GPS position packets as priority.
   * Technical Details: Position Mesh packets will be prioritized higher and sent more frequently by default.
   *   When used in conjunction with power.is_power_saving = true, nodes will wake up,
   *   send position, and then sleep for position.position_broadcast_secs seconds.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__TRACKER = 5,
  /*
   * Description: Broadcasts telemetry packets as priority.
   * Technical Details: Telemetry Mesh packets will be prioritized higher and sent more frequently by default.
   *   When used in conjunction with power.is_power_saving = true, nodes will wake up,
   *   send environment telemetry, and then sleep for telemetry.environment_update_interval seconds.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__SENSOR = 6,
  /*
   * Description: Optimized for ATAK system communication and reduces routine broadcasts.
   * Technical Details: Used for nodes dedicated for connection to an ATAK EUD.
   *    Turns off many of the routine broadcasts to favor CoT packet stream
   *    from the Meshtastic ATAK plugin -> IMeshService -> Node
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__TAK = 7,
  /*
   * Description: Device that only broadcasts as needed for stealth or power savings.
   * Technical Details: Used for nodes that "only speak when spoken to"
   *    Turns all of the routine broadcasts but allows for ad-hoc communication
   *    Still rebroadcasts, but with local only rebroadcast mode (known meshes only)
   *    Can be used for clandestine operation or to dramatically reduce airtime / power consumption
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT_HIDDEN = 8,
  /*
   * Description: Broadcasts location as message to default channel regularly for to assist with device recovery.
   * Technical Details: Used to automatically send a text message to the mesh
   *    with the current position of the device on a frequent interval:
   *    "I'm lost! Position: lat / long"
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__LOST_AND_FOUND = 9,
  /*
   * Description: Enables automatic TAK PLI broadcasts and reduces routine broadcasts.
   * Technical Details: Turns off many of the routine broadcasts to favor ATAK CoT packet stream
   *    and automatic TAK PLI (position location information) broadcasts.
   *    Uses position module configuration to determine TAK PLI broadcast interval.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__TAK_TRACKER = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE)
} Meshtastic__Config__DeviceConfig__Role;
/*
 * Defines the device's behavior for how messages are rebroadcast
 */
typedef enum _Meshtastic__Config__DeviceConfig__RebroadcastMode {
  /*
   * Default behavior.
   * Rebroadcast any observed message, if it was on our private channel or from another mesh with the same lora params.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__ALL = 0,
  /*
   * Same as behavior as ALL but skips packet decoding and simply rebroadcasts them.
   * Only available in Repeater role. Setting this on any other roles will result in ALL behavior.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__ALL_SKIP_DECODING = 1,
  /*
   * Ignores observed messages from foreign meshes that are open or those which it cannot decrypt.
   * Only rebroadcasts message on the nodes local primary / secondary channels.
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__LOCAL_ONLY = 2,
  /*
   * Ignores observed messages from foreign meshes like LOCAL_ONLY,
   * but takes it step further by also ignoring messages from nodenums not in the node's known list (NodeDB)
   */
  MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__KNOWN_ONLY = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE)
} Meshtastic__Config__DeviceConfig__RebroadcastMode;
/*
 * Bit field of boolean configuration options, indicating which optional
 * fields to include when assembling POSITION messages.
 * Longitude, latitude, altitude, speed, heading, and DOP
 * are always included (also time if GPS-synced)
 * NOTE: the more fields are included, the larger the message will be -
 *   leading to longer airtime and a higher risk of packet loss
 */
typedef enum _Meshtastic__Config__PositionConfig__PositionFlags {
  /*
   * Required for compilation
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__UNSET = 0,
  /*
   * Include an altitude value (if available)
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__ALTITUDE = 1,
  /*
   * Altitude value is MSL
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__ALTITUDE_MSL = 2,
  /*
   * Include geoidal separation
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__GEOIDAL_SEPARATION = 4,
  /*
   * Include the DOP value ; PDOP used by default, see below
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__DOP = 8,
  /*
   * If POS_DOP set, send separate HDOP / VDOP values instead of PDOP
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__HVDOP = 16,
  /*
   * Include number of "satellites in view"
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__SATINVIEW = 32,
  /*
   * Include a sequence number incremented per packet
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__SEQ_NO = 64,
  /*
   * Include positional timestamp (from GPS solution)
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__TIMESTAMP = 128,
  /*
   * Include positional heading
   * Intended for use with vehicle not walking speeds
   * walking speeds are likely to be error prone like the compass
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__HEADING = 256,
  /*
   * Include positional speed
   * Intended for use with vehicle not walking speeds
   * walking speeds are likely to be error prone like the compass
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS__SPEED = 512
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__POSITION_CONFIG__POSITION_FLAGS)
} Meshtastic__Config__PositionConfig__PositionFlags;
typedef enum _Meshtastic__Config__PositionConfig__GpsMode {
  /*
   * GPS is present but disabled
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE__DISABLED = 0,
  /*
   * GPS is present and enabled
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE__ENABLED = 1,
  /*
   * GPS is not present on the device
   */
  MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE__NOT_PRESENT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE)
} Meshtastic__Config__PositionConfig__GpsMode;
typedef enum _Meshtastic__Config__NetworkConfig__AddressMode {
  /*
   * obtain ip address via DHCP
   */
  MESHTASTIC__CONFIG__NETWORK_CONFIG__ADDRESS_MODE__DHCP = 0,
  /*
   * use static ip address
   */
  MESHTASTIC__CONFIG__NETWORK_CONFIG__ADDRESS_MODE__STATIC = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__NETWORK_CONFIG__ADDRESS_MODE)
} Meshtastic__Config__NetworkConfig__AddressMode;
/*
 * How the GPS coordinates are displayed on the OLED screen.
 */
typedef enum _Meshtastic__Config__DisplayConfig__GpsCoordinateFormat {
  /*
   * GPS coordinates are displayed in the normal decimal degrees format:
   * DD.DDDDDD DDD.DDDDDD
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__DEC = 0,
  /*
   * GPS coordinates are displayed in the degrees minutes seconds format:
   * DD°MM'SS"C DDD°MM'SS"C, where C is the compass point representing the locations quadrant
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__DMS = 1,
  /*
   * Universal Transverse Mercator format:
   * ZZB EEEEEE NNNNNNN, where Z is zone, B is band, E is easting, N is northing
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__UTM = 2,
  /*
   * Military Grid Reference System format:
   * ZZB CD EEEEE NNNNN, where Z is zone, B is band, C is the east 100k square, D is the north 100k square,
   * E is easting, N is northing
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__MGRS = 3,
  /*
   * Open Location Code (aka Plus Codes).
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__OLC = 4,
  /*
   * Ordnance Survey Grid Reference (the National Grid System of the UK).
   * Format: AB EEEEE NNNNN, where A is the east 100k square, B is the north 100k square,
   * E is the easting, N is the northing
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__OSGR = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT)
} Meshtastic__Config__DisplayConfig__GpsCoordinateFormat;
/*
 * Unit display preference
 */
typedef enum _Meshtastic__Config__DisplayConfig__DisplayUnits {
  /*
   * Metric (Default)
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_UNITS__METRIC = 0,
  /*
   * Imperial
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_UNITS__IMPERIAL = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_UNITS)
} Meshtastic__Config__DisplayConfig__DisplayUnits;
/*
 * Override OLED outo detect with this if it fails.
 */
typedef enum _Meshtastic__Config__DisplayConfig__OledType {
  /*
   * Default / Auto
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_AUTO = 0,
  /*
   * Default / Auto
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_SSD1306 = 1,
  /*
   * Default / Auto
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_SH1106 = 2,
  /*
   * Can not be auto detected but set by proto. Used for 128x128 screens
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_SH1107 = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE)
} Meshtastic__Config__DisplayConfig__OledType;
typedef enum _Meshtastic__Config__DisplayConfig__DisplayMode {
  /*
   * Default. The old style for the 128x64 OLED screen
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__DEFAULT = 0,
  /*
   * Rearrange display elements to cater for bicolor OLED displays
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__TWOCOLOR = 1,
  /*
   * Same as TwoColor, but with inverted top bar. Not so good for Epaper displays
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__INVERTED = 2,
  /*
   * TFT Full Color Displays (not implemented yet)
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__COLOR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE)
} Meshtastic__Config__DisplayConfig__DisplayMode;
typedef enum _Meshtastic__Config__DisplayConfig__CompassOrientation {
  /*
   * The compass and the display are in the same orientation.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_0 = 0,
  /*
   * Rotate the compass by 90 degrees.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_90 = 1,
  /*
   * Rotate the compass by 180 degrees.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_180 = 2,
  /*
   * Rotate the compass by 270 degrees.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_270 = 3,
  /*
   * Don't rotate the compass, but invert the result.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_0_INVERTED = 4,
  /*
   * Rotate the compass by 90 degrees and invert.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_90_INVERTED = 5,
  /*
   * Rotate the compass by 180 degrees and invert.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_180_INVERTED = 6,
  /*
   * Rotate the compass by 270 degrees and invert.
   */
  MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_270_INVERTED = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION)
} Meshtastic__Config__DisplayConfig__CompassOrientation;
typedef enum _Meshtastic__Config__LoRaConfig__RegionCode {
  /*
   * Region is not set
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UNSET = 0,
  /*
   * United States
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__US = 1,
  /*
   * European Union 433mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__EU_433 = 2,
  /*
   * European Union 868mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__EU_868 = 3,
  /*
   * China
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__CN = 4,
  /*
   * Japan
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__JP = 5,
  /*
   * Australia / New Zealand
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__ANZ = 6,
  /*
   * Korea
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__KR = 7,
  /*
   * Taiwan
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__TW = 8,
  /*
   * Russia
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__RU = 9,
  /*
   * India
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__IN = 10,
  /*
   * New Zealand 865mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__NZ_865 = 11,
  /*
   * Thailand
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__TH = 12,
  /*
   * WLAN Band
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__LORA_24 = 13,
  /*
   * Ukraine 433mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UA_433 = 14,
  /*
   * Ukraine 868mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UA_868 = 15,
  /*
   * Malaysia 433mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__MY_433 = 16,
  /*
   * Malaysia 919mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__MY_919 = 17,
  /*
   * Singapore 923mhz
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__SG_923 = 18
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE)
} Meshtastic__Config__LoRaConfig__RegionCode;
/*
 * Standard predefined channel settings
 * Note: these mappings must match ModemPreset Choice in the device code.
 */
typedef enum _Meshtastic__Config__LoRaConfig__ModemPreset {
  /*
   * Long Range - Fast
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_FAST = 0,
  /*
   * Long Range - Slow
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_SLOW = 1,
  /*
   * Very Long Range - Slow
   * Deprecated in 2.5: Works only with txco and is unusably slow
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__VERY_LONG_SLOW = 2,
  /*
   * Medium Range - Slow
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__MEDIUM_SLOW = 3,
  /*
   * Medium Range - Fast
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__MEDIUM_FAST = 4,
  /*
   * Short Range - Slow
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__SHORT_SLOW = 5,
  /*
   * Short Range - Fast
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__SHORT_FAST = 6,
  /*
   * Long Range - Moderately Fast
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_MODERATE = 7,
  /*
   * Short Range - Turbo
   * This is the fastest preset and the only one with 500kHz bandwidth.
   * It is not legal to use in all regions due to this wider bandwidth.
   */
  MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__SHORT_TURBO = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET)
} Meshtastic__Config__LoRaConfig__ModemPreset;
typedef enum _Meshtastic__Config__BluetoothConfig__PairingMode {
  /*
   * Device generates a random PIN that will be shown on the screen of the device for pairing
   */
  MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE__RANDOM_PIN = 0,
  /*
   * Device requires a specified fixed PIN for pairing
   */
  MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE__FIXED_PIN = 1,
  /*
   * Device requires no PIN for pairing
   */
  MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE__NO_PIN = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE)
} Meshtastic__Config__BluetoothConfig__PairingMode;

/* --- messages --- */

/*
 * Configuration
 */
struct  Meshtastic__Config__DeviceConfig
{
  ProtobufCMessage base;
  /*
   * Sets the role of node
   */
  Meshtastic__Config__DeviceConfig__Role role;
  /*
   * Disabling this will disable the SerialConsole by not initilizing the StreamAPI
   * Moved to SecurityConfig
   */
  protobuf_c_boolean serial_enabled PROTOBUF_C__DEPRECATED;
  /*
   * For boards without a hard wired button, this is the pin number that will be used
   * Boards that have more than one button can swap the function with this one. defaults to BUTTON_PIN if defined.
   */
  uint32_t button_gpio;
  /*
   * For boards without a PWM buzzer, this is the pin number that will be used
   * Defaults to PIN_BUZZER if defined.
   */
  uint32_t buzzer_gpio;
  /*
   * Sets the role of node
   */
  Meshtastic__Config__DeviceConfig__RebroadcastMode rebroadcast_mode;
  /*
   * Send our nodeinfo this often
   * Defaults to 900 Seconds (15 minutes)
   */
  uint32_t node_info_broadcast_secs;
  /*
   * Treat double tap interrupt on supported accelerometers as a button press if set to true
   */
  protobuf_c_boolean double_tap_as_button_press;
  /*
   * If true, device is considered to be "managed" by a mesh administrator
   * Clients should then limit available configuration and administrative options inside the user interface
   * Moved to SecurityConfig
   */
  protobuf_c_boolean is_managed PROTOBUF_C__DEPRECATED;
  /*
   * Disables the triple-press of user button to enable or disable GPS
   */
  protobuf_c_boolean disable_triple_click;
  /*
   * POSIX Timezone definition string from https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv.
   */
  char *tzdef;
  /*
   * If true, disable the default blinking LED (LED_PIN) behavior on the device 
   */
  protobuf_c_boolean led_heartbeat_disabled;
};
#define MESHTASTIC__CONFIG__DEVICE_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__device_config__descriptor) \
    , MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT, 0, 0, 0, MESHTASTIC__CONFIG__DEVICE_CONFIG__REBROADCAST_MODE__ALL, 0, 0, 0, 0, (char *)protobuf_c_empty_string, 0 }


/*
 * Position Config
 */
struct  Meshtastic__Config__PositionConfig
{
  ProtobufCMessage base;
  /*
   * We should send our position this often (but only if it has changed significantly)
   * Defaults to 15 minutes
   */
  uint32_t position_broadcast_secs;
  /*
   * Adaptive position braoadcast, which is now the default.
   */
  protobuf_c_boolean position_broadcast_smart_enabled;
  /*
   * If set, this node is at a fixed position.
   * We will generate GPS position updates at the regular interval, but use whatever the last lat/lon/alt we have for the node.
   * The lat/lon/alt can be set by an internal GPS or with the help of the app.
   */
  protobuf_c_boolean fixed_position;
  /*
   * Is GPS enabled for this node?
   */
  protobuf_c_boolean gps_enabled PROTOBUF_C__DEPRECATED;
  /*
   * How often should we try to get GPS position (in seconds)
   * or zero for the default of once every 30 seconds
   * or a very large value (maxint) to update only once at boot.
   */
  uint32_t gps_update_interval;
  /*
   * Deprecated in favor of using smart / regular broadcast intervals as implicit attempt time
   */
  uint32_t gps_attempt_time PROTOBUF_C__DEPRECATED;
  /*
   * Bit field of boolean configuration options for POSITION messages
   * (bitwise OR of PositionFlags)
   */
  uint32_t position_flags;
  /*
   * (Re)define GPS_RX_PIN for your board.
   */
  uint32_t rx_gpio;
  /*
   * (Re)define GPS_TX_PIN for your board.
   */
  uint32_t tx_gpio;
  /*
   * The minimum distance in meters traveled (since the last send) before we can send a position to the mesh if position_broadcast_smart_enabled
   */
  uint32_t broadcast_smart_minimum_distance;
  /*
   * The minimum number of seconds (since the last send) before we can send a position to the mesh if position_broadcast_smart_enabled
   */
  uint32_t broadcast_smart_minimum_interval_secs;
  /*
   * (Re)define PIN_GPS_EN for your board.
   */
  uint32_t gps_en_gpio;
  /*
   * Set where GPS is enabled, disabled, or not present
   */
  Meshtastic__Config__PositionConfig__GpsMode gps_mode;
};
#define MESHTASTIC__CONFIG__POSITION_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__position_config__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, MESHTASTIC__CONFIG__POSITION_CONFIG__GPS_MODE__DISABLED }


/*
 * Power Config\
 * See [Power Config](/docs/settings/config/power) for additional power config details.
 */
struct  Meshtastic__Config__PowerConfig
{
  ProtobufCMessage base;
  /*
   * Description: Will sleep everything as much as possible, for the tracker and sensor role this will also include the lora radio. 
   * Don't use this setting if you want to use your device with the phone apps or are using a device without a user button.
   * Technical Details: Works for ESP32 devices and NRF52 devices in the Sensor or Tracker roles
   */
  protobuf_c_boolean is_power_saving;
  /*
   *  Description: If non-zero, the device will fully power off this many seconds after external power is removed.
   */
  uint32_t on_battery_shutdown_after_secs;
  /*
   * Ratio of voltage divider for battery pin eg. 3.20 (R1=100k, R2=220k)
   * Overrides the ADC_MULTIPLIER defined in variant for battery voltage calculation.
   * https://meshtastic.org/docs/configuration/radio/power/#adc-multiplier-override
   * Should be set to floating point value between 2 and 6
   */
  float adc_multiplier_override;
  /*
   *  Description: The number of seconds for to wait before turning off BLE in No Bluetooth states
   *  Technical Details: ESP32 Only 0 for default of 1 minute
   */
  uint32_t wait_bluetooth_secs;
  /*
   * Super Deep Sleep Seconds
   * While in Light Sleep if mesh_sds_timeout_secs is exceeded we will lower into super deep sleep
   * for this value (default 1 year) or a button press
   * 0 for default of one year
   */
  uint32_t sds_secs;
  /*
   * Description: In light sleep the CPU is suspended, LoRa radio is on, BLE is off an GPS is on
   * Technical Details: ESP32 Only 0 for default of 300
   */
  uint32_t ls_secs;
  /*
   * Description: While in light sleep when we receive packets on the LoRa radio we will wake and handle them and stay awake in no BLE mode for this value
   * Technical Details: ESP32 Only 0 for default of 10 seconds
   */
  uint32_t min_wake_secs;
  /*
   * I2C address of INA_2XX to use for reading device battery voltage
   */
  uint32_t device_battery_ina_address;
  /*
   * If non-zero, we want powermon log outputs.  With the particular (bitfield) sources enabled.
   * Note: we picked an ID of 32 so that lower more efficient IDs can be used for more frequently used options.
   */
  uint64_t powermon_enables;
};
#define MESHTASTIC__CONFIG__POWER_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__power_config__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  Meshtastic__Config__NetworkConfig__IpV4Config
{
  ProtobufCMessage base;
  /*
   * Static IP address
   */
  uint32_t ip;
  /*
   * Static gateway address
   */
  uint32_t gateway;
  /*
   * Static subnet mask
   */
  uint32_t subnet;
  /*
   * Static DNS server address
   */
  uint32_t dns;
};
#define MESHTASTIC__CONFIG__NETWORK_CONFIG__IP_V4_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__network_config__ip_v4_config__descriptor) \
    , 0, 0, 0, 0 }


/*
 * Network Config
 */
struct  Meshtastic__Config__NetworkConfig
{
  ProtobufCMessage base;
  /*
   * Enable WiFi (disables Bluetooth)
   */
  protobuf_c_boolean wifi_enabled;
  /*
   * If set, this node will try to join the specified wifi network and
   * acquire an address via DHCP
   */
  char *wifi_ssid;
  /*
   * If set, will be use to authenticate to the named wifi
   */
  char *wifi_psk;
  /*
   * NTP server to use if WiFi is conneced, defaults to `0.pool.ntp.org`
   */
  char *ntp_server;
  /*
   * Enable Ethernet
   */
  protobuf_c_boolean eth_enabled;
  /*
   * acquire an address via DHCP or assign static
   */
  Meshtastic__Config__NetworkConfig__AddressMode address_mode;
  /*
   * struct to keep static address
   */
  Meshtastic__Config__NetworkConfig__IpV4Config *ipv4_config;
  /*
   * rsyslog Server and Port
   */
  char *rsyslog_server;
};
#define MESHTASTIC__CONFIG__NETWORK_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__network_config__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, MESHTASTIC__CONFIG__NETWORK_CONFIG__ADDRESS_MODE__DHCP, NULL, (char *)protobuf_c_empty_string }


/*
 * Display Config
 */
struct  Meshtastic__Config__DisplayConfig
{
  ProtobufCMessage base;
  /*
   * Number of seconds the screen stays on after pressing the user button or receiving a message
   * 0 for default of one minute MAXUINT for always on
   */
  uint32_t screen_on_secs;
  /*
   * How the GPS coordinates are formatted on the OLED screen.
   */
  Meshtastic__Config__DisplayConfig__GpsCoordinateFormat gps_format;
  /*
   * Automatically toggles to the next page on the screen like a carousel, based the specified interval in seconds.
   * Potentially useful for devices without user buttons.
   */
  uint32_t auto_screen_carousel_secs;
  /*
   * If this is set, the displayed compass will always point north. if unset, the old behaviour
   * (top of display is heading direction) is used.
   */
  protobuf_c_boolean compass_north_top;
  /*
   * Flip screen vertically, for cases that mount the screen upside down
   */
  protobuf_c_boolean flip_screen;
  /*
   * Perferred display units
   */
  Meshtastic__Config__DisplayConfig__DisplayUnits units;
  /*
   * Override auto-detect in screen
   */
  Meshtastic__Config__DisplayConfig__OledType oled;
  /*
   * Display Mode
   */
  Meshtastic__Config__DisplayConfig__DisplayMode displaymode;
  /*
   * Print first line in pseudo-bold? FALSE is original style, TRUE is bold
   */
  protobuf_c_boolean heading_bold;
  /*
   * Should we wake the screen up on accelerometer detected motion or tap
   */
  protobuf_c_boolean wake_on_tap_or_motion;
  /*
   * Indicates how to rotate or invert the compass output to accurate display on the display.
   */
  Meshtastic__Config__DisplayConfig__CompassOrientation compass_orientation;
};
#define MESHTASTIC__CONFIG__DISPLAY_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__display_config__descriptor) \
    , 0, MESHTASTIC__CONFIG__DISPLAY_CONFIG__GPS_COORDINATE_FORMAT__DEC, 0, 0, 0, MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_UNITS__METRIC, MESHTASTIC__CONFIG__DISPLAY_CONFIG__OLED_TYPE__OLED_AUTO, MESHTASTIC__CONFIG__DISPLAY_CONFIG__DISPLAY_MODE__DEFAULT, 0, 0, MESHTASTIC__CONFIG__DISPLAY_CONFIG__COMPASS_ORIENTATION__DEGREES_0 }


/*
 * Lora Config
 */
struct  Meshtastic__Config__LoRaConfig
{
  ProtobufCMessage base;
  /*
   * When enabled, the `modem_preset` fields will be adhered to, else the `bandwidth`/`spread_factor`/`coding_rate`
   * will be taked from their respective manually defined fields
   */
  protobuf_c_boolean use_preset;
  /*
   * Either modem_config or bandwidth/spreading/coding will be specified - NOT BOTH.
   * As a heuristic: If bandwidth is specified, do not use modem_config.
   * Because protobufs take ZERO space when the value is zero this works out nicely.
   * This value is replaced by bandwidth/spread_factor/coding_rate.
   * If you'd like to experiment with other options add them to MeshRadio.cpp in the device code.
   */
  Meshtastic__Config__LoRaConfig__ModemPreset modem_preset;
  /*
   * Bandwidth in MHz
   * Certain bandwidth numbers are 'special' and will be converted to the
   * appropriate floating point value: 31 -> 31.25MHz
   */
  uint32_t bandwidth;
  /*
   * A number from 7 to 12.
   * Indicates number of chirps per symbol as 1<<spread_factor.
   */
  uint32_t spread_factor;
  /*
   * The denominator of the coding rate.
   * ie for 4/5, the value is 5. 4/8 the value is 8.
   */
  uint32_t coding_rate;
  /*
   * This parameter is for advanced users with advanced test equipment, we do not recommend most users use it.
   * A frequency offset that is added to to the calculated band center frequency.
   * Used to correct for crystal calibration errors.
   */
  float frequency_offset;
  /*
   * The region code for the radio (US, CN, EU433, etc...)
   */
  Meshtastic__Config__LoRaConfig__RegionCode region;
  /*
   * Maximum number of hops. This can't be greater than 7.
   * Default of 3
   * Attempting to set a value > 7 results in the default
   */
  uint32_t hop_limit;
  /*
   * Disable TX from the LoRa radio. Useful for hot-swapping antennas and other tests.
   * Defaults to false
   */
  protobuf_c_boolean tx_enabled;
  /*
   * If zero, then use default max legal continuous power (ie. something that won't
   * burn out the radio hardware)
   * In most cases you should use zero here.
   * Units are in dBm.
   */
  int32_t tx_power;
  /*
   * This controls the actual hardware frequency the radio transmits on.
   * Most users should never need to be exposed to this field/concept.
   * A channel number between 1 and NUM_CHANNELS (whatever the max is in the current region).
   * If ZERO then the rule is "use the old channel name hash based
   * algorithm to derive the channel number")
   * If using the hash algorithm the channel number will be: hash(channel_name) %
   * NUM_CHANNELS (Where num channels depends on the regulatory region).
   */
  uint32_t channel_num;
  /*
   * If true, duty cycle limits will be exceeded and thus you're possibly not following
   * the local regulations if you're not a HAM.
   * Has no effect if the duty cycle of the used region is 100%.
   */
  protobuf_c_boolean override_duty_cycle;
  /*
   * If true, sets RX boosted gain mode on SX126X based radios
   */
  protobuf_c_boolean sx126x_rx_boosted_gain;
  /*
   * This parameter is for advanced users and licensed HAM radio operators.
   * Ignore Channel Calculation and use this frequency instead. The frequency_offset
   * will still be applied. This will allow you to use out-of-band frequencies.
   * Please respect your local laws and regulations. If you are a HAM, make sure you
   * enable HAM mode and turn off encryption.
   */
  float override_frequency;
  /*
   * If true, disable the build-in PA FAN using pin define in RF95_FAN_EN.
   */
  protobuf_c_boolean pa_fan_disabled;
  /*
   * For testing it is useful sometimes to force a node to never listen to
   * particular other nodes (simulating radio out of range). All nodenums listed
   * in ignore_incoming will have packets they send dropped on receive (by router.cpp)
   */
  size_t n_ignore_incoming;
  uint32_t *ignore_incoming;
  /*
   * If true, the device will not process any packets received via LoRa that passed via MQTT anywhere on the path towards it.
   */
  protobuf_c_boolean ignore_mqtt;
  /*
   * Sets the ok_to_mqtt bit on outgoing packets
   */
  protobuf_c_boolean config_ok_to_mqtt;
};
#define MESHTASTIC__CONFIG__LO_RA_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__lo_ra_config__descriptor) \
    , 0, MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_FAST, 0, 0, 0, 0, MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UNSET, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0, 0 }


struct  Meshtastic__Config__BluetoothConfig
{
  ProtobufCMessage base;
  /*
   * Enable Bluetooth on the device
   */
  protobuf_c_boolean enabled;
  /*
   * Determines the pairing strategy for the device
   */
  Meshtastic__Config__BluetoothConfig__PairingMode mode;
  /*
   * Specified PIN for PairingMode.FixedPin
   */
  uint32_t fixed_pin;
};
#define MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__bluetooth_config__descriptor) \
    , 0, MESHTASTIC__CONFIG__BLUETOOTH_CONFIG__PAIRING_MODE__RANDOM_PIN, 0 }


struct  Meshtastic__Config__SecurityConfig
{
  ProtobufCMessage base;
  /*
   * The public key of the user's device.
   * Sent out to other nodes on the mesh to allow them to compute a shared secret key.
   */
  ProtobufCBinaryData public_key;
  /*
   * The private key of the device.
   * Used to create a shared key with a remote device.
   */
  ProtobufCBinaryData private_key;
  /*
   * The public key authorized to send admin messages to this node.
   */
  size_t n_admin_key;
  ProtobufCBinaryData *admin_key;
  /*
   * If true, device is considered to be "managed" by a mesh administrator via admin messages
   * Device is managed by a mesh administrator.
   */
  protobuf_c_boolean is_managed;
  /*
   * Serial Console over the Stream API."
   */
  protobuf_c_boolean serial_enabled;
  /*
   * By default we turn off logging as soon as an API client connects (to keep shared serial link quiet).
   * Output live debug logging over serial or bluetooth is set to true.
   */
  protobuf_c_boolean debug_log_api_enabled;
  /*
   * Allow incoming device control over the insecure legacy admin channel.
   */
  protobuf_c_boolean admin_channel_enabled;
};
#define MESHTASTIC__CONFIG__SECURITY_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__security_config__descriptor) \
    , {0,NULL}, {0,NULL}, 0,NULL, 0, 0, 0, 0 }


/*
 * Blank config request, strictly for getting the session key
 */
struct  Meshtastic__Config__SessionkeyConfig
{
  ProtobufCMessage base;
};
#define MESHTASTIC__CONFIG__SESSIONKEY_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__sessionkey_config__descriptor) \
     }


typedef enum {
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT__NOT_SET = 0,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_DEVICE = 1,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_POSITION = 2,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_POWER = 3,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_NETWORK = 4,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_DISPLAY = 5,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_LORA = 6,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_BLUETOOTH = 7,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_SECURITY = 8,
  MESHTASTIC__CONFIG__PAYLOAD_VARIANT_SESSIONKEY = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__CONFIG__PAYLOAD_VARIANT__CASE)
} Meshtastic__Config__PayloadVariantCase;

struct  Meshtastic__Config
{
  ProtobufCMessage base;
  Meshtastic__Config__PayloadVariantCase payload_variant_case;
  union {
    Meshtastic__Config__BluetoothConfig *bluetooth;
    Meshtastic__Config__DeviceConfig *device;
    Meshtastic__Config__DisplayConfig *display;
    Meshtastic__Config__LoRaConfig *lora;
    Meshtastic__Config__NetworkConfig *network;
    Meshtastic__Config__PositionConfig *position;
    Meshtastic__Config__PowerConfig *power;
    Meshtastic__Config__SecurityConfig *security;
    Meshtastic__Config__SessionkeyConfig *sessionkey;
  };
};
#define MESHTASTIC__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__config__descriptor) \
    , MESHTASTIC__CONFIG__PAYLOAD_VARIANT__NOT_SET, {0} }


/* Meshtastic__Config__DeviceConfig methods */
void   meshtastic__config__device_config__init
                     (Meshtastic__Config__DeviceConfig         *message);
/* Meshtastic__Config__PositionConfig methods */
void   meshtastic__config__position_config__init
                     (Meshtastic__Config__PositionConfig         *message);
/* Meshtastic__Config__PowerConfig methods */
void   meshtastic__config__power_config__init
                     (Meshtastic__Config__PowerConfig         *message);
/* Meshtastic__Config__NetworkConfig__IpV4Config methods */
void   meshtastic__config__network_config__ip_v4_config__init
                     (Meshtastic__Config__NetworkConfig__IpV4Config         *message);
/* Meshtastic__Config__NetworkConfig methods */
void   meshtastic__config__network_config__init
                     (Meshtastic__Config__NetworkConfig         *message);
/* Meshtastic__Config__DisplayConfig methods */
void   meshtastic__config__display_config__init
                     (Meshtastic__Config__DisplayConfig         *message);
/* Meshtastic__Config__LoRaConfig methods */
void   meshtastic__config__lo_ra_config__init
                     (Meshtastic__Config__LoRaConfig         *message);
/* Meshtastic__Config__BluetoothConfig methods */
void   meshtastic__config__bluetooth_config__init
                     (Meshtastic__Config__BluetoothConfig         *message);
/* Meshtastic__Config__SecurityConfig methods */
void   meshtastic__config__security_config__init
                     (Meshtastic__Config__SecurityConfig         *message);
/* Meshtastic__Config__SessionkeyConfig methods */
void   meshtastic__config__sessionkey_config__init
                     (Meshtastic__Config__SessionkeyConfig         *message);
/* Meshtastic__Config methods */
void   meshtastic__config__init
                     (Meshtastic__Config         *message);
size_t meshtastic__config__get_packed_size
                     (const Meshtastic__Config   *message);
size_t meshtastic__config__pack
                     (const Meshtastic__Config   *message,
                      uint8_t             *out);
size_t meshtastic__config__pack_to_buffer
                     (const Meshtastic__Config   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__Config *
       meshtastic__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__config__free_unpacked
                     (Meshtastic__Config *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Meshtastic__Config__DeviceConfig_Closure)
                 (const Meshtastic__Config__DeviceConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__PositionConfig_Closure)
                 (const Meshtastic__Config__PositionConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__PowerConfig_Closure)
                 (const Meshtastic__Config__PowerConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__NetworkConfig__IpV4Config_Closure)
                 (const Meshtastic__Config__NetworkConfig__IpV4Config *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__NetworkConfig_Closure)
                 (const Meshtastic__Config__NetworkConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__DisplayConfig_Closure)
                 (const Meshtastic__Config__DisplayConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__LoRaConfig_Closure)
                 (const Meshtastic__Config__LoRaConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__BluetoothConfig_Closure)
                 (const Meshtastic__Config__BluetoothConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__SecurityConfig_Closure)
                 (const Meshtastic__Config__SecurityConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config__SessionkeyConfig_Closure)
                 (const Meshtastic__Config__SessionkeyConfig *message,
                  void *closure_data);
typedef void (*Meshtastic__Config_Closure)
                 (const Meshtastic__Config *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor meshtastic__config__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__device_config__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__device_config__role__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__device_config__rebroadcast_mode__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__position_config__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__position_config__position_flags__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__position_config__gps_mode__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__power_config__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__network_config__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__network_config__ip_v4_config__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__network_config__address_mode__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__display_config__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__display_config__gps_coordinate_format__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__display_config__display_units__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__display_config__oled_type__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__display_config__display_mode__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__display_config__compass_orientation__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__lo_ra_config__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__lo_ra_config__region_code__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__lo_ra_config__modem_preset__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__bluetooth_config__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__config__bluetooth_config__pairing_mode__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__security_config__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__config__sessionkey_config__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshtastic_2fconfig_2eproto__INCLUDED */
