/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/deviceonly.proto */

#ifndef PROTOBUF_C_meshtastic_2fdeviceonly_2eproto__INCLUDED
#define PROTOBUF_C_meshtastic_2fdeviceonly_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "meshtastic/channel.pb-c.h"
#include "meshtastic/localonly.pb-c.h"
#include "meshtastic/mesh.pb-c.h"
#include "meshtastic/telemetry.pb-c.h"
#include "meshtastic/config.pb-c.h"
#include "nanopb.pb-c.h"

typedef struct Meshtastic__PositionLite Meshtastic__PositionLite;
typedef struct Meshtastic__UserLite Meshtastic__UserLite;
typedef struct Meshtastic__NodeInfoLite Meshtastic__NodeInfoLite;
typedef struct Meshtastic__DeviceState Meshtastic__DeviceState;
typedef struct Meshtastic__ChannelFile Meshtastic__ChannelFile;
typedef struct Meshtastic__OEMStore Meshtastic__OEMStore;


/* --- enums --- */

/*
 * Font sizes for the device screen
 */
typedef enum _Meshtastic__ScreenFonts {
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__SCREEN_FONTS__FONT_SMALL = 0,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__SCREEN_FONTS__FONT_MEDIUM = 1,
  /*
   * TODO: REPLACE
   */
  MESHTASTIC__SCREEN_FONTS__FONT_LARGE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__SCREEN_FONTS)
} Meshtastic__ScreenFonts;

/* --- messages --- */

/*
 * Position with static location information only for NodeDBLite
 */
struct  Meshtastic__PositionLite
{
  ProtobufCMessage base;
  /*
   * The new preferred location encoding, multiply by 1e-7 to get degrees
   * in floating point
   */
  int32_t latitude_i;
  /*
   * TODO: REPLACE
   */
  int32_t longitude_i;
  /*
   * In meters above MSL (but see issue #359)
   */
  int32_t altitude;
  /*
   * This is usually not sent over the mesh (to save space), but it is sent
   * from the phone so that the local device can set its RTC If it is sent over
   * the mesh (because there are devices on the mesh without GPS), it will only
   * be sent by devices which has a hardware GPS clock.
   * seconds since 1970
   */
  uint32_t time;
  /*
   * TODO: REPLACE
   */
  Meshtastic__Position__LocSource location_source;
};
#define MESHTASTIC__POSITION_LITE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__position_lite__descriptor) \
    , 0, 0, 0, 0, MESHTASTIC__POSITION__LOC_SOURCE__LOC_UNSET }


struct  Meshtastic__UserLite
{
  ProtobufCMessage base;
  /*
   * This is the addr of the radio.
   */
  ProtobufCBinaryData macaddr PROTOBUF_C__DEPRECATED;
  /*
   * A full name for this user, i.e. "Kevin Hester"
   */
  char *long_name;
  /*
   * A VERY short name, ideally two characters.
   * Suitable for a tiny OLED screen
   */
  char *short_name;
  /*
   * TBEAM, HELTEC, etc...
   * Starting in 1.2.11 moved to hw_model enum in the NodeInfo object.
   * Apps will still need the string here for older builds
   * (so OTA update can find the right image), but if the enum is available it will be used instead.
   */
  Meshtastic__HardwareModel hw_model;
  /*
   * In some regions Ham radio operators have different bandwidth limitations than others.
   * If this user is a licensed operator, set this flag.
   * Also, "long_name" should be their licence number.
   */
  protobuf_c_boolean is_licensed;
  /*
   * Indicates that the user's role in the mesh
   */
  Meshtastic__Config__DeviceConfig__Role role;
  /*
   * The public key of the user's device.
   * This is sent out to other nodes on the mesh to allow them to compute a shared secret key.
   */
  ProtobufCBinaryData public_key;
};
#define MESHTASTIC__USER_LITE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__user_lite__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, MESHTASTIC__HARDWARE_MODEL__UNSET, 0, MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT, {0,NULL} }


typedef enum {
  MESHTASTIC__NODE_INFO_LITE___HOPS_AWAY__NOT_SET = 0,
  MESHTASTIC__NODE_INFO_LITE___HOPS_AWAY_HOPS_AWAY = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__NODE_INFO_LITE___HOPS_AWAY__CASE)
} Meshtastic__NodeInfoLite__HopsAwayCase;

struct  Meshtastic__NodeInfoLite
{
  ProtobufCMessage base;
  /*
   * The node number
   */
  uint32_t num;
  /*
   * The user info for this node
   */
  Meshtastic__UserLite *user;
  /*
   * This position data. Note: before 1.2.14 we would also store the last time we've heard from this node in position.time, that is no longer true.
   * Position.time now indicates the last time we received a POSITION from that node.
   */
  Meshtastic__PositionLite *position;
  /*
   * Returns the Signal-to-noise ratio (SNR) of the last received message,
   * as measured by the receiver. Return SNR of the last received message in dB
   */
  float snr;
  /*
   * Set to indicate the last time we received a packet from this node
   */
  uint32_t last_heard;
  /*
   * The latest device metrics for the node.
   */
  Meshtastic__DeviceMetrics *device_metrics;
  /*
   * local channel index we heard that node on. Only populated if its not the default channel.
   */
  uint32_t channel;
  /*
   * True if we witnessed the node over MQTT instead of LoRA transport
   */
  protobuf_c_boolean via_mqtt;
  /*
   * True if node is in our favorites list
   * Persists between NodeDB internal clean ups
   */
  protobuf_c_boolean is_favorite;
  Meshtastic__NodeInfoLite__HopsAwayCase _hops_away_case;
  union {
    /*
     * Number of hops away from us this node is (0 if adjacent)
     */
    uint32_t hops_away;
  };
};
#define MESHTASTIC__NODE_INFO_LITE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__node_info_lite__descriptor) \
    , 0, NULL, NULL, 0, 0, NULL, 0, 0, 0, MESHTASTIC__NODE_INFO_LITE___HOPS_AWAY__NOT_SET, {0} }


/*
 * This message is never sent over the wire, but it is used for serializing DB
 * state to flash in the device code
 * FIXME, since we write this each time we enter deep sleep (and have infinite
 * flash) it would be better to use some sort of append only data structure for
 * the receive queue and use the preferences store for the other stuff
 */
struct  Meshtastic__DeviceState
{
  ProtobufCMessage base;
  /*
   * Read only settings/info about this node
   */
  Meshtastic__MyNodeInfo *my_node;
  /*
   * My owner info
   */
  Meshtastic__User *owner;
  /*
   * Received packets saved for delivery to the phone
   */
  size_t n_receive_queue;
  Meshtastic__MeshPacket **receive_queue;
  /*
   * A version integer used to invalidate old save files when we make
   * incompatible changes This integer is set at build time and is private to
   * NodeDB.cpp in the device code.
   */
  uint32_t version;
  /*
   * We keep the last received text message (only) stored in the device flash,
   * so we can show it on the screen.
   * Might be null
   */
  Meshtastic__MeshPacket *rx_text_message;
  /*
   * Used only during development.
   * Indicates developer is testing and changes should never be saved to flash.
   * Deprecated in 2.3.1
   */
  protobuf_c_boolean no_save PROTOBUF_C__DEPRECATED;
  /*
   * Some GPS receivers seem to have bogus settings from the factory, so we always do one factory reset.
   */
  protobuf_c_boolean did_gps_reset;
  /*
   * We keep the last received waypoint stored in the device flash,
   * so we can show it on the screen.
   * Might be null
   */
  Meshtastic__MeshPacket *rx_waypoint;
  /*
   * The mesh's nodes with their available gpio pins for RemoteHardware module
   */
  size_t n_node_remote_hardware_pins;
  Meshtastic__NodeRemoteHardwarePin **node_remote_hardware_pins;
  /*
   * New lite version of NodeDB to decrease memory footprint
   */
  size_t n_node_db_lite;
  Meshtastic__NodeInfoLite **node_db_lite;
};
#define MESHTASTIC__DEVICE_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__device_state__descriptor) \
    , NULL, NULL, 0,NULL, 0, NULL, 0, 0, NULL, 0,NULL, 0,NULL }


/*
 * The on-disk saved channels
 */
struct  Meshtastic__ChannelFile
{
  ProtobufCMessage base;
  /*
   * The channels our node knows about
   */
  size_t n_channels;
  Meshtastic__Channel **channels;
  /*
   * A version integer used to invalidate old save files when we make
   * incompatible changes This integer is set at build time and is private to
   * NodeDB.cpp in the device code.
   */
  uint32_t version;
};
#define MESHTASTIC__CHANNEL_FILE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__channel_file__descriptor) \
    , 0,NULL, 0 }


/*
 * This can be used for customizing the firmware distribution. If populated,
 * show a secondary bootup screen with custom logo and text for 2.5 seconds.
 */
struct  Meshtastic__OEMStore
{
  ProtobufCMessage base;
  /*
   * The Logo width in Px
   */
  uint32_t oem_icon_width;
  /*
   * The Logo height in Px
   */
  uint32_t oem_icon_height;
  /*
   * The Logo in XBM bytechar format
   */
  ProtobufCBinaryData oem_icon_bits;
  /*
   * Use this font for the OEM text.
   */
  Meshtastic__ScreenFonts oem_font;
  /*
   * Use this font for the OEM text.
   */
  char *oem_text;
  /*
   * The default device encryption key, 16 or 32 byte
   */
  ProtobufCBinaryData oem_aes_key;
  /*
   * A Preset LocalConfig to apply during factory reset
   */
  Meshtastic__LocalConfig *oem_local_config;
  /*
   * A Preset LocalModuleConfig to apply during factory reset
   */
  Meshtastic__LocalModuleConfig *oem_local_module_config;
};
#define MESHTASTIC__OEMSTORE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__oemstore__descriptor) \
    , 0, 0, {0,NULL}, MESHTASTIC__SCREEN_FONTS__FONT_SMALL, (char *)protobuf_c_empty_string, {0,NULL}, NULL, NULL }


/* Meshtastic__PositionLite methods */
void   meshtastic__position_lite__init
                     (Meshtastic__PositionLite         *message);
size_t meshtastic__position_lite__get_packed_size
                     (const Meshtastic__PositionLite   *message);
size_t meshtastic__position_lite__pack
                     (const Meshtastic__PositionLite   *message,
                      uint8_t             *out);
size_t meshtastic__position_lite__pack_to_buffer
                     (const Meshtastic__PositionLite   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__PositionLite *
       meshtastic__position_lite__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__position_lite__free_unpacked
                     (Meshtastic__PositionLite *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__UserLite methods */
void   meshtastic__user_lite__init
                     (Meshtastic__UserLite         *message);
size_t meshtastic__user_lite__get_packed_size
                     (const Meshtastic__UserLite   *message);
size_t meshtastic__user_lite__pack
                     (const Meshtastic__UserLite   *message,
                      uint8_t             *out);
size_t meshtastic__user_lite__pack_to_buffer
                     (const Meshtastic__UserLite   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__UserLite *
       meshtastic__user_lite__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__user_lite__free_unpacked
                     (Meshtastic__UserLite *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__NodeInfoLite methods */
void   meshtastic__node_info_lite__init
                     (Meshtastic__NodeInfoLite         *message);
size_t meshtastic__node_info_lite__get_packed_size
                     (const Meshtastic__NodeInfoLite   *message);
size_t meshtastic__node_info_lite__pack
                     (const Meshtastic__NodeInfoLite   *message,
                      uint8_t             *out);
size_t meshtastic__node_info_lite__pack_to_buffer
                     (const Meshtastic__NodeInfoLite   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__NodeInfoLite *
       meshtastic__node_info_lite__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__node_info_lite__free_unpacked
                     (Meshtastic__NodeInfoLite *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__DeviceState methods */
void   meshtastic__device_state__init
                     (Meshtastic__DeviceState         *message);
size_t meshtastic__device_state__get_packed_size
                     (const Meshtastic__DeviceState   *message);
size_t meshtastic__device_state__pack
                     (const Meshtastic__DeviceState   *message,
                      uint8_t             *out);
size_t meshtastic__device_state__pack_to_buffer
                     (const Meshtastic__DeviceState   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__DeviceState *
       meshtastic__device_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__device_state__free_unpacked
                     (Meshtastic__DeviceState *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__ChannelFile methods */
void   meshtastic__channel_file__init
                     (Meshtastic__ChannelFile         *message);
size_t meshtastic__channel_file__get_packed_size
                     (const Meshtastic__ChannelFile   *message);
size_t meshtastic__channel_file__pack
                     (const Meshtastic__ChannelFile   *message,
                      uint8_t             *out);
size_t meshtastic__channel_file__pack_to_buffer
                     (const Meshtastic__ChannelFile   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__ChannelFile *
       meshtastic__channel_file__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__channel_file__free_unpacked
                     (Meshtastic__ChannelFile *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__OEMStore methods */
void   meshtastic__oemstore__init
                     (Meshtastic__OEMStore         *message);
size_t meshtastic__oemstore__get_packed_size
                     (const Meshtastic__OEMStore   *message);
size_t meshtastic__oemstore__pack
                     (const Meshtastic__OEMStore   *message,
                      uint8_t             *out);
size_t meshtastic__oemstore__pack_to_buffer
                     (const Meshtastic__OEMStore   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__OEMStore *
       meshtastic__oemstore__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__oemstore__free_unpacked
                     (Meshtastic__OEMStore *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Meshtastic__PositionLite_Closure)
                 (const Meshtastic__PositionLite *message,
                  void *closure_data);
typedef void (*Meshtastic__UserLite_Closure)
                 (const Meshtastic__UserLite *message,
                  void *closure_data);
typedef void (*Meshtastic__NodeInfoLite_Closure)
                 (const Meshtastic__NodeInfoLite *message,
                  void *closure_data);
typedef void (*Meshtastic__DeviceState_Closure)
                 (const Meshtastic__DeviceState *message,
                  void *closure_data);
typedef void (*Meshtastic__ChannelFile_Closure)
                 (const Meshtastic__ChannelFile *message,
                  void *closure_data);
typedef void (*Meshtastic__OEMStore_Closure)
                 (const Meshtastic__OEMStore *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    meshtastic__screen_fonts__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__position_lite__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__user_lite__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__node_info_lite__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__device_state__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__channel_file__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__oemstore__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshtastic_2fdeviceonly_2eproto__INCLUDED */
