/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/localonly.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/localonly.pb-c.h"
void   meshtastic__local_config__init
                     (Meshtastic__LocalConfig         *message)
{
  static const Meshtastic__LocalConfig init_value = MESHTASTIC__LOCAL_CONFIG__INIT;
  *message = init_value;
}
size_t meshtastic__local_config__get_packed_size
                     (const Meshtastic__LocalConfig *message)
{
  assert(message->base.descriptor == &meshtastic__local_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__local_config__pack
                     (const Meshtastic__LocalConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__local_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__local_config__pack_to_buffer
                     (const Meshtastic__LocalConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__local_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__LocalConfig *
       meshtastic__local_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__LocalConfig *)
     protobuf_c_message_unpack (&meshtastic__local_config__descriptor,
                                allocator, len, data);
}
void   meshtastic__local_config__free_unpacked
                     (Meshtastic__LocalConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__local_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__local_module_config__init
                     (Meshtastic__LocalModuleConfig         *message)
{
  static const Meshtastic__LocalModuleConfig init_value = MESHTASTIC__LOCAL_MODULE_CONFIG__INIT;
  *message = init_value;
}
size_t meshtastic__local_module_config__get_packed_size
                     (const Meshtastic__LocalModuleConfig *message)
{
  assert(message->base.descriptor == &meshtastic__local_module_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__local_module_config__pack
                     (const Meshtastic__LocalModuleConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__local_module_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__local_module_config__pack_to_buffer
                     (const Meshtastic__LocalModuleConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__local_module_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__LocalModuleConfig *
       meshtastic__local_module_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__LocalModuleConfig *)
     protobuf_c_message_unpack (&meshtastic__local_module_config__descriptor,
                                allocator, len, data);
}
void   meshtastic__local_module_config__free_unpacked
                     (Meshtastic__LocalModuleConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__local_module_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor meshtastic__local_config__field_descriptors[9] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, device),
    &meshtastic__config__device_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, position),
    &meshtastic__config__position_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, power),
    &meshtastic__config__power_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, network),
    &meshtastic__config__network_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, display),
    &meshtastic__config__display_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lora",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, lora),
    &meshtastic__config__lo_ra_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bluetooth",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, bluetooth),
    &meshtastic__config__bluetooth_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "security",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalConfig, security),
    &meshtastic__config__security_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__local_config__field_indices_by_name[] = {
  6,   /* field[6] = bluetooth */
  0,   /* field[0] = device */
  4,   /* field[4] = display */
  5,   /* field[5] = lora */
  3,   /* field[3] = network */
  1,   /* field[1] = position */
  2,   /* field[2] = power */
  8,   /* field[8] = security */
  7,   /* field[7] = version */
};
static const ProtobufCIntRange meshtastic__local_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor meshtastic__local_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.LocalConfig",
  "LocalConfig",
  "Meshtastic__LocalConfig",
  "meshtastic",
  sizeof(Meshtastic__LocalConfig),
  9,
  meshtastic__local_config__field_descriptors,
  meshtastic__local_config__field_indices_by_name,
  1,  meshtastic__local_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__local_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__local_module_config__field_descriptors[14] =
{
  {
    "mqtt",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, mqtt),
    &meshtastic__module_config__mqttconfig__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, serial),
    &meshtastic__module_config__serial_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external_notification",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, external_notification),
    &meshtastic__module_config__external_notification_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "store_forward",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, store_forward),
    &meshtastic__module_config__store_forward_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range_test",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, range_test),
    &meshtastic__module_config__range_test_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "telemetry",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, telemetry),
    &meshtastic__module_config__telemetry_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canned_message",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, canned_message),
    &meshtastic__module_config__canned_message_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, audio),
    &meshtastic__module_config__audio_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_hardware",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, remote_hardware),
    &meshtastic__module_config__remote_hardware_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "neighbor_info",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, neighbor_info),
    &meshtastic__module_config__neighbor_info_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ambient_lighting",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, ambient_lighting),
    &meshtastic__module_config__ambient_lighting_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detection_sensor",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, detection_sensor),
    &meshtastic__module_config__detection_sensor_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "paxcounter",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__LocalModuleConfig, paxcounter),
    &meshtastic__module_config__paxcounter_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__local_module_config__field_indices_by_name[] = {
  11,   /* field[11] = ambient_lighting */
  8,   /* field[8] = audio */
  6,   /* field[6] = canned_message */
  12,   /* field[12] = detection_sensor */
  2,   /* field[2] = external_notification */
  0,   /* field[0] = mqtt */
  10,   /* field[10] = neighbor_info */
  13,   /* field[13] = paxcounter */
  4,   /* field[4] = range_test */
  9,   /* field[9] = remote_hardware */
  1,   /* field[1] = serial */
  3,   /* field[3] = store_forward */
  5,   /* field[5] = telemetry */
  7,   /* field[7] = version */
};
static const ProtobufCIntRange meshtastic__local_module_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor meshtastic__local_module_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.LocalModuleConfig",
  "LocalModuleConfig",
  "Meshtastic__LocalModuleConfig",
  "meshtastic",
  sizeof(Meshtastic__LocalModuleConfig),
  14,
  meshtastic__local_module_config__field_descriptors,
  meshtastic__local_module_config__field_indices_by_name,
  1,  meshtastic__local_module_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__local_module_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
