/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/module_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/module_config.pb-c.h"
void   meshtastic__module_config__mqttconfig__init
                     (Meshtastic__ModuleConfig__MQTTConfig         *message)
{
  static const Meshtastic__ModuleConfig__MQTTConfig init_value = MESHTASTIC__MODULE_CONFIG__MQTTCONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__map_report_settings__init
                     (Meshtastic__ModuleConfig__MapReportSettings         *message)
{
  static const Meshtastic__ModuleConfig__MapReportSettings init_value = MESHTASTIC__MODULE_CONFIG__MAP_REPORT_SETTINGS__INIT;
  *message = init_value;
}
void   meshtastic__module_config__remote_hardware_config__init
                     (Meshtastic__ModuleConfig__RemoteHardwareConfig         *message)
{
  static const Meshtastic__ModuleConfig__RemoteHardwareConfig init_value = MESHTASTIC__MODULE_CONFIG__REMOTE_HARDWARE_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__neighbor_info_config__init
                     (Meshtastic__ModuleConfig__NeighborInfoConfig         *message)
{
  static const Meshtastic__ModuleConfig__NeighborInfoConfig init_value = MESHTASTIC__MODULE_CONFIG__NEIGHBOR_INFO_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__detection_sensor_config__init
                     (Meshtastic__ModuleConfig__DetectionSensorConfig         *message)
{
  static const Meshtastic__ModuleConfig__DetectionSensorConfig init_value = MESHTASTIC__MODULE_CONFIG__DETECTION_SENSOR_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__audio_config__init
                     (Meshtastic__ModuleConfig__AudioConfig         *message)
{
  static const Meshtastic__ModuleConfig__AudioConfig init_value = MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__paxcounter_config__init
                     (Meshtastic__ModuleConfig__PaxcounterConfig         *message)
{
  static const Meshtastic__ModuleConfig__PaxcounterConfig init_value = MESHTASTIC__MODULE_CONFIG__PAXCOUNTER_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__serial_config__init
                     (Meshtastic__ModuleConfig__SerialConfig         *message)
{
  static const Meshtastic__ModuleConfig__SerialConfig init_value = MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__external_notification_config__init
                     (Meshtastic__ModuleConfig__ExternalNotificationConfig         *message)
{
  static const Meshtastic__ModuleConfig__ExternalNotificationConfig init_value = MESHTASTIC__MODULE_CONFIG__EXTERNAL_NOTIFICATION_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__store_forward_config__init
                     (Meshtastic__ModuleConfig__StoreForwardConfig         *message)
{
  static const Meshtastic__ModuleConfig__StoreForwardConfig init_value = MESHTASTIC__MODULE_CONFIG__STORE_FORWARD_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__range_test_config__init
                     (Meshtastic__ModuleConfig__RangeTestConfig         *message)
{
  static const Meshtastic__ModuleConfig__RangeTestConfig init_value = MESHTASTIC__MODULE_CONFIG__RANGE_TEST_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__telemetry_config__init
                     (Meshtastic__ModuleConfig__TelemetryConfig         *message)
{
  static const Meshtastic__ModuleConfig__TelemetryConfig init_value = MESHTASTIC__MODULE_CONFIG__TELEMETRY_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__canned_message_config__init
                     (Meshtastic__ModuleConfig__CannedMessageConfig         *message)
{
  static const Meshtastic__ModuleConfig__CannedMessageConfig init_value = MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__ambient_lighting_config__init
                     (Meshtastic__ModuleConfig__AmbientLightingConfig         *message)
{
  static const Meshtastic__ModuleConfig__AmbientLightingConfig init_value = MESHTASTIC__MODULE_CONFIG__AMBIENT_LIGHTING_CONFIG__INIT;
  *message = init_value;
}
void   meshtastic__module_config__init
                     (Meshtastic__ModuleConfig         *message)
{
  static const Meshtastic__ModuleConfig init_value = MESHTASTIC__MODULE_CONFIG__INIT;
  *message = init_value;
}
size_t meshtastic__module_config__get_packed_size
                     (const Meshtastic__ModuleConfig *message)
{
  assert(message->base.descriptor == &meshtastic__module_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__module_config__pack
                     (const Meshtastic__ModuleConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__module_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__module_config__pack_to_buffer
                     (const Meshtastic__ModuleConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__module_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__ModuleConfig *
       meshtastic__module_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__ModuleConfig *)
     protobuf_c_message_unpack (&meshtastic__module_config__descriptor,
                                allocator, len, data);
}
void   meshtastic__module_config__free_unpacked
                     (Meshtastic__ModuleConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__module_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__remote_hardware_pin__init
                     (Meshtastic__RemoteHardwarePin         *message)
{
  static const Meshtastic__RemoteHardwarePin init_value = MESHTASTIC__REMOTE_HARDWARE_PIN__INIT;
  *message = init_value;
}
size_t meshtastic__remote_hardware_pin__get_packed_size
                     (const Meshtastic__RemoteHardwarePin *message)
{
  assert(message->base.descriptor == &meshtastic__remote_hardware_pin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__remote_hardware_pin__pack
                     (const Meshtastic__RemoteHardwarePin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__remote_hardware_pin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__remote_hardware_pin__pack_to_buffer
                     (const Meshtastic__RemoteHardwarePin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__remote_hardware_pin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__RemoteHardwarePin *
       meshtastic__remote_hardware_pin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__RemoteHardwarePin *)
     protobuf_c_message_unpack (&meshtastic__remote_hardware_pin__descriptor,
                                allocator, len, data);
}
void   meshtastic__remote_hardware_pin__free_unpacked
                     (Meshtastic__RemoteHardwarePin *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__remote_hardware_pin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor meshtastic__module_config__mqttconfig__field_descriptors[11] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encryption_enabled",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, encryption_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "json_enabled",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, json_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls_enabled",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, tls_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, root),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proxy_to_client_enabled",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, proxy_to_client_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_reporting_enabled",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, map_reporting_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_report_settings",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MQTTConfig, map_report_settings),
    &meshtastic__module_config__map_report_settings__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__mqttconfig__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = enabled */
  4,   /* field[4] = encryption_enabled */
  5,   /* field[5] = json_enabled */
  10,   /* field[10] = map_report_settings */
  9,   /* field[9] = map_reporting_enabled */
  3,   /* field[3] = password */
  8,   /* field[8] = proxy_to_client_enabled */
  7,   /* field[7] = root */
  6,   /* field[6] = tls_enabled */
  2,   /* field[2] = username */
};
static const ProtobufCIntRange meshtastic__module_config__mqttconfig__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__mqttconfig__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.MQTTConfig",
  "MQTTConfig",
  "Meshtastic__ModuleConfig__MQTTConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__MQTTConfig),
  11,
  meshtastic__module_config__mqttconfig__field_descriptors,
  meshtastic__module_config__mqttconfig__field_indices_by_name,
  1,  meshtastic__module_config__mqttconfig__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__mqttconfig__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__map_report_settings__field_descriptors[2] =
{
  {
    "publish_interval_secs",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MapReportSettings, publish_interval_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_precision",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__MapReportSettings, position_precision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__map_report_settings__field_indices_by_name[] = {
  1,   /* field[1] = position_precision */
  0,   /* field[0] = publish_interval_secs */
};
static const ProtobufCIntRange meshtastic__module_config__map_report_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__map_report_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.MapReportSettings",
  "MapReportSettings",
  "Meshtastic__ModuleConfig__MapReportSettings",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__MapReportSettings),
  2,
  meshtastic__module_config__map_report_settings__field_descriptors,
  meshtastic__module_config__map_report_settings__field_indices_by_name,
  1,  meshtastic__module_config__map_report_settings__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__map_report_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__remote_hardware_config__field_descriptors[3] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__RemoteHardwareConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_undefined_pin_access",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__RemoteHardwareConfig, allow_undefined_pin_access),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "available_pins",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig__RemoteHardwareConfig, n_available_pins),
    offsetof(Meshtastic__ModuleConfig__RemoteHardwareConfig, available_pins),
    &meshtastic__remote_hardware_pin__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__remote_hardware_config__field_indices_by_name[] = {
  1,   /* field[1] = allow_undefined_pin_access */
  2,   /* field[2] = available_pins */
  0,   /* field[0] = enabled */
};
static const ProtobufCIntRange meshtastic__module_config__remote_hardware_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__remote_hardware_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.RemoteHardwareConfig",
  "RemoteHardwareConfig",
  "Meshtastic__ModuleConfig__RemoteHardwareConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__RemoteHardwareConfig),
  3,
  meshtastic__module_config__remote_hardware_config__field_descriptors,
  meshtastic__module_config__remote_hardware_config__field_indices_by_name,
  1,  meshtastic__module_config__remote_hardware_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__remote_hardware_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__neighbor_info_config__field_descriptors[2] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__NeighborInfoConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_interval",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__NeighborInfoConfig, update_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__neighbor_info_config__field_indices_by_name[] = {
  0,   /* field[0] = enabled */
  1,   /* field[1] = update_interval */
};
static const ProtobufCIntRange meshtastic__module_config__neighbor_info_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__neighbor_info_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.NeighborInfoConfig",
  "NeighborInfoConfig",
  "Meshtastic__ModuleConfig__NeighborInfoConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__NeighborInfoConfig),
  2,
  meshtastic__module_config__neighbor_info_config__field_descriptors,
  meshtastic__module_config__neighbor_info_config__field_indices_by_name,
  1,  meshtastic__module_config__neighbor_info_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__neighbor_info_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__module_config__detection_sensor_config__trigger_type__enum_values_by_number[6] =
{
  { "LOGIC_LOW", "MESHTASTIC__MODULE_CONFIG__DETECTION_SENSOR_CONFIG__TRIGGER_TYPE__LOGIC_LOW", 0 },
  { "LOGIC_HIGH", "MESHTASTIC__MODULE_CONFIG__DETECTION_SENSOR_CONFIG__TRIGGER_TYPE__LOGIC_HIGH", 1 },
  { "FALLING_EDGE", "MESHTASTIC__MODULE_CONFIG__DETECTION_SENSOR_CONFIG__TRIGGER_TYPE__FALLING_EDGE", 2 },
  { "RISING_EDGE", "MESHTASTIC__MODULE_CONFIG__DETECTION_SENSOR_CONFIG__TRIGGER_TYPE__RISING_EDGE", 3 },
  { "EITHER_EDGE_ACTIVE_LOW", "MESHTASTIC__MODULE_CONFIG__DETECTION_SENSOR_CONFIG__TRIGGER_TYPE__EITHER_EDGE_ACTIVE_LOW", 4 },
  { "EITHER_EDGE_ACTIVE_HIGH", "MESHTASTIC__MODULE_CONFIG__DETECTION_SENSOR_CONFIG__TRIGGER_TYPE__EITHER_EDGE_ACTIVE_HIGH", 5 },
};
static const ProtobufCIntRange meshtastic__module_config__detection_sensor_config__trigger_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex meshtastic__module_config__detection_sensor_config__trigger_type__enum_values_by_name[6] =
{
  { "EITHER_EDGE_ACTIVE_HIGH", 5 },
  { "EITHER_EDGE_ACTIVE_LOW", 4 },
  { "FALLING_EDGE", 2 },
  { "LOGIC_HIGH", 1 },
  { "LOGIC_LOW", 0 },
  { "RISING_EDGE", 3 },
};
const ProtobufCEnumDescriptor meshtastic__module_config__detection_sensor_config__trigger_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.DetectionSensorConfig.TriggerType",
  "TriggerType",
  "Meshtastic__ModuleConfig__DetectionSensorConfig__TriggerType",
  "meshtastic",
  6,
  meshtastic__module_config__detection_sensor_config__trigger_type__enum_values_by_number,
  6,
  meshtastic__module_config__detection_sensor_config__trigger_type__enum_values_by_name,
  1,
  meshtastic__module_config__detection_sensor_config__trigger_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__detection_sensor_config__field_descriptors[8] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minimum_broadcast_secs",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, minimum_broadcast_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state_broadcast_secs",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, state_broadcast_secs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_bell",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, send_bell),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monitor_pin",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, monitor_pin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detection_trigger_type",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, detection_trigger_type),
    &meshtastic__module_config__detection_sensor_config__trigger_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_pullup",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__DetectionSensorConfig, use_pullup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__detection_sensor_config__field_indices_by_name[] = {
  6,   /* field[6] = detection_trigger_type */
  0,   /* field[0] = enabled */
  1,   /* field[1] = minimum_broadcast_secs */
  5,   /* field[5] = monitor_pin */
  4,   /* field[4] = name */
  3,   /* field[3] = send_bell */
  2,   /* field[2] = state_broadcast_secs */
  7,   /* field[7] = use_pullup */
};
static const ProtobufCIntRange meshtastic__module_config__detection_sensor_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__detection_sensor_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.DetectionSensorConfig",
  "DetectionSensorConfig",
  "Meshtastic__ModuleConfig__DetectionSensorConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__DetectionSensorConfig),
  8,
  meshtastic__module_config__detection_sensor_config__field_descriptors,
  meshtastic__module_config__detection_sensor_config__field_indices_by_name,
  1,  meshtastic__module_config__detection_sensor_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__detection_sensor_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__module_config__audio_config__audio__baud__enum_values_by_number[9] =
{
  { "CODEC2_DEFAULT", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_DEFAULT", 0 },
  { "CODEC2_3200", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_3200", 1 },
  { "CODEC2_2400", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_2400", 2 },
  { "CODEC2_1600", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_1600", 3 },
  { "CODEC2_1400", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_1400", 4 },
  { "CODEC2_1300", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_1300", 5 },
  { "CODEC2_1200", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_1200", 6 },
  { "CODEC2_700", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_700", 7 },
  { "CODEC2_700B", "MESHTASTIC__MODULE_CONFIG__AUDIO_CONFIG__AUDIO__BAUD__CODEC2_700B", 8 },
};
static const ProtobufCIntRange meshtastic__module_config__audio_config__audio__baud__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex meshtastic__module_config__audio_config__audio__baud__enum_values_by_name[9] =
{
  { "CODEC2_1200", 6 },
  { "CODEC2_1300", 5 },
  { "CODEC2_1400", 4 },
  { "CODEC2_1600", 3 },
  { "CODEC2_2400", 2 },
  { "CODEC2_3200", 1 },
  { "CODEC2_700", 7 },
  { "CODEC2_700B", 8 },
  { "CODEC2_DEFAULT", 0 },
};
const ProtobufCEnumDescriptor meshtastic__module_config__audio_config__audio__baud__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.AudioConfig.Audio_Baud",
  "Audio_Baud",
  "Meshtastic__ModuleConfig__AudioConfig__AudioBaud",
  "meshtastic",
  9,
  meshtastic__module_config__audio_config__audio__baud__enum_values_by_number,
  9,
  meshtastic__module_config__audio_config__audio__baud__enum_values_by_name,
  1,
  meshtastic__module_config__audio_config__audio__baud__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__audio_config__field_descriptors[7] =
{
  {
    "codec2_enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AudioConfig, codec2_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ptt_pin",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AudioConfig, ptt_pin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitrate",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AudioConfig, bitrate),
    &meshtastic__module_config__audio_config__audio__baud__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i2s_ws",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AudioConfig, i2s_ws),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i2s_sd",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AudioConfig, i2s_sd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i2s_din",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AudioConfig, i2s_din),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i2s_sck",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AudioConfig, i2s_sck),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__audio_config__field_indices_by_name[] = {
  2,   /* field[2] = bitrate */
  0,   /* field[0] = codec2_enabled */
  5,   /* field[5] = i2s_din */
  6,   /* field[6] = i2s_sck */
  4,   /* field[4] = i2s_sd */
  3,   /* field[3] = i2s_ws */
  1,   /* field[1] = ptt_pin */
};
static const ProtobufCIntRange meshtastic__module_config__audio_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__audio_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.AudioConfig",
  "AudioConfig",
  "Meshtastic__ModuleConfig__AudioConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__AudioConfig),
  7,
  meshtastic__module_config__audio_config__field_descriptors,
  meshtastic__module_config__audio_config__field_indices_by_name,
  1,  meshtastic__module_config__audio_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__audio_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__paxcounter_config__field_descriptors[4] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__PaxcounterConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "paxcounter_update_interval",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__PaxcounterConfig, paxcounter_update_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi_threshold",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__PaxcounterConfig, wifi_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ble_threshold",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__PaxcounterConfig, ble_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__paxcounter_config__field_indices_by_name[] = {
  3,   /* field[3] = ble_threshold */
  0,   /* field[0] = enabled */
  1,   /* field[1] = paxcounter_update_interval */
  2,   /* field[2] = wifi_threshold */
};
static const ProtobufCIntRange meshtastic__module_config__paxcounter_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__paxcounter_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.PaxcounterConfig",
  "PaxcounterConfig",
  "Meshtastic__ModuleConfig__PaxcounterConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__PaxcounterConfig),
  4,
  meshtastic__module_config__paxcounter_config__field_descriptors,
  meshtastic__module_config__paxcounter_config__field_indices_by_name,
  1,  meshtastic__module_config__paxcounter_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__paxcounter_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__module_config__serial_config__serial__baud__enum_values_by_number[16] =
{
  { "BAUD_DEFAULT", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_DEFAULT", 0 },
  { "BAUD_110", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_110", 1 },
  { "BAUD_300", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_300", 2 },
  { "BAUD_600", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_600", 3 },
  { "BAUD_1200", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_1200", 4 },
  { "BAUD_2400", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_2400", 5 },
  { "BAUD_4800", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_4800", 6 },
  { "BAUD_9600", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_9600", 7 },
  { "BAUD_19200", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_19200", 8 },
  { "BAUD_38400", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_38400", 9 },
  { "BAUD_57600", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_57600", 10 },
  { "BAUD_115200", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_115200", 11 },
  { "BAUD_230400", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_230400", 12 },
  { "BAUD_460800", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_460800", 13 },
  { "BAUD_576000", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_576000", 14 },
  { "BAUD_921600", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__BAUD__BAUD_921600", 15 },
};
static const ProtobufCIntRange meshtastic__module_config__serial_config__serial__baud__value_ranges[] = {
{0, 0},{0, 16}
};
static const ProtobufCEnumValueIndex meshtastic__module_config__serial_config__serial__baud__enum_values_by_name[16] =
{
  { "BAUD_110", 1 },
  { "BAUD_115200", 11 },
  { "BAUD_1200", 4 },
  { "BAUD_19200", 8 },
  { "BAUD_230400", 12 },
  { "BAUD_2400", 5 },
  { "BAUD_300", 2 },
  { "BAUD_38400", 9 },
  { "BAUD_460800", 13 },
  { "BAUD_4800", 6 },
  { "BAUD_57600", 10 },
  { "BAUD_576000", 14 },
  { "BAUD_600", 3 },
  { "BAUD_921600", 15 },
  { "BAUD_9600", 7 },
  { "BAUD_DEFAULT", 0 },
};
const ProtobufCEnumDescriptor meshtastic__module_config__serial_config__serial__baud__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.SerialConfig.Serial_Baud",
  "Serial_Baud",
  "Meshtastic__ModuleConfig__SerialConfig__SerialBaud",
  "meshtastic",
  16,
  meshtastic__module_config__serial_config__serial__baud__enum_values_by_number,
  16,
  meshtastic__module_config__serial_config__serial__baud__enum_values_by_name,
  1,
  meshtastic__module_config__serial_config__serial__baud__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue meshtastic__module_config__serial_config__serial__mode__enum_values_by_number[7] =
{
  { "DEFAULT", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__MODE__DEFAULT", 0 },
  { "SIMPLE", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__MODE__SIMPLE", 1 },
  { "PROTO", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__MODE__PROTO", 2 },
  { "TEXTMSG", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__MODE__TEXTMSG", 3 },
  { "NMEA", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__MODE__NMEA", 4 },
  { "CALTOPO", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__MODE__CALTOPO", 5 },
  { "WS85", "MESHTASTIC__MODULE_CONFIG__SERIAL_CONFIG__SERIAL__MODE__WS85", 6 },
};
static const ProtobufCIntRange meshtastic__module_config__serial_config__serial__mode__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex meshtastic__module_config__serial_config__serial__mode__enum_values_by_name[7] =
{
  { "CALTOPO", 5 },
  { "DEFAULT", 0 },
  { "NMEA", 4 },
  { "PROTO", 2 },
  { "SIMPLE", 1 },
  { "TEXTMSG", 3 },
  { "WS85", 6 },
};
const ProtobufCEnumDescriptor meshtastic__module_config__serial_config__serial__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.SerialConfig.Serial_Mode",
  "Serial_Mode",
  "Meshtastic__ModuleConfig__SerialConfig__SerialMode",
  "meshtastic",
  7,
  meshtastic__module_config__serial_config__serial__mode__enum_values_by_number,
  7,
  meshtastic__module_config__serial_config__serial__mode__enum_values_by_name,
  1,
  meshtastic__module_config__serial_config__serial__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__serial_config__field_descriptors[8] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "echo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, echo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rxd",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, rxd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txd",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, txd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, baud),
    &meshtastic__module_config__serial_config__serial__baud__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, mode),
    &meshtastic__module_config__serial_config__serial__mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "override_console_serial_port",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__SerialConfig, override_console_serial_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__serial_config__field_indices_by_name[] = {
  4,   /* field[4] = baud */
  1,   /* field[1] = echo */
  0,   /* field[0] = enabled */
  6,   /* field[6] = mode */
  7,   /* field[7] = override_console_serial_port */
  2,   /* field[2] = rxd */
  5,   /* field[5] = timeout */
  3,   /* field[3] = txd */
};
static const ProtobufCIntRange meshtastic__module_config__serial_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__serial_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.SerialConfig",
  "SerialConfig",
  "Meshtastic__ModuleConfig__SerialConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__SerialConfig),
  8,
  meshtastic__module_config__serial_config__field_descriptors,
  meshtastic__module_config__serial_config__field_indices_by_name,
  1,  meshtastic__module_config__serial_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__serial_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__external_notification_config__field_descriptors[15] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_ms",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, output_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, output),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "active",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, alert_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_bell",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, alert_bell),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_pwm",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, use_pwm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_vibra",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, output_vibra),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_buzzer",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, output_buzzer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_message_vibra",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, alert_message_vibra),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_message_buzzer",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, alert_message_buzzer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_bell_vibra",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, alert_bell_vibra),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alert_bell_buzzer",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, alert_bell_buzzer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nag_timeout",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, nag_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_i2s_as_buzzer",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__ExternalNotificationConfig, use_i2s_as_buzzer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__external_notification_config__field_indices_by_name[] = {
  3,   /* field[3] = active */
  5,   /* field[5] = alert_bell */
  12,   /* field[12] = alert_bell_buzzer */
  11,   /* field[11] = alert_bell_vibra */
  4,   /* field[4] = alert_message */
  10,   /* field[10] = alert_message_buzzer */
  9,   /* field[9] = alert_message_vibra */
  0,   /* field[0] = enabled */
  13,   /* field[13] = nag_timeout */
  2,   /* field[2] = output */
  8,   /* field[8] = output_buzzer */
  1,   /* field[1] = output_ms */
  7,   /* field[7] = output_vibra */
  14,   /* field[14] = use_i2s_as_buzzer */
  6,   /* field[6] = use_pwm */
};
static const ProtobufCIntRange meshtastic__module_config__external_notification_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__external_notification_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.ExternalNotificationConfig",
  "ExternalNotificationConfig",
  "Meshtastic__ModuleConfig__ExternalNotificationConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__ExternalNotificationConfig),
  15,
  meshtastic__module_config__external_notification_config__field_descriptors,
  meshtastic__module_config__external_notification_config__field_indices_by_name,
  1,  meshtastic__module_config__external_notification_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__external_notification_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__store_forward_config__field_descriptors[6] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__StoreForwardConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__StoreForwardConfig, heartbeat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "records",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__StoreForwardConfig, records),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "history_return_max",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__StoreForwardConfig, history_return_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "history_return_window",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__StoreForwardConfig, history_return_window),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_server",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__StoreForwardConfig, is_server),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__store_forward_config__field_indices_by_name[] = {
  0,   /* field[0] = enabled */
  1,   /* field[1] = heartbeat */
  3,   /* field[3] = history_return_max */
  4,   /* field[4] = history_return_window */
  5,   /* field[5] = is_server */
  2,   /* field[2] = records */
};
static const ProtobufCIntRange meshtastic__module_config__store_forward_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__store_forward_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.StoreForwardConfig",
  "StoreForwardConfig",
  "Meshtastic__ModuleConfig__StoreForwardConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__StoreForwardConfig),
  6,
  meshtastic__module_config__store_forward_config__field_descriptors,
  meshtastic__module_config__store_forward_config__field_indices_by_name,
  1,  meshtastic__module_config__store_forward_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__store_forward_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__range_test_config__field_descriptors[3] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__RangeTestConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__RangeTestConfig, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__RangeTestConfig, save),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__range_test_config__field_indices_by_name[] = {
  0,   /* field[0] = enabled */
  2,   /* field[2] = save */
  1,   /* field[1] = sender */
};
static const ProtobufCIntRange meshtastic__module_config__range_test_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__range_test_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.RangeTestConfig",
  "RangeTestConfig",
  "Meshtastic__ModuleConfig__RangeTestConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__RangeTestConfig),
  3,
  meshtastic__module_config__range_test_config__field_descriptors,
  meshtastic__module_config__range_test_config__field_indices_by_name,
  1,  meshtastic__module_config__range_test_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__range_test_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__telemetry_config__field_descriptors[13] =
{
  {
    "device_update_interval",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, device_update_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "environment_update_interval",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, environment_update_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "environment_measurement_enabled",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, environment_measurement_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "environment_screen_enabled",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, environment_screen_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "environment_display_fahrenheit",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, environment_display_fahrenheit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "air_quality_enabled",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, air_quality_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "air_quality_interval",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, air_quality_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_measurement_enabled",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, power_measurement_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_update_interval",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, power_update_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_screen_enabled",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, power_screen_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health_measurement_enabled",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, health_measurement_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health_update_interval",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, health_update_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "health_screen_enabled",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__TelemetryConfig, health_screen_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__telemetry_config__field_indices_by_name[] = {
  5,   /* field[5] = air_quality_enabled */
  6,   /* field[6] = air_quality_interval */
  0,   /* field[0] = device_update_interval */
  4,   /* field[4] = environment_display_fahrenheit */
  2,   /* field[2] = environment_measurement_enabled */
  3,   /* field[3] = environment_screen_enabled */
  1,   /* field[1] = environment_update_interval */
  10,   /* field[10] = health_measurement_enabled */
  12,   /* field[12] = health_screen_enabled */
  11,   /* field[11] = health_update_interval */
  7,   /* field[7] = power_measurement_enabled */
  9,   /* field[9] = power_screen_enabled */
  8,   /* field[8] = power_update_interval */
};
static const ProtobufCIntRange meshtastic__module_config__telemetry_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__telemetry_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.TelemetryConfig",
  "TelemetryConfig",
  "Meshtastic__ModuleConfig__TelemetryConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__TelemetryConfig),
  13,
  meshtastic__module_config__telemetry_config__field_descriptors,
  meshtastic__module_config__telemetry_config__field_indices_by_name,
  1,  meshtastic__module_config__telemetry_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__telemetry_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__module_config__canned_message_config__input_event_char__enum_values_by_number[8] =
{
  { "NONE", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__NONE", 0 },
  { "SELECT", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__SELECT", 10 },
  { "UP", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__UP", 17 },
  { "DOWN", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__DOWN", 18 },
  { "LEFT", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__LEFT", 19 },
  { "RIGHT", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__RIGHT", 20 },
  { "CANCEL", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__CANCEL", 24 },
  { "BACK", "MESHTASTIC__MODULE_CONFIG__CANNED_MESSAGE_CONFIG__INPUT_EVENT_CHAR__BACK", 27 },
};
static const ProtobufCIntRange meshtastic__module_config__canned_message_config__input_event_char__value_ranges[] = {
{0, 0},{10, 1},{17, 2},{24, 6},{27, 7},{0, 8}
};
static const ProtobufCEnumValueIndex meshtastic__module_config__canned_message_config__input_event_char__enum_values_by_name[8] =
{
  { "BACK", 7 },
  { "CANCEL", 6 },
  { "DOWN", 3 },
  { "LEFT", 4 },
  { "NONE", 0 },
  { "RIGHT", 5 },
  { "SELECT", 1 },
  { "UP", 2 },
};
const ProtobufCEnumDescriptor meshtastic__module_config__canned_message_config__input_event_char__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.CannedMessageConfig.InputEventChar",
  "InputEventChar",
  "Meshtastic__ModuleConfig__CannedMessageConfig__InputEventChar",
  "meshtastic",
  8,
  meshtastic__module_config__canned_message_config__input_event_char__enum_values_by_number,
  8,
  meshtastic__module_config__canned_message_config__input_event_char__enum_values_by_name,
  5,
  meshtastic__module_config__canned_message_config__input_event_char__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__canned_message_config__field_descriptors[11] =
{
  {
    "rotary1_enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, rotary1_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputbroker_pin_a",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, inputbroker_pin_a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputbroker_pin_b",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, inputbroker_pin_b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputbroker_pin_press",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, inputbroker_pin_press),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputbroker_event_cw",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, inputbroker_event_cw),
    &meshtastic__module_config__canned_message_config__input_event_char__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputbroker_event_ccw",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, inputbroker_event_ccw),
    &meshtastic__module_config__canned_message_config__input_event_char__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputbroker_event_press",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, inputbroker_event_press),
    &meshtastic__module_config__canned_message_config__input_event_char__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "updown1_enabled",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, updown1_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enabled",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_input_source",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, allow_input_source),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_bell",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__CannedMessageConfig, send_bell),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__canned_message_config__field_indices_by_name[] = {
  9,   /* field[9] = allow_input_source */
  8,   /* field[8] = enabled */
  5,   /* field[5] = inputbroker_event_ccw */
  4,   /* field[4] = inputbroker_event_cw */
  6,   /* field[6] = inputbroker_event_press */
  1,   /* field[1] = inputbroker_pin_a */
  2,   /* field[2] = inputbroker_pin_b */
  3,   /* field[3] = inputbroker_pin_press */
  0,   /* field[0] = rotary1_enabled */
  10,   /* field[10] = send_bell */
  7,   /* field[7] = updown1_enabled */
};
static const ProtobufCIntRange meshtastic__module_config__canned_message_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__canned_message_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.CannedMessageConfig",
  "CannedMessageConfig",
  "Meshtastic__ModuleConfig__CannedMessageConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__CannedMessageConfig),
  11,
  meshtastic__module_config__canned_message_config__field_descriptors,
  meshtastic__module_config__canned_message_config__field_indices_by_name,
  1,  meshtastic__module_config__canned_message_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__canned_message_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__ambient_lighting_config__field_descriptors[5] =
{
  {
    "led_state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AmbientLightingConfig, led_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AmbientLightingConfig, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "red",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AmbientLightingConfig, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AmbientLightingConfig, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__ModuleConfig__AmbientLightingConfig, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__ambient_lighting_config__field_indices_by_name[] = {
  4,   /* field[4] = blue */
  1,   /* field[1] = current */
  3,   /* field[3] = green */
  0,   /* field[0] = led_state */
  2,   /* field[2] = red */
};
static const ProtobufCIntRange meshtastic__module_config__ambient_lighting_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__ambient_lighting_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig.AmbientLightingConfig",
  "AmbientLightingConfig",
  "Meshtastic__ModuleConfig__AmbientLightingConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig__AmbientLightingConfig),
  5,
  meshtastic__module_config__ambient_lighting_config__field_descriptors,
  meshtastic__module_config__ambient_lighting_config__field_indices_by_name,
  1,  meshtastic__module_config__ambient_lighting_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__ambient_lighting_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__module_config__field_descriptors[13] =
{
  {
    "mqtt",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, mqtt),
    &meshtastic__module_config__mqttconfig__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, serial),
    &meshtastic__module_config__serial_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external_notification",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, external_notification),
    &meshtastic__module_config__external_notification_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "store_forward",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, store_forward),
    &meshtastic__module_config__store_forward_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range_test",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, range_test),
    &meshtastic__module_config__range_test_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "telemetry",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, telemetry),
    &meshtastic__module_config__telemetry_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canned_message",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, canned_message),
    &meshtastic__module_config__canned_message_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, audio),
    &meshtastic__module_config__audio_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_hardware",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, remote_hardware),
    &meshtastic__module_config__remote_hardware_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "neighbor_info",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, neighbor_info),
    &meshtastic__module_config__neighbor_info_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ambient_lighting",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, ambient_lighting),
    &meshtastic__module_config__ambient_lighting_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detection_sensor",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, detection_sensor),
    &meshtastic__module_config__detection_sensor_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "paxcounter",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Meshtastic__ModuleConfig, payload_variant_case),
    offsetof(Meshtastic__ModuleConfig, paxcounter),
    &meshtastic__module_config__paxcounter_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__module_config__field_indices_by_name[] = {
  10,   /* field[10] = ambient_lighting */
  7,   /* field[7] = audio */
  6,   /* field[6] = canned_message */
  11,   /* field[11] = detection_sensor */
  2,   /* field[2] = external_notification */
  0,   /* field[0] = mqtt */
  9,   /* field[9] = neighbor_info */
  12,   /* field[12] = paxcounter */
  4,   /* field[4] = range_test */
  8,   /* field[8] = remote_hardware */
  1,   /* field[1] = serial */
  3,   /* field[3] = store_forward */
  5,   /* field[5] = telemetry */
};
static const ProtobufCIntRange meshtastic__module_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor meshtastic__module_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.ModuleConfig",
  "ModuleConfig",
  "Meshtastic__ModuleConfig",
  "meshtastic",
  sizeof(Meshtastic__ModuleConfig),
  13,
  meshtastic__module_config__field_descriptors,
  meshtastic__module_config__field_indices_by_name,
  1,  meshtastic__module_config__number_ranges,
  (ProtobufCMessageInit) meshtastic__module_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor meshtastic__remote_hardware_pin__field_descriptors[3] =
{
  {
    "gpio_pin",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__RemoteHardwarePin, gpio_pin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__RemoteHardwarePin, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__RemoteHardwarePin, type),
    &meshtastic__remote_hardware_pin_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__remote_hardware_pin__field_indices_by_name[] = {
  0,   /* field[0] = gpio_pin */
  1,   /* field[1] = name */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange meshtastic__remote_hardware_pin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor meshtastic__remote_hardware_pin__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.RemoteHardwarePin",
  "RemoteHardwarePin",
  "Meshtastic__RemoteHardwarePin",
  "meshtastic",
  sizeof(Meshtastic__RemoteHardwarePin),
  3,
  meshtastic__remote_hardware_pin__field_descriptors,
  meshtastic__remote_hardware_pin__field_indices_by_name,
  1,  meshtastic__remote_hardware_pin__number_ranges,
  (ProtobufCMessageInit) meshtastic__remote_hardware_pin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__remote_hardware_pin_type__enum_values_by_number[3] =
{
  { "UNKNOWN", "MESHTASTIC__REMOTE_HARDWARE_PIN_TYPE__UNKNOWN", 0 },
  { "DIGITAL_READ", "MESHTASTIC__REMOTE_HARDWARE_PIN_TYPE__DIGITAL_READ", 1 },
  { "DIGITAL_WRITE", "MESHTASTIC__REMOTE_HARDWARE_PIN_TYPE__DIGITAL_WRITE", 2 },
};
static const ProtobufCIntRange meshtastic__remote_hardware_pin_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex meshtastic__remote_hardware_pin_type__enum_values_by_name[3] =
{
  { "DIGITAL_READ", 1 },
  { "DIGITAL_WRITE", 2 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor meshtastic__remote_hardware_pin_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.RemoteHardwarePinType",
  "RemoteHardwarePinType",
  "Meshtastic__RemoteHardwarePinType",
  "meshtastic",
  3,
  meshtastic__remote_hardware_pin_type__enum_values_by_number,
  3,
  meshtastic__remote_hardware_pin_type__enum_values_by_name,
  1,
  meshtastic__remote_hardware_pin_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
