/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/mqtt.proto */

#ifndef PROTOBUF_C_meshtastic_2fmqtt_2eproto__INCLUDED
#define PROTOBUF_C_meshtastic_2fmqtt_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "meshtastic/config.pb-c.h"
#include "meshtastic/mesh.pb-c.h"

typedef struct Meshtastic__ServiceEnvelope Meshtastic__ServiceEnvelope;
typedef struct Meshtastic__MapReport Meshtastic__MapReport;


/* --- enums --- */


/* --- messages --- */

/*
 * This message wraps a MeshPacket with extra metadata about the sender and how it arrived.
 */
struct  Meshtastic__ServiceEnvelope
{
  ProtobufCMessage base;
  /*
   * The (probably encrypted) packet
   */
  Meshtastic__MeshPacket *packet;
  /*
   * The global channel ID it was sent on
   */
  char *channel_id;
  /*
   * The sending gateway node ID. Can we use this to authenticate/prevent fake
   * nodeid impersonation for senders? - i.e. use gateway/mesh id (which is authenticated) + local node id as
   * the globally trusted nodenum
   */
  char *gateway_id;
};
#define MESHTASTIC__SERVICE_ENVELOPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__service_envelope__descriptor) \
    , NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Information about a node intended to be reported unencrypted to a map using MQTT.
 */
struct  Meshtastic__MapReport
{
  ProtobufCMessage base;
  /*
   * A full name for this user, i.e. "Kevin Hester"
   */
  char *long_name;
  /*
   * A VERY short name, ideally two characters.
   * Suitable for a tiny OLED screen
   */
  char *short_name;
  /*
   * Role of the node that applies specific settings for a particular use-case
   */
  Meshtastic__Config__DeviceConfig__Role role;
  /*
   * Hardware model of the node, i.e. T-Beam, Heltec V3, etc...
   */
  Meshtastic__HardwareModel hw_model;
  /*
   * Device firmware version string
   */
  char *firmware_version;
  /*
   * The region code for the radio (US, CN, EU433, etc...)
   */
  Meshtastic__Config__LoRaConfig__RegionCode region;
  /*
   * Modem preset used by the radio (LongFast, MediumSlow, etc...)
   */
  Meshtastic__Config__LoRaConfig__ModemPreset modem_preset;
  /*
   * Whether the node has a channel with default PSK and name (LongFast, MediumSlow, etc...)
   * and it uses the default frequency slot given the region and modem preset.
   */
  protobuf_c_boolean has_default_channel;
  /*
   * Latitude: multiply by 1e-7 to get degrees in floating point
   */
  int32_t latitude_i;
  /*
   * Longitude: multiply by 1e-7 to get degrees in floating point
   */
  int32_t longitude_i;
  /*
   * Altitude in meters above MSL
   */
  int32_t altitude;
  /*
   * Indicates the bits of precision for latitude and longitude set by the sending node
   */
  uint32_t position_precision;
  /*
   * Number of online nodes (heard in the last 2 hours) this node has in its list that were received locally (not via MQTT)
   */
  uint32_t num_online_local_nodes;
};
#define MESHTASTIC__MAP_REPORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__map_report__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, MESHTASTIC__CONFIG__DEVICE_CONFIG__ROLE__CLIENT, MESHTASTIC__HARDWARE_MODEL__UNSET, (char *)protobuf_c_empty_string, MESHTASTIC__CONFIG__LO_RA_CONFIG__REGION_CODE__UNSET, MESHTASTIC__CONFIG__LO_RA_CONFIG__MODEM_PRESET__LONG_FAST, 0, 0, 0, 0, 0, 0 }


/* Meshtastic__ServiceEnvelope methods */
void   meshtastic__service_envelope__init
                     (Meshtastic__ServiceEnvelope         *message);
size_t meshtastic__service_envelope__get_packed_size
                     (const Meshtastic__ServiceEnvelope   *message);
size_t meshtastic__service_envelope__pack
                     (const Meshtastic__ServiceEnvelope   *message,
                      uint8_t             *out);
size_t meshtastic__service_envelope__pack_to_buffer
                     (const Meshtastic__ServiceEnvelope   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__ServiceEnvelope *
       meshtastic__service_envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__service_envelope__free_unpacked
                     (Meshtastic__ServiceEnvelope *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__MapReport methods */
void   meshtastic__map_report__init
                     (Meshtastic__MapReport         *message);
size_t meshtastic__map_report__get_packed_size
                     (const Meshtastic__MapReport   *message);
size_t meshtastic__map_report__pack
                     (const Meshtastic__MapReport   *message,
                      uint8_t             *out);
size_t meshtastic__map_report__pack_to_buffer
                     (const Meshtastic__MapReport   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__MapReport *
       meshtastic__map_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__map_report__free_unpacked
                     (Meshtastic__MapReport *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Meshtastic__ServiceEnvelope_Closure)
                 (const Meshtastic__ServiceEnvelope *message,
                  void *closure_data);
typedef void (*Meshtastic__MapReport_Closure)
                 (const Meshtastic__MapReport *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor meshtastic__service_envelope__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__map_report__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshtastic_2fmqtt_2eproto__INCLUDED */
