/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/paxcount.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/paxcount.pb-c.h"
void   meshtastic__paxcount__init
                     (Meshtastic__Paxcount         *message)
{
  static const Meshtastic__Paxcount init_value = MESHTASTIC__PAXCOUNT__INIT;
  *message = init_value;
}
size_t meshtastic__paxcount__get_packed_size
                     (const Meshtastic__Paxcount *message)
{
  assert(message->base.descriptor == &meshtastic__paxcount__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__paxcount__pack
                     (const Meshtastic__Paxcount *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__paxcount__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__paxcount__pack_to_buffer
                     (const Meshtastic__Paxcount *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__paxcount__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__Paxcount *
       meshtastic__paxcount__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__Paxcount *)
     protobuf_c_message_unpack (&meshtastic__paxcount__descriptor,
                                allocator, len, data);
}
void   meshtastic__paxcount__free_unpacked
                     (Meshtastic__Paxcount *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__paxcount__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor meshtastic__paxcount__field_descriptors[3] =
{
  {
    "wifi",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Paxcount, wifi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ble",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Paxcount, ble),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__Paxcount, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__paxcount__field_indices_by_name[] = {
  1,   /* field[1] = ble */
  2,   /* field[2] = uptime */
  0,   /* field[0] = wifi */
};
static const ProtobufCIntRange meshtastic__paxcount__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor meshtastic__paxcount__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.Paxcount",
  "Paxcount",
  "Meshtastic__Paxcount",
  "meshtastic",
  sizeof(Meshtastic__Paxcount),
  3,
  meshtastic__paxcount__field_descriptors,
  meshtastic__paxcount__field_indices_by_name,
  1,  meshtastic__paxcount__number_ranges,
  (ProtobufCMessageInit) meshtastic__paxcount__init,
  NULL,NULL,NULL    /* reserved[123] */
};
