/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/powermon.proto */

#ifndef PROTOBUF_C_meshtastic_2fpowermon_2eproto__INCLUDED
#define PROTOBUF_C_meshtastic_2fpowermon_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Meshtastic__PowerMon Meshtastic__PowerMon;
typedef struct Meshtastic__PowerStressMessage Meshtastic__PowerStressMessage;


/* --- enums --- */

/*
 * Any significant power changing event in meshtastic should be tagged with a powermon state transition.
 *If you are making new meshtastic features feel free to add new entries at the end of this definition.
 */
typedef enum _Meshtastic__PowerMon__State {
  MESHTASTIC__POWER_MON__STATE__None = 0,
  MESHTASTIC__POWER_MON__STATE__CPU_DeepSleep = 1,
  MESHTASTIC__POWER_MON__STATE__CPU_LightSleep = 2,
  /*
   *The external Vext1 power is on.  Many boards have auxillary power rails that the CPU turns on only
   *occasionally.  In cases where that rail has multiple devices on it we usually want to have logging on
   *the state of that rail as an independent record.
   *For instance on the Heltec Tracker 1.1 board, this rail is the power source for the GPS and screen.
   *The log messages will be short and complete (see PowerMon.Event in the protobufs for details).
   *something like "S:PM:C,0x00001234,REASON" where the hex number is the bitmask of all current states.
   *(We use a bitmask for states so that if a log message gets lost it won't be fatal)
   */
  MESHTASTIC__POWER_MON__STATE__Vext1_On = 4,
  MESHTASTIC__POWER_MON__STATE__Lora_RXOn = 8,
  MESHTASTIC__POWER_MON__STATE__Lora_TXOn = 16,
  MESHTASTIC__POWER_MON__STATE__Lora_RXActive = 32,
  MESHTASTIC__POWER_MON__STATE__BT_On = 64,
  MESHTASTIC__POWER_MON__STATE__LED_On = 128,
  MESHTASTIC__POWER_MON__STATE__Screen_On = 256,
  MESHTASTIC__POWER_MON__STATE__Screen_Drawing = 512,
  MESHTASTIC__POWER_MON__STATE__Wifi_On = 1024,
  /*
   *GPS is actively trying to find our location
   *See GPSPowerState for more details
   */
  MESHTASTIC__POWER_MON__STATE__GPS_Active = 2048
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__POWER_MON__STATE)
} Meshtastic__PowerMon__State;
/*
 * What operation would we like the UUT to perform.
 *note: senders should probably set want_response in their request packets, so that they can know when the state
 *machine has started processing their request
 */
typedef enum _Meshtastic__PowerStressMessage__Opcode {
  /*
   * Unset/unused
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__UNSET = 0,
  /*
   * Print board version slog and send an ack that we are alive and ready to process commands
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__PRINT_INFO = 1,
  /*
   * Try to turn off all automatic processing of packets, screen, sleeping, etc (to make it easier to measure in isolation)
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__FORCE_QUIET = 2,
  /*
   * Stop powerstress processing - probably by just rebooting the board
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__END_QUIET = 3,
  /*
   * Turn the screen on
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__SCREEN_ON = 16,
  /*
   * Turn the screen off
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__SCREEN_OFF = 17,
  /*
   * Let the CPU run but we assume mostly idling for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__CPU_IDLE = 32,
  /*
   * Force deep sleep for FIXME seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__CPU_DEEPSLEEP = 33,
  /*
   * Spin the CPU as fast as possible for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__CPU_FULLON = 34,
  /*
   * Turn the LED on for num_seconds (and leave it on - for baseline power measurement purposes)
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LED_ON = 48,
  /*
   * Force the LED off for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LED_OFF = 49,
  /*
   * Completely turn off the LORA radio for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LORA_OFF = 64,
  /*
   * Send Lora packets for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LORA_TX = 65,
  /*
   * Receive Lora packets for num_seconds (node will be mostly just listening, unless an external agent is helping stress this by sending packets on the current channel)
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LORA_RX = 66,
  /*
   * Turn off the BT radio for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__BT_OFF = 80,
  /*
   * Turn on the BT radio for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__BT_ON = 81,
  /*
   * Turn off the WIFI radio for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__WIFI_OFF = 96,
  /*
   * Turn on the WIFI radio for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__WIFI_ON = 97,
  /*
   * Turn off the GPS radio for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__GPS_OFF = 112,
  /*
   * Turn on the GPS radio for num_seconds
   */
  MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__GPS_ON = 113
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE)
} Meshtastic__PowerStressMessage__Opcode;

/* --- messages --- */

/*
 * Note: There are no 'PowerMon' messages normally in use (PowerMons are sent only as structured logs - slogs).
 *But we wrap our State enum in this message to effectively nest a namespace (without our linter yelling at us)
 */
struct  Meshtastic__PowerMon
{
  ProtobufCMessage base;
};
#define MESHTASTIC__POWER_MON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__power_mon__descriptor) \
     }


/*
 * PowerStress testing support via the C++ PowerStress module
 */
struct  Meshtastic__PowerStressMessage
{
  ProtobufCMessage base;
  /*
   * What type of HardwareMessage is this?
   */
  Meshtastic__PowerStressMessage__Opcode cmd;
  float num_seconds;
};
#define MESHTASTIC__POWER_STRESS_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&meshtastic__power_stress_message__descriptor) \
    , MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__UNSET, 0 }


/* Meshtastic__PowerMon methods */
void   meshtastic__power_mon__init
                     (Meshtastic__PowerMon         *message);
size_t meshtastic__power_mon__get_packed_size
                     (const Meshtastic__PowerMon   *message);
size_t meshtastic__power_mon__pack
                     (const Meshtastic__PowerMon   *message,
                      uint8_t             *out);
size_t meshtastic__power_mon__pack_to_buffer
                     (const Meshtastic__PowerMon   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__PowerMon *
       meshtastic__power_mon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__power_mon__free_unpacked
                     (Meshtastic__PowerMon *message,
                      ProtobufCAllocator *allocator);
/* Meshtastic__PowerStressMessage methods */
void   meshtastic__power_stress_message__init
                     (Meshtastic__PowerStressMessage         *message);
size_t meshtastic__power_stress_message__get_packed_size
                     (const Meshtastic__PowerStressMessage   *message);
size_t meshtastic__power_stress_message__pack
                     (const Meshtastic__PowerStressMessage   *message,
                      uint8_t             *out);
size_t meshtastic__power_stress_message__pack_to_buffer
                     (const Meshtastic__PowerStressMessage   *message,
                      ProtobufCBuffer     *buffer);
Meshtastic__PowerStressMessage *
       meshtastic__power_stress_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   meshtastic__power_stress_message__free_unpacked
                     (Meshtastic__PowerStressMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Meshtastic__PowerMon_Closure)
                 (const Meshtastic__PowerMon *message,
                  void *closure_data);
typedef void (*Meshtastic__PowerStressMessage_Closure)
                 (const Meshtastic__PowerStressMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor meshtastic__power_mon__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__power_mon__state__descriptor;
extern const ProtobufCMessageDescriptor meshtastic__power_stress_message__descriptor;
extern const ProtobufCEnumDescriptor    meshtastic__power_stress_message__opcode__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meshtastic_2fpowermon_2eproto__INCLUDED */
