/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/powermon.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/powermon.pb-c.h"
void   meshtastic__power_mon__init
                     (Meshtastic__PowerMon         *message)
{
  static const Meshtastic__PowerMon init_value = MESHTASTIC__POWER_MON__INIT;
  *message = init_value;
}
size_t meshtastic__power_mon__get_packed_size
                     (const Meshtastic__PowerMon *message)
{
  assert(message->base.descriptor == &meshtastic__power_mon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__power_mon__pack
                     (const Meshtastic__PowerMon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__power_mon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__power_mon__pack_to_buffer
                     (const Meshtastic__PowerMon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__power_mon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__PowerMon *
       meshtastic__power_mon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__PowerMon *)
     protobuf_c_message_unpack (&meshtastic__power_mon__descriptor,
                                allocator, len, data);
}
void   meshtastic__power_mon__free_unpacked
                     (Meshtastic__PowerMon *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__power_mon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meshtastic__power_stress_message__init
                     (Meshtastic__PowerStressMessage         *message)
{
  static const Meshtastic__PowerStressMessage init_value = MESHTASTIC__POWER_STRESS_MESSAGE__INIT;
  *message = init_value;
}
size_t meshtastic__power_stress_message__get_packed_size
                     (const Meshtastic__PowerStressMessage *message)
{
  assert(message->base.descriptor == &meshtastic__power_stress_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__power_stress_message__pack
                     (const Meshtastic__PowerStressMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__power_stress_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__power_stress_message__pack_to_buffer
                     (const Meshtastic__PowerStressMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__power_stress_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__PowerStressMessage *
       meshtastic__power_stress_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__PowerStressMessage *)
     protobuf_c_message_unpack (&meshtastic__power_stress_message__descriptor,
                                allocator, len, data);
}
void   meshtastic__power_stress_message__free_unpacked
                     (Meshtastic__PowerStressMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__power_stress_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue meshtastic__power_mon__state__enum_values_by_number[13] =
{
  { "None", "MESHTASTIC__POWER_MON__STATE__None", 0 },
  { "CPU_DeepSleep", "MESHTASTIC__POWER_MON__STATE__CPU_DeepSleep", 1 },
  { "CPU_LightSleep", "MESHTASTIC__POWER_MON__STATE__CPU_LightSleep", 2 },
  { "Vext1_On", "MESHTASTIC__POWER_MON__STATE__Vext1_On", 4 },
  { "Lora_RXOn", "MESHTASTIC__POWER_MON__STATE__Lora_RXOn", 8 },
  { "Lora_TXOn", "MESHTASTIC__POWER_MON__STATE__Lora_TXOn", 16 },
  { "Lora_RXActive", "MESHTASTIC__POWER_MON__STATE__Lora_RXActive", 32 },
  { "BT_On", "MESHTASTIC__POWER_MON__STATE__BT_On", 64 },
  { "LED_On", "MESHTASTIC__POWER_MON__STATE__LED_On", 128 },
  { "Screen_On", "MESHTASTIC__POWER_MON__STATE__Screen_On", 256 },
  { "Screen_Drawing", "MESHTASTIC__POWER_MON__STATE__Screen_Drawing", 512 },
  { "Wifi_On", "MESHTASTIC__POWER_MON__STATE__Wifi_On", 1024 },
  { "GPS_Active", "MESHTASTIC__POWER_MON__STATE__GPS_Active", 2048 },
};
static const ProtobufCIntRange meshtastic__power_mon__state__value_ranges[] = {
{0, 0},{4, 3},{8, 4},{16, 5},{32, 6},{64, 7},{128, 8},{256, 9},{512, 10},{1024, 11},{2048, 12},{0, 13}
};
static const ProtobufCEnumValueIndex meshtastic__power_mon__state__enum_values_by_name[13] =
{
  { "BT_On", 7 },
  { "CPU_DeepSleep", 1 },
  { "CPU_LightSleep", 2 },
  { "GPS_Active", 12 },
  { "LED_On", 8 },
  { "Lora_RXActive", 6 },
  { "Lora_RXOn", 4 },
  { "Lora_TXOn", 5 },
  { "None", 0 },
  { "Screen_Drawing", 10 },
  { "Screen_On", 9 },
  { "Vext1_On", 3 },
  { "Wifi_On", 11 },
};
const ProtobufCEnumDescriptor meshtastic__power_mon__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.PowerMon.State",
  "State",
  "Meshtastic__PowerMon__State",
  "meshtastic",
  13,
  meshtastic__power_mon__state__enum_values_by_number,
  13,
  meshtastic__power_mon__state__enum_values_by_name,
  11,
  meshtastic__power_mon__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
#define meshtastic__power_mon__field_descriptors NULL
#define meshtastic__power_mon__field_indices_by_name NULL
#define meshtastic__power_mon__number_ranges NULL
const ProtobufCMessageDescriptor meshtastic__power_mon__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.PowerMon",
  "PowerMon",
  "Meshtastic__PowerMon",
  "meshtastic",
  sizeof(Meshtastic__PowerMon),
  0,
  meshtastic__power_mon__field_descriptors,
  meshtastic__power_mon__field_indices_by_name,
  0,  meshtastic__power_mon__number_ranges,
  (ProtobufCMessageInit) meshtastic__power_mon__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue meshtastic__power_stress_message__opcode__enum_values_by_number[20] =
{
  { "UNSET", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__UNSET", 0 },
  { "PRINT_INFO", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__PRINT_INFO", 1 },
  { "FORCE_QUIET", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__FORCE_QUIET", 2 },
  { "END_QUIET", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__END_QUIET", 3 },
  { "SCREEN_ON", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__SCREEN_ON", 16 },
  { "SCREEN_OFF", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__SCREEN_OFF", 17 },
  { "CPU_IDLE", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__CPU_IDLE", 32 },
  { "CPU_DEEPSLEEP", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__CPU_DEEPSLEEP", 33 },
  { "CPU_FULLON", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__CPU_FULLON", 34 },
  { "LED_ON", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LED_ON", 48 },
  { "LED_OFF", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LED_OFF", 49 },
  { "LORA_OFF", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LORA_OFF", 64 },
  { "LORA_TX", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LORA_TX", 65 },
  { "LORA_RX", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__LORA_RX", 66 },
  { "BT_OFF", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__BT_OFF", 80 },
  { "BT_ON", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__BT_ON", 81 },
  { "WIFI_OFF", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__WIFI_OFF", 96 },
  { "WIFI_ON", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__WIFI_ON", 97 },
  { "GPS_OFF", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__GPS_OFF", 112 },
  { "GPS_ON", "MESHTASTIC__POWER_STRESS_MESSAGE__OPCODE__GPS_ON", 113 },
};
static const ProtobufCIntRange meshtastic__power_stress_message__opcode__value_ranges[] = {
{0, 0},{16, 4},{32, 6},{48, 9},{64, 11},{80, 14},{96, 16},{112, 18},{0, 20}
};
static const ProtobufCEnumValueIndex meshtastic__power_stress_message__opcode__enum_values_by_name[20] =
{
  { "BT_OFF", 14 },
  { "BT_ON", 15 },
  { "CPU_DEEPSLEEP", 7 },
  { "CPU_FULLON", 8 },
  { "CPU_IDLE", 6 },
  { "END_QUIET", 3 },
  { "FORCE_QUIET", 2 },
  { "GPS_OFF", 18 },
  { "GPS_ON", 19 },
  { "LED_OFF", 10 },
  { "LED_ON", 9 },
  { "LORA_OFF", 11 },
  { "LORA_RX", 13 },
  { "LORA_TX", 12 },
  { "PRINT_INFO", 1 },
  { "SCREEN_OFF", 5 },
  { "SCREEN_ON", 4 },
  { "UNSET", 0 },
  { "WIFI_OFF", 16 },
  { "WIFI_ON", 17 },
};
const ProtobufCEnumDescriptor meshtastic__power_stress_message__opcode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.PowerStressMessage.Opcode",
  "Opcode",
  "Meshtastic__PowerStressMessage__Opcode",
  "meshtastic",
  20,
  meshtastic__power_stress_message__opcode__enum_values_by_number,
  20,
  meshtastic__power_stress_message__opcode__enum_values_by_name,
  8,
  meshtastic__power_stress_message__opcode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__power_stress_message__field_descriptors[2] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__PowerStressMessage, cmd),
    &meshtastic__power_stress_message__opcode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_seconds",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__PowerStressMessage, num_seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__power_stress_message__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  1,   /* field[1] = num_seconds */
};
static const ProtobufCIntRange meshtastic__power_stress_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor meshtastic__power_stress_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.PowerStressMessage",
  "PowerStressMessage",
  "Meshtastic__PowerStressMessage",
  "meshtastic",
  sizeof(Meshtastic__PowerStressMessage),
  2,
  meshtastic__power_stress_message__field_descriptors,
  meshtastic__power_stress_message__field_indices_by_name,
  1,  meshtastic__power_stress_message__number_ranges,
  (ProtobufCMessageInit) meshtastic__power_stress_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
