/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meshtastic/remote_hardware.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "meshtastic/remote_hardware.pb-c.h"
void   meshtastic__hardware_message__init
                     (Meshtastic__HardwareMessage         *message)
{
  static const Meshtastic__HardwareMessage init_value = MESHTASTIC__HARDWARE_MESSAGE__INIT;
  *message = init_value;
}
size_t meshtastic__hardware_message__get_packed_size
                     (const Meshtastic__HardwareMessage *message)
{
  assert(message->base.descriptor == &meshtastic__hardware_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meshtastic__hardware_message__pack
                     (const Meshtastic__HardwareMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &meshtastic__hardware_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meshtastic__hardware_message__pack_to_buffer
                     (const Meshtastic__HardwareMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &meshtastic__hardware_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Meshtastic__HardwareMessage *
       meshtastic__hardware_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Meshtastic__HardwareMessage *)
     protobuf_c_message_unpack (&meshtastic__hardware_message__descriptor,
                                allocator, len, data);
}
void   meshtastic__hardware_message__free_unpacked
                     (Meshtastic__HardwareMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &meshtastic__hardware_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue meshtastic__hardware_message__type__enum_values_by_number[6] =
{
  { "UNSET", "MESHTASTIC__HARDWARE_MESSAGE__TYPE__UNSET", 0 },
  { "WRITE_GPIOS", "MESHTASTIC__HARDWARE_MESSAGE__TYPE__WRITE_GPIOS", 1 },
  { "WATCH_GPIOS", "MESHTASTIC__HARDWARE_MESSAGE__TYPE__WATCH_GPIOS", 2 },
  { "GPIOS_CHANGED", "MESHTASTIC__HARDWARE_MESSAGE__TYPE__GPIOS_CHANGED", 3 },
  { "READ_GPIOS", "MESHTASTIC__HARDWARE_MESSAGE__TYPE__READ_GPIOS", 4 },
  { "READ_GPIOS_REPLY", "MESHTASTIC__HARDWARE_MESSAGE__TYPE__READ_GPIOS_REPLY", 5 },
};
static const ProtobufCIntRange meshtastic__hardware_message__type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex meshtastic__hardware_message__type__enum_values_by_name[6] =
{
  { "GPIOS_CHANGED", 3 },
  { "READ_GPIOS", 4 },
  { "READ_GPIOS_REPLY", 5 },
  { "UNSET", 0 },
  { "WATCH_GPIOS", 2 },
  { "WRITE_GPIOS", 1 },
};
const ProtobufCEnumDescriptor meshtastic__hardware_message__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "meshtastic.HardwareMessage.Type",
  "Type",
  "Meshtastic__HardwareMessage__Type",
  "meshtastic",
  6,
  meshtastic__hardware_message__type__enum_values_by_number,
  6,
  meshtastic__hardware_message__type__enum_values_by_name,
  1,
  meshtastic__hardware_message__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meshtastic__hardware_message__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__HardwareMessage, type),
    &meshtastic__hardware_message__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpio_mask",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__HardwareMessage, gpio_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpio_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Meshtastic__HardwareMessage, gpio_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meshtastic__hardware_message__field_indices_by_name[] = {
  1,   /* field[1] = gpio_mask */
  2,   /* field[2] = gpio_value */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange meshtastic__hardware_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor meshtastic__hardware_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "meshtastic.HardwareMessage",
  "HardwareMessage",
  "Meshtastic__HardwareMessage",
  "meshtastic",
  sizeof(Meshtastic__HardwareMessage),
  3,
  meshtastic__hardware_message__field_descriptors,
  meshtastic__hardware_message__field_indices_by_name,
  1,  meshtastic__hardware_message__number_ranges,
  (ProtobufCMessageInit) meshtastic__hardware_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
