/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/privateconfig.proto */

#ifndef PROTOBUF_C_protobuf_2fprivateconfig_2eproto__INCLUDED
#define PROTOBUF_C_protobuf_2fprivateconfig_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "nanopb.pb-c.h"

typedef struct Temeshtastic__DeviceLabels Temeshtastic__DeviceLabels;
typedef struct Temeshtastic__DeviceLabels__InfoLabel Temeshtastic__DeviceLabels__InfoLabel;
typedef struct Temeshtastic__SyncWakeupConfig Temeshtastic__SyncWakeupConfig;
typedef struct Temeshtastic__SyncWakeupConfig__TimeSlot Temeshtastic__SyncWakeupConfig__TimeSlot;
typedef struct Temeshtastic__SyncWakeupConfig__FixedWakeup Temeshtastic__SyncWakeupConfig__FixedWakeup;
typedef struct Temeshtastic__SyncWakeupConfig__ScheduledWakeup Temeshtastic__SyncWakeupConfig__ScheduledWakeup;
typedef struct Temeshtastic__CompanyConfig Temeshtastic__CompanyConfig;
typedef struct Temeshtastic__PrivateConfig Temeshtastic__PrivateConfig;
typedef struct Temeshtastic__PrivateConfigPacket Temeshtastic__PrivateConfigPacket;
typedef struct Temeshtastic__PrivateConfigPacket__SetAdminKey Temeshtastic__PrivateConfigPacket__SetAdminKey;
typedef struct Temeshtastic__PrivateConfigPacket__SetDeviceName Temeshtastic__PrivateConfigPacket__SetDeviceName;
typedef struct Temeshtastic__PrivateConfigPacket__SetInfoLabel Temeshtastic__PrivateConfigPacket__SetInfoLabel;
typedef struct Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel;
typedef struct Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig;
typedef struct Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest;
typedef struct Temeshtastic__PrivateConfigPacket__ChangeAdminRequest Temeshtastic__PrivateConfigPacket__ChangeAdminRequest;
typedef struct Temeshtastic__PrivateConfigPacket__Request Temeshtastic__PrivateConfigPacket__Request;
typedef struct Temeshtastic__PrivateConfigPacket__Response Temeshtastic__PrivateConfigPacket__Response;


/* --- enums --- */

/*
 * Wake-up strategy
 */
typedef enum _Temeshtastic__SyncWakeupConfig__WakeupStrategy {
  /*
   * Fixed interval
   */
  TEMESHTASTIC__SYNC_WAKEUP_CONFIG__WAKEUP_STRATEGY__STRATEGY_FIXED = 0,
  /*
   * Scheduled
   */
  TEMESHTASTIC__SYNC_WAKEUP_CONFIG__WAKEUP_STRATEGY__STRATEGY_SCHEDULED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TEMESHTASTIC__SYNC_WAKEUP_CONFIG__WAKEUP_STRATEGY)
} Temeshtastic__SyncWakeupConfig__WakeupStrategy;
typedef enum _Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabelAction {
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION__ADD = 0,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION__UPDATE = 1,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION__DELETE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION)
} Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabelAction;
typedef enum _Temeshtastic__PrivateConfigPacket__Status {
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__STATUS__OK = 0,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__STATUS__ERROR = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TEMESHTASTIC__PRIVATE_CONFIG_PACKET__STATUS)
} Temeshtastic__PrivateConfigPacket__Status;

/* --- messages --- */

struct  Temeshtastic__DeviceLabels__InfoLabel
{
  ProtobufCMessage base;
  uint32_t id;
  char *key;
  char *value;
};
#define TEMESHTASTIC__DEVICE_LABELS__INFO_LABEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__device_labels__info_label__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Temeshtastic__DeviceLabels
{
  ProtobufCMessage base;
  /*
   * repeated FunctionLabel function_labels = 2 [(nanopb).max_count = 10];
   */
  size_t n_info_labels;
  Temeshtastic__DeviceLabels__InfoLabel **info_labels;
};
#define TEMESHTASTIC__DEVICE_LABELS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__device_labels__descriptor) \
    , 0,NULL }


/*
 * Time slot configuration
 */
struct  Temeshtastic__SyncWakeupConfig__TimeSlot
{
  ProtobufCMessage base;
  /*
   * Start hour (0-23)
   */
  uint32_t start_hour;
  /*
   * End hour (0-23)
   */
  uint32_t end_hour;
  /*
   * Wake-up interval for this time slot (minutes)
   */
  uint32_t interval_min;
  /*
   * Alignment minute for this time slot (0-59)
   */
  uint32_t align_minute;
};
#define TEMESHTASTIC__SYNC_WAKEUP_CONFIG__TIME_SLOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__sync_wakeup_config__time_slot__descriptor) \
    , 0, 0, 0, 0 }


struct  Temeshtastic__SyncWakeupConfig__FixedWakeup
{
  ProtobufCMessage base;
  /*
   * Strategy 1: Fixed Interval
   * Wake-up interval in minutes (for fixed strategy) or default interval for scheduled strategy
   */
  uint32_t interval_min;
  /*
   * Alignment minute for wake-up (0-59), only applicable for fixed strategy
   */
  uint32_t align_minute;
  /*
   * Time offset in seconds for scheduled wake-up, only applicable for scheduled strategy
   */
  uint32_t offset_sec;
};
#define TEMESHTASTIC__SYNC_WAKEUP_CONFIG__FIXED_WAKEUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__sync_wakeup_config__fixed_wakeup__descriptor) \
    , 0, 0, 0 }


struct  Temeshtastic__SyncWakeupConfig__ScheduledWakeup
{
  ProtobufCMessage base;
  /*
   * Strategy 2: Scheduled
   * Time offset in seconds for scheduled wake-up
   */
  uint32_t offset_sec;
  size_t n_time_slots;
  Temeshtastic__SyncWakeupConfig__TimeSlot **time_slots;
};
#define TEMESHTASTIC__SYNC_WAKEUP_CONFIG__SCHEDULED_WAKEUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__sync_wakeup_config__scheduled_wakeup__descriptor) \
    , 0, 0,NULL }


struct  Temeshtastic__SyncWakeupConfig
{
  ProtobufCMessage base;
  /*
   * Whether to enable sync wake-up
   */
  protobuf_c_boolean enabled;
  /*
   * Wake-up strategy
   */
  Temeshtastic__SyncWakeupConfig__WakeupStrategy strategy;
  Temeshtastic__SyncWakeupConfig__FixedWakeup *fixed_wakeup;
  Temeshtastic__SyncWakeupConfig__ScheduledWakeup *scheduled_wakeup;
};
#define TEMESHTASTIC__SYNC_WAKEUP_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__sync_wakeup_config__descriptor) \
    , 0, TEMESHTASTIC__SYNC_WAKEUP_CONFIG__WAKEUP_STRATEGY__STRATEGY_FIXED, NULL, NULL }


/*
 * 公司配置（设备本地存储）
 */
struct  Temeshtastic__CompanyConfig
{
  ProtobufCMessage base;
  /*
   * 公司公钥 (32字节)
   */
  ProtobufCBinaryData company_public_key;
  /*
   * 是否已入网
   */
  protobuf_c_boolean is_enrolled;
  /*
   * 上次更换管理员时间
   */
  uint64_t last_change_timestamp;
};
#define TEMESHTASTIC__COMPANY_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__company_config__descriptor) \
    , {0,NULL}, 0, 0 }


struct  Temeshtastic__PrivateConfig
{
  ProtobufCMessage base;
  uint32_t privateversion;
  char *devicename;
  protobuf_c_boolean isadminkeyset;
  Temeshtastic__SyncWakeupConfig *sync_wakeup;
  Temeshtastic__CompanyConfig *company_config;
};
#define TEMESHTASTIC__PRIVATE_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, NULL, NULL }


struct  Temeshtastic__PrivateConfigPacket__SetAdminKey
{
  ProtobufCMessage base;
  ProtobufCBinaryData admin_key;
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_ADMIN_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__set_admin_key__descriptor) \
    , {0,NULL} }


struct  Temeshtastic__PrivateConfigPacket__SetDeviceName
{
  ProtobufCMessage base;
  char *device_name;
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_DEVICE_NAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__set_device_name__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel
{
  ProtobufCMessage base;
  uint32_t id;
  char *key;
  char *value;
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__set_info_label__info_label__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Temeshtastic__PrivateConfigPacket__SetInfoLabel
{
  ProtobufCMessage base;
  Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabelAction action;
  Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel *info_label;
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__set_info_label__descriptor) \
    , TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION__ADD, NULL }


struct  Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig
{
  ProtobufCMessage base;
  Temeshtastic__SyncWakeupConfig *config;
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_SYNC_WAKEUP_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__set_sync_wakeup_config__descriptor) \
    , NULL }


/*
 * 入网请求
 */
struct  Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest
{
  ProtobufCMessage base;
  /*
   * 公司公钥 (32字节)
   */
  ProtobufCBinaryData company_public_key;
  /*
   * 网关节点公钥 (32字节)
   */
  ProtobufCBinaryData gateway_public_key;
  /*
   * 网关节点ID
   */
  uint32_t gateway_node_id;
  /*
   * 时间戳
   */
  uint64_t timestamp;
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_COMPANY_KEY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__set_company_key_request__descriptor) \
    , {0,NULL}, {0,NULL}, 0, 0 }


/*
 * 更换管理员请求
 */
struct  Temeshtastic__PrivateConfigPacket__ChangeAdminRequest
{
  ProtobufCMessage base;
  /*
   * 新网关公钥 (32字节)
   */
  ProtobufCBinaryData new_gateway_public_key;
  /*
   * 新网关节点ID
   */
  uint32_t new_gateway_node_id;
  /*
   * 时间戳（防重放）
   */
  uint64_t timestamp;
  /*
   * Ed25519签名 (64字节)
   */
  ProtobufCBinaryData signature;
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__CHANGE_ADMIN_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__change_admin_request__descriptor) \
    , {0,NULL}, 0, 0, {0,NULL} }


typedef enum {
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD__NOT_SET = 0,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_GET_CONFIG = 2,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_GET_INFO_LABELS = 3,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_GET_SYNC_WAKEUP = 4,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_SET_ADMIN_KEY = 5,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_SET_DEVICE_NAME = 6,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_SET_INFO_LABEL = 7,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_SET_SYNC_WAKEUP_CONFIG = 8,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_SET_COMPANY_KEY = 9,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD_CHANGE_ADMIN = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD__CASE)
} Temeshtastic__PrivateConfigPacket__Request__PayloadCase;

struct  Temeshtastic__PrivateConfigPacket__Request
{
  ProtobufCMessage base;
  Temeshtastic__PrivateConfigPacket__Status status;
  Temeshtastic__PrivateConfigPacket__Request__PayloadCase payload_case;
  union {
    Temeshtastic__PrivateConfigPacket__ChangeAdminRequest *change_admin;
    Temeshtastic__PrivateConfigPacket__SetAdminKey *set_admin_key;
    Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest *set_company_key;
    Temeshtastic__PrivateConfigPacket__SetDeviceName *set_device_name;
    Temeshtastic__PrivateConfigPacket__SetInfoLabel *set_info_label;
    Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig *set_sync_wakeup_config;
    protobuf_c_boolean get_config;
    protobuf_c_boolean get_info_labels;
    protobuf_c_boolean get_sync_wakeup;
  };
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__request__descriptor) \
    , TEMESHTASTIC__PRIVATE_CONFIG_PACKET__STATUS__OK, TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__PAYLOAD__NOT_SET, {0} }


typedef enum {
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__PAYLOAD__NOT_SET = 0,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__PAYLOAD_PRIVATE_CONFIG = 1,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__PAYLOAD_DEVICE_LABELS = 2,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__PAYLOAD_SYNC_WAKEUP_CONFIG = 3,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__PAYLOAD_COMPANY_CONFIG = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__PAYLOAD__CASE)
} Temeshtastic__PrivateConfigPacket__Response__PayloadCase;

struct  Temeshtastic__PrivateConfigPacket__Response
{
  ProtobufCMessage base;
  Temeshtastic__PrivateConfigPacket__Response__PayloadCase payload_case;
  union {
    Temeshtastic__CompanyConfig *company_config;
    Temeshtastic__DeviceLabels *device_labels;
    Temeshtastic__PrivateConfig *private_config;
    Temeshtastic__SyncWakeupConfig *sync_wakeup_config;
  };
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__response__descriptor) \
    , TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__PAYLOAD__NOT_SET, {0} }


typedef enum {
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__PACKET_TYPE__NOT_SET = 0,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__PACKET_TYPE_REQUEST = 1,
  TEMESHTASTIC__PRIVATE_CONFIG_PACKET__PACKET_TYPE_RESPONSE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TEMESHTASTIC__PRIVATE_CONFIG_PACKET__PACKET_TYPE__CASE)
} Temeshtastic__PrivateConfigPacket__PacketTypeCase;

struct  Temeshtastic__PrivateConfigPacket
{
  ProtobufCMessage base;
  Temeshtastic__PrivateConfigPacket__PacketTypeCase packet_type_case;
  union {
    Temeshtastic__PrivateConfigPacket__Request *request;
    Temeshtastic__PrivateConfigPacket__Response *response;
  };
};
#define TEMESHTASTIC__PRIVATE_CONFIG_PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temeshtastic__private_config_packet__descriptor) \
    , TEMESHTASTIC__PRIVATE_CONFIG_PACKET__PACKET_TYPE__NOT_SET, {0} }


/* Temeshtastic__DeviceLabels__InfoLabel methods */
void   temeshtastic__device_labels__info_label__init
                     (Temeshtastic__DeviceLabels__InfoLabel         *message);
/* Temeshtastic__DeviceLabels methods */
void   temeshtastic__device_labels__init
                     (Temeshtastic__DeviceLabels         *message);
size_t temeshtastic__device_labels__get_packed_size
                     (const Temeshtastic__DeviceLabels   *message);
size_t temeshtastic__device_labels__pack
                     (const Temeshtastic__DeviceLabels   *message,
                      uint8_t             *out);
size_t temeshtastic__device_labels__pack_to_buffer
                     (const Temeshtastic__DeviceLabels   *message,
                      ProtobufCBuffer     *buffer);
Temeshtastic__DeviceLabels *
       temeshtastic__device_labels__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temeshtastic__device_labels__free_unpacked
                     (Temeshtastic__DeviceLabels *message,
                      ProtobufCAllocator *allocator);
/* Temeshtastic__SyncWakeupConfig__TimeSlot methods */
void   temeshtastic__sync_wakeup_config__time_slot__init
                     (Temeshtastic__SyncWakeupConfig__TimeSlot         *message);
/* Temeshtastic__SyncWakeupConfig__FixedWakeup methods */
void   temeshtastic__sync_wakeup_config__fixed_wakeup__init
                     (Temeshtastic__SyncWakeupConfig__FixedWakeup         *message);
/* Temeshtastic__SyncWakeupConfig__ScheduledWakeup methods */
void   temeshtastic__sync_wakeup_config__scheduled_wakeup__init
                     (Temeshtastic__SyncWakeupConfig__ScheduledWakeup         *message);
/* Temeshtastic__SyncWakeupConfig methods */
void   temeshtastic__sync_wakeup_config__init
                     (Temeshtastic__SyncWakeupConfig         *message);
size_t temeshtastic__sync_wakeup_config__get_packed_size
                     (const Temeshtastic__SyncWakeupConfig   *message);
size_t temeshtastic__sync_wakeup_config__pack
                     (const Temeshtastic__SyncWakeupConfig   *message,
                      uint8_t             *out);
size_t temeshtastic__sync_wakeup_config__pack_to_buffer
                     (const Temeshtastic__SyncWakeupConfig   *message,
                      ProtobufCBuffer     *buffer);
Temeshtastic__SyncWakeupConfig *
       temeshtastic__sync_wakeup_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temeshtastic__sync_wakeup_config__free_unpacked
                     (Temeshtastic__SyncWakeupConfig *message,
                      ProtobufCAllocator *allocator);
/* Temeshtastic__CompanyConfig methods */
void   temeshtastic__company_config__init
                     (Temeshtastic__CompanyConfig         *message);
size_t temeshtastic__company_config__get_packed_size
                     (const Temeshtastic__CompanyConfig   *message);
size_t temeshtastic__company_config__pack
                     (const Temeshtastic__CompanyConfig   *message,
                      uint8_t             *out);
size_t temeshtastic__company_config__pack_to_buffer
                     (const Temeshtastic__CompanyConfig   *message,
                      ProtobufCBuffer     *buffer);
Temeshtastic__CompanyConfig *
       temeshtastic__company_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temeshtastic__company_config__free_unpacked
                     (Temeshtastic__CompanyConfig *message,
                      ProtobufCAllocator *allocator);
/* Temeshtastic__PrivateConfig methods */
void   temeshtastic__private_config__init
                     (Temeshtastic__PrivateConfig         *message);
size_t temeshtastic__private_config__get_packed_size
                     (const Temeshtastic__PrivateConfig   *message);
size_t temeshtastic__private_config__pack
                     (const Temeshtastic__PrivateConfig   *message,
                      uint8_t             *out);
size_t temeshtastic__private_config__pack_to_buffer
                     (const Temeshtastic__PrivateConfig   *message,
                      ProtobufCBuffer     *buffer);
Temeshtastic__PrivateConfig *
       temeshtastic__private_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temeshtastic__private_config__free_unpacked
                     (Temeshtastic__PrivateConfig *message,
                      ProtobufCAllocator *allocator);
/* Temeshtastic__PrivateConfigPacket__SetAdminKey methods */
void   temeshtastic__private_config_packet__set_admin_key__init
                     (Temeshtastic__PrivateConfigPacket__SetAdminKey         *message);
/* Temeshtastic__PrivateConfigPacket__SetDeviceName methods */
void   temeshtastic__private_config_packet__set_device_name__init
                     (Temeshtastic__PrivateConfigPacket__SetDeviceName         *message);
/* Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel methods */
void   temeshtastic__private_config_packet__set_info_label__info_label__init
                     (Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel         *message);
/* Temeshtastic__PrivateConfigPacket__SetInfoLabel methods */
void   temeshtastic__private_config_packet__set_info_label__init
                     (Temeshtastic__PrivateConfigPacket__SetInfoLabel         *message);
/* Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig methods */
void   temeshtastic__private_config_packet__set_sync_wakeup_config__init
                     (Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig         *message);
/* Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest methods */
void   temeshtastic__private_config_packet__set_company_key_request__init
                     (Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest         *message);
/* Temeshtastic__PrivateConfigPacket__ChangeAdminRequest methods */
void   temeshtastic__private_config_packet__change_admin_request__init
                     (Temeshtastic__PrivateConfigPacket__ChangeAdminRequest         *message);
/* Temeshtastic__PrivateConfigPacket__Request methods */
void   temeshtastic__private_config_packet__request__init
                     (Temeshtastic__PrivateConfigPacket__Request         *message);
/* Temeshtastic__PrivateConfigPacket__Response methods */
void   temeshtastic__private_config_packet__response__init
                     (Temeshtastic__PrivateConfigPacket__Response         *message);
/* Temeshtastic__PrivateConfigPacket methods */
void   temeshtastic__private_config_packet__init
                     (Temeshtastic__PrivateConfigPacket         *message);
size_t temeshtastic__private_config_packet__get_packed_size
                     (const Temeshtastic__PrivateConfigPacket   *message);
size_t temeshtastic__private_config_packet__pack
                     (const Temeshtastic__PrivateConfigPacket   *message,
                      uint8_t             *out);
size_t temeshtastic__private_config_packet__pack_to_buffer
                     (const Temeshtastic__PrivateConfigPacket   *message,
                      ProtobufCBuffer     *buffer);
Temeshtastic__PrivateConfigPacket *
       temeshtastic__private_config_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temeshtastic__private_config_packet__free_unpacked
                     (Temeshtastic__PrivateConfigPacket *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Temeshtastic__DeviceLabels__InfoLabel_Closure)
                 (const Temeshtastic__DeviceLabels__InfoLabel *message,
                  void *closure_data);
typedef void (*Temeshtastic__DeviceLabels_Closure)
                 (const Temeshtastic__DeviceLabels *message,
                  void *closure_data);
typedef void (*Temeshtastic__SyncWakeupConfig__TimeSlot_Closure)
                 (const Temeshtastic__SyncWakeupConfig__TimeSlot *message,
                  void *closure_data);
typedef void (*Temeshtastic__SyncWakeupConfig__FixedWakeup_Closure)
                 (const Temeshtastic__SyncWakeupConfig__FixedWakeup *message,
                  void *closure_data);
typedef void (*Temeshtastic__SyncWakeupConfig__ScheduledWakeup_Closure)
                 (const Temeshtastic__SyncWakeupConfig__ScheduledWakeup *message,
                  void *closure_data);
typedef void (*Temeshtastic__SyncWakeupConfig_Closure)
                 (const Temeshtastic__SyncWakeupConfig *message,
                  void *closure_data);
typedef void (*Temeshtastic__CompanyConfig_Closure)
                 (const Temeshtastic__CompanyConfig *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfig_Closure)
                 (const Temeshtastic__PrivateConfig *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__SetAdminKey_Closure)
                 (const Temeshtastic__PrivateConfigPacket__SetAdminKey *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__SetDeviceName_Closure)
                 (const Temeshtastic__PrivateConfigPacket__SetDeviceName *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel_Closure)
                 (const Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__SetInfoLabel_Closure)
                 (const Temeshtastic__PrivateConfigPacket__SetInfoLabel *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig_Closure)
                 (const Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest_Closure)
                 (const Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__ChangeAdminRequest_Closure)
                 (const Temeshtastic__PrivateConfigPacket__ChangeAdminRequest *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__Request_Closure)
                 (const Temeshtastic__PrivateConfigPacket__Request *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket__Response_Closure)
                 (const Temeshtastic__PrivateConfigPacket__Response *message,
                  void *closure_data);
typedef void (*Temeshtastic__PrivateConfigPacket_Closure)
                 (const Temeshtastic__PrivateConfigPacket *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor temeshtastic__device_labels__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__device_labels__info_label__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__time_slot__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__fixed_wakeup__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__scheduled_wakeup__descriptor;
extern const ProtobufCEnumDescriptor    temeshtastic__sync_wakeup_config__wakeup_strategy__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__company_config__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_admin_key__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_device_name__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_info_label__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_info_label__info_label__descriptor;
extern const ProtobufCEnumDescriptor    temeshtastic__private_config_packet__set_info_label__info_label_action__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_sync_wakeup_config__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_company_key_request__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__change_admin_request__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__request__descriptor;
extern const ProtobufCMessageDescriptor temeshtastic__private_config_packet__response__descriptor;
extern const ProtobufCEnumDescriptor    temeshtastic__private_config_packet__status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_protobuf_2fprivateconfig_2eproto__INCLUDED */
