/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/privateconfig.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "privateconfig.pb-c.h"
void   temeshtastic__device_labels__info_label__init
                     (Temeshtastic__DeviceLabels__InfoLabel         *message)
{
  static const Temeshtastic__DeviceLabels__InfoLabel init_value = TEMESHTASTIC__DEVICE_LABELS__INFO_LABEL__INIT;
  *message = init_value;
}
void   temeshtastic__device_labels__init
                     (Temeshtastic__DeviceLabels         *message)
{
  static const Temeshtastic__DeviceLabels init_value = TEMESHTASTIC__DEVICE_LABELS__INIT;
  *message = init_value;
}
size_t temeshtastic__device_labels__get_packed_size
                     (const Temeshtastic__DeviceLabels *message)
{
  assert(message->base.descriptor == &temeshtastic__device_labels__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t temeshtastic__device_labels__pack
                     (const Temeshtastic__DeviceLabels *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &temeshtastic__device_labels__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t temeshtastic__device_labels__pack_to_buffer
                     (const Temeshtastic__DeviceLabels *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &temeshtastic__device_labels__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Temeshtastic__DeviceLabels *
       temeshtastic__device_labels__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Temeshtastic__DeviceLabels *)
     protobuf_c_message_unpack (&temeshtastic__device_labels__descriptor,
                                allocator, len, data);
}
void   temeshtastic__device_labels__free_unpacked
                     (Temeshtastic__DeviceLabels *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &temeshtastic__device_labels__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   temeshtastic__sync_wakeup_config__time_slot__init
                     (Temeshtastic__SyncWakeupConfig__TimeSlot         *message)
{
  static const Temeshtastic__SyncWakeupConfig__TimeSlot init_value = TEMESHTASTIC__SYNC_WAKEUP_CONFIG__TIME_SLOT__INIT;
  *message = init_value;
}
void   temeshtastic__sync_wakeup_config__fixed_wakeup__init
                     (Temeshtastic__SyncWakeupConfig__FixedWakeup         *message)
{
  static const Temeshtastic__SyncWakeupConfig__FixedWakeup init_value = TEMESHTASTIC__SYNC_WAKEUP_CONFIG__FIXED_WAKEUP__INIT;
  *message = init_value;
}
void   temeshtastic__sync_wakeup_config__scheduled_wakeup__init
                     (Temeshtastic__SyncWakeupConfig__ScheduledWakeup         *message)
{
  static const Temeshtastic__SyncWakeupConfig__ScheduledWakeup init_value = TEMESHTASTIC__SYNC_WAKEUP_CONFIG__SCHEDULED_WAKEUP__INIT;
  *message = init_value;
}
void   temeshtastic__sync_wakeup_config__init
                     (Temeshtastic__SyncWakeupConfig         *message)
{
  static const Temeshtastic__SyncWakeupConfig init_value = TEMESHTASTIC__SYNC_WAKEUP_CONFIG__INIT;
  *message = init_value;
}
size_t temeshtastic__sync_wakeup_config__get_packed_size
                     (const Temeshtastic__SyncWakeupConfig *message)
{
  assert(message->base.descriptor == &temeshtastic__sync_wakeup_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t temeshtastic__sync_wakeup_config__pack
                     (const Temeshtastic__SyncWakeupConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &temeshtastic__sync_wakeup_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t temeshtastic__sync_wakeup_config__pack_to_buffer
                     (const Temeshtastic__SyncWakeupConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &temeshtastic__sync_wakeup_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Temeshtastic__SyncWakeupConfig *
       temeshtastic__sync_wakeup_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Temeshtastic__SyncWakeupConfig *)
     protobuf_c_message_unpack (&temeshtastic__sync_wakeup_config__descriptor,
                                allocator, len, data);
}
void   temeshtastic__sync_wakeup_config__free_unpacked
                     (Temeshtastic__SyncWakeupConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &temeshtastic__sync_wakeup_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   temeshtastic__company_config__init
                     (Temeshtastic__CompanyConfig         *message)
{
  static const Temeshtastic__CompanyConfig init_value = TEMESHTASTIC__COMPANY_CONFIG__INIT;
  *message = init_value;
}
size_t temeshtastic__company_config__get_packed_size
                     (const Temeshtastic__CompanyConfig *message)
{
  assert(message->base.descriptor == &temeshtastic__company_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t temeshtastic__company_config__pack
                     (const Temeshtastic__CompanyConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &temeshtastic__company_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t temeshtastic__company_config__pack_to_buffer
                     (const Temeshtastic__CompanyConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &temeshtastic__company_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Temeshtastic__CompanyConfig *
       temeshtastic__company_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Temeshtastic__CompanyConfig *)
     protobuf_c_message_unpack (&temeshtastic__company_config__descriptor,
                                allocator, len, data);
}
void   temeshtastic__company_config__free_unpacked
                     (Temeshtastic__CompanyConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &temeshtastic__company_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   temeshtastic__private_config__init
                     (Temeshtastic__PrivateConfig         *message)
{
  static const Temeshtastic__PrivateConfig init_value = TEMESHTASTIC__PRIVATE_CONFIG__INIT;
  *message = init_value;
}
size_t temeshtastic__private_config__get_packed_size
                     (const Temeshtastic__PrivateConfig *message)
{
  assert(message->base.descriptor == &temeshtastic__private_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t temeshtastic__private_config__pack
                     (const Temeshtastic__PrivateConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &temeshtastic__private_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t temeshtastic__private_config__pack_to_buffer
                     (const Temeshtastic__PrivateConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &temeshtastic__private_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Temeshtastic__PrivateConfig *
       temeshtastic__private_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Temeshtastic__PrivateConfig *)
     protobuf_c_message_unpack (&temeshtastic__private_config__descriptor,
                                allocator, len, data);
}
void   temeshtastic__private_config__free_unpacked
                     (Temeshtastic__PrivateConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &temeshtastic__private_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   temeshtastic__private_config_packet__set_admin_key__init
                     (Temeshtastic__PrivateConfigPacket__SetAdminKey         *message)
{
  static const Temeshtastic__PrivateConfigPacket__SetAdminKey init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_ADMIN_KEY__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__set_device_name__init
                     (Temeshtastic__PrivateConfigPacket__SetDeviceName         *message)
{
  static const Temeshtastic__PrivateConfigPacket__SetDeviceName init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_DEVICE_NAME__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__set_info_label__info_label__init
                     (Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel         *message)
{
  static const Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__set_info_label__init
                     (Temeshtastic__PrivateConfigPacket__SetInfoLabel         *message)
{
  static const Temeshtastic__PrivateConfigPacket__SetInfoLabel init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__set_sync_wakeup_config__init
                     (Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig         *message)
{
  static const Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_SYNC_WAKEUP_CONFIG__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__set_company_key_request__init
                     (Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest         *message)
{
  static const Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_COMPANY_KEY_REQUEST__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__change_admin_request__init
                     (Temeshtastic__PrivateConfigPacket__ChangeAdminRequest         *message)
{
  static const Temeshtastic__PrivateConfigPacket__ChangeAdminRequest init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__CHANGE_ADMIN_REQUEST__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__request__init
                     (Temeshtastic__PrivateConfigPacket__Request         *message)
{
  static const Temeshtastic__PrivateConfigPacket__Request init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__REQUEST__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__response__init
                     (Temeshtastic__PrivateConfigPacket__Response         *message)
{
  static const Temeshtastic__PrivateConfigPacket__Response init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__RESPONSE__INIT;
  *message = init_value;
}
void   temeshtastic__private_config_packet__init
                     (Temeshtastic__PrivateConfigPacket         *message)
{
  static const Temeshtastic__PrivateConfigPacket init_value = TEMESHTASTIC__PRIVATE_CONFIG_PACKET__INIT;
  *message = init_value;
}
size_t temeshtastic__private_config_packet__get_packed_size
                     (const Temeshtastic__PrivateConfigPacket *message)
{
  assert(message->base.descriptor == &temeshtastic__private_config_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t temeshtastic__private_config_packet__pack
                     (const Temeshtastic__PrivateConfigPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &temeshtastic__private_config_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t temeshtastic__private_config_packet__pack_to_buffer
                     (const Temeshtastic__PrivateConfigPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &temeshtastic__private_config_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Temeshtastic__PrivateConfigPacket *
       temeshtastic__private_config_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Temeshtastic__PrivateConfigPacket *)
     protobuf_c_message_unpack (&temeshtastic__private_config_packet__descriptor,
                                allocator, len, data);
}
void   temeshtastic__private_config_packet__free_unpacked
                     (Temeshtastic__PrivateConfigPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &temeshtastic__private_config_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor temeshtastic__device_labels__info_label__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__DeviceLabels__InfoLabel, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__DeviceLabels__InfoLabel, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__DeviceLabels__InfoLabel, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__device_labels__info_label__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = key */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange temeshtastic__device_labels__info_label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor temeshtastic__device_labels__info_label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.DeviceLabels.InfoLabel",
  "InfoLabel",
  "Temeshtastic__DeviceLabels__InfoLabel",
  "temeshtastic",
  sizeof(Temeshtastic__DeviceLabels__InfoLabel),
  3,
  temeshtastic__device_labels__info_label__field_descriptors,
  temeshtastic__device_labels__info_label__field_indices_by_name,
  1,  temeshtastic__device_labels__info_label__number_ranges,
  (ProtobufCMessageInit) temeshtastic__device_labels__info_label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__device_labels__field_descriptors[1] =
{
  {
    "info_labels",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__DeviceLabels, n_info_labels),
    offsetof(Temeshtastic__DeviceLabels, info_labels),
    &temeshtastic__device_labels__info_label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__device_labels__field_indices_by_name[] = {
  0,   /* field[0] = info_labels */
};
static const ProtobufCIntRange temeshtastic__device_labels__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor temeshtastic__device_labels__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.DeviceLabels",
  "DeviceLabels",
  "Temeshtastic__DeviceLabels",
  "temeshtastic",
  sizeof(Temeshtastic__DeviceLabels),
  1,
  temeshtastic__device_labels__field_descriptors,
  temeshtastic__device_labels__field_indices_by_name,
  1,  temeshtastic__device_labels__number_ranges,
  (ProtobufCMessageInit) temeshtastic__device_labels__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__sync_wakeup_config__time_slot__field_descriptors[4] =
{
  {
    "start_hour",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__TimeSlot, start_hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_hour",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__TimeSlot, end_hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval_min",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__TimeSlot, interval_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "align_minute",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__TimeSlot, align_minute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__sync_wakeup_config__time_slot__field_indices_by_name[] = {
  3,   /* field[3] = align_minute */
  1,   /* field[1] = end_hour */
  2,   /* field[2] = interval_min */
  0,   /* field[0] = start_hour */
};
static const ProtobufCIntRange temeshtastic__sync_wakeup_config__time_slot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__time_slot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.SyncWakeupConfig.TimeSlot",
  "TimeSlot",
  "Temeshtastic__SyncWakeupConfig__TimeSlot",
  "temeshtastic",
  sizeof(Temeshtastic__SyncWakeupConfig__TimeSlot),
  4,
  temeshtastic__sync_wakeup_config__time_slot__field_descriptors,
  temeshtastic__sync_wakeup_config__time_slot__field_indices_by_name,
  1,  temeshtastic__sync_wakeup_config__time_slot__number_ranges,
  (ProtobufCMessageInit) temeshtastic__sync_wakeup_config__time_slot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__sync_wakeup_config__fixed_wakeup__field_descriptors[3] =
{
  {
    "interval_min",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__FixedWakeup, interval_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "align_minute",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__FixedWakeup, align_minute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset_sec",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__FixedWakeup, offset_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__sync_wakeup_config__fixed_wakeup__field_indices_by_name[] = {
  1,   /* field[1] = align_minute */
  0,   /* field[0] = interval_min */
  2,   /* field[2] = offset_sec */
};
static const ProtobufCIntRange temeshtastic__sync_wakeup_config__fixed_wakeup__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__fixed_wakeup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.SyncWakeupConfig.FixedWakeup",
  "FixedWakeup",
  "Temeshtastic__SyncWakeupConfig__FixedWakeup",
  "temeshtastic",
  sizeof(Temeshtastic__SyncWakeupConfig__FixedWakeup),
  3,
  temeshtastic__sync_wakeup_config__fixed_wakeup__field_descriptors,
  temeshtastic__sync_wakeup_config__fixed_wakeup__field_indices_by_name,
  1,  temeshtastic__sync_wakeup_config__fixed_wakeup__number_ranges,
  (ProtobufCMessageInit) temeshtastic__sync_wakeup_config__fixed_wakeup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__sync_wakeup_config__scheduled_wakeup__field_descriptors[2] =
{
  {
    "offset_sec",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig__ScheduledWakeup, offset_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_slots",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__SyncWakeupConfig__ScheduledWakeup, n_time_slots),
    offsetof(Temeshtastic__SyncWakeupConfig__ScheduledWakeup, time_slots),
    &temeshtastic__sync_wakeup_config__time_slot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__sync_wakeup_config__scheduled_wakeup__field_indices_by_name[] = {
  0,   /* field[0] = offset_sec */
  1,   /* field[1] = time_slots */
};
static const ProtobufCIntRange temeshtastic__sync_wakeup_config__scheduled_wakeup__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__scheduled_wakeup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.SyncWakeupConfig.ScheduledWakeup",
  "ScheduledWakeup",
  "Temeshtastic__SyncWakeupConfig__ScheduledWakeup",
  "temeshtastic",
  sizeof(Temeshtastic__SyncWakeupConfig__ScheduledWakeup),
  2,
  temeshtastic__sync_wakeup_config__scheduled_wakeup__field_descriptors,
  temeshtastic__sync_wakeup_config__scheduled_wakeup__field_indices_by_name,
  2,  temeshtastic__sync_wakeup_config__scheduled_wakeup__number_ranges,
  (ProtobufCMessageInit) temeshtastic__sync_wakeup_config__scheduled_wakeup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue temeshtastic__sync_wakeup_config__wakeup_strategy__enum_values_by_number[2] =
{
  { "STRATEGY_FIXED", "TEMESHTASTIC__SYNC_WAKEUP_CONFIG__WAKEUP_STRATEGY__STRATEGY_FIXED", 0 },
  { "STRATEGY_SCHEDULED", "TEMESHTASTIC__SYNC_WAKEUP_CONFIG__WAKEUP_STRATEGY__STRATEGY_SCHEDULED", 1 },
};
static const ProtobufCIntRange temeshtastic__sync_wakeup_config__wakeup_strategy__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex temeshtastic__sync_wakeup_config__wakeup_strategy__enum_values_by_name[2] =
{
  { "STRATEGY_FIXED", 0 },
  { "STRATEGY_SCHEDULED", 1 },
};
const ProtobufCEnumDescriptor temeshtastic__sync_wakeup_config__wakeup_strategy__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "temeshtastic.SyncWakeupConfig.WakeupStrategy",
  "WakeupStrategy",
  "Temeshtastic__SyncWakeupConfig__WakeupStrategy",
  "temeshtastic",
  2,
  temeshtastic__sync_wakeup_config__wakeup_strategy__enum_values_by_number,
  2,
  temeshtastic__sync_wakeup_config__wakeup_strategy__enum_values_by_name,
  1,
  temeshtastic__sync_wakeup_config__wakeup_strategy__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor temeshtastic__sync_wakeup_config__field_descriptors[4] =
{
  {
    "enabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig, enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "strategy",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig, strategy),
    &temeshtastic__sync_wakeup_config__wakeup_strategy__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixed_wakeup",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig, fixed_wakeup),
    &temeshtastic__sync_wakeup_config__fixed_wakeup__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scheduled_wakeup",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__SyncWakeupConfig, scheduled_wakeup),
    &temeshtastic__sync_wakeup_config__scheduled_wakeup__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__sync_wakeup_config__field_indices_by_name[] = {
  0,   /* field[0] = enabled */
  2,   /* field[2] = fixed_wakeup */
  3,   /* field[3] = scheduled_wakeup */
  1,   /* field[1] = strategy */
};
static const ProtobufCIntRange temeshtastic__sync_wakeup_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor temeshtastic__sync_wakeup_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.SyncWakeupConfig",
  "SyncWakeupConfig",
  "Temeshtastic__SyncWakeupConfig",
  "temeshtastic",
  sizeof(Temeshtastic__SyncWakeupConfig),
  4,
  temeshtastic__sync_wakeup_config__field_descriptors,
  temeshtastic__sync_wakeup_config__field_indices_by_name,
  1,  temeshtastic__sync_wakeup_config__number_ranges,
  (ProtobufCMessageInit) temeshtastic__sync_wakeup_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__company_config__field_descriptors[3] =
{
  {
    "company_public_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__CompanyConfig, company_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_enrolled",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__CompanyConfig, is_enrolled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_change_timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__CompanyConfig, last_change_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__company_config__field_indices_by_name[] = {
  0,   /* field[0] = company_public_key */
  1,   /* field[1] = is_enrolled */
  2,   /* field[2] = last_change_timestamp */
};
static const ProtobufCIntRange temeshtastic__company_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor temeshtastic__company_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.CompanyConfig",
  "CompanyConfig",
  "Temeshtastic__CompanyConfig",
  "temeshtastic",
  sizeof(Temeshtastic__CompanyConfig),
  3,
  temeshtastic__company_config__field_descriptors,
  temeshtastic__company_config__field_indices_by_name,
  1,  temeshtastic__company_config__number_ranges,
  (ProtobufCMessageInit) temeshtastic__company_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config__field_descriptors[5] =
{
  {
    "privateVersion",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfig, privateversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceName",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfig, devicename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isAdminKeySet",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfig, isadminkeyset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_wakeup",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfig, sync_wakeup),
    &temeshtastic__sync_wakeup_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company_config",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfig, company_config),
    &temeshtastic__company_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config__field_indices_by_name[] = {
  4,   /* field[4] = company_config */
  1,   /* field[1] = deviceName */
  2,   /* field[2] = isAdminKeySet */
  0,   /* field[0] = privateVersion */
  3,   /* field[3] = sync_wakeup */
};
static const ProtobufCIntRange temeshtastic__private_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfig",
  "PrivateConfig",
  "Temeshtastic__PrivateConfig",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfig),
  5,
  temeshtastic__private_config__field_descriptors,
  temeshtastic__private_config__field_indices_by_name,
  1,  temeshtastic__private_config__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__set_admin_key__field_descriptors[1] =
{
  {
    "admin_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetAdminKey, admin_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__set_admin_key__field_indices_by_name[] = {
  0,   /* field[0] = admin_key */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__set_admin_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_admin_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.SetAdminKey",
  "SetAdminKey",
  "Temeshtastic__PrivateConfigPacket__SetAdminKey",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__SetAdminKey),
  1,
  temeshtastic__private_config_packet__set_admin_key__field_descriptors,
  temeshtastic__private_config_packet__set_admin_key__field_indices_by_name,
  1,  temeshtastic__private_config_packet__set_admin_key__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__set_admin_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__set_device_name__field_descriptors[1] =
{
  {
    "device_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetDeviceName, device_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__set_device_name__field_indices_by_name[] = {
  0,   /* field[0] = device_name */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__set_device_name__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_device_name__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.SetDeviceName",
  "SetDeviceName",
  "Temeshtastic__PrivateConfigPacket__SetDeviceName",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__SetDeviceName),
  1,
  temeshtastic__private_config_packet__set_device_name__field_descriptors,
  temeshtastic__private_config_packet__set_device_name__field_indices_by_name,
  1,  temeshtastic__private_config_packet__set_device_name__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__set_device_name__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__set_info_label__info_label__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__set_info_label__info_label__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = key */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__set_info_label__info_label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_info_label__info_label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.SetInfoLabel.InfoLabel",
  "InfoLabel",
  "Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabel),
  3,
  temeshtastic__private_config_packet__set_info_label__info_label__field_descriptors,
  temeshtastic__private_config_packet__set_info_label__info_label__field_indices_by_name,
  1,  temeshtastic__private_config_packet__set_info_label__info_label__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__set_info_label__info_label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue temeshtastic__private_config_packet__set_info_label__info_label_action__enum_values_by_number[3] =
{
  { "ADD", "TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION__ADD", 0 },
  { "UPDATE", "TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION__UPDATE", 1 },
  { "DELETE", "TEMESHTASTIC__PRIVATE_CONFIG_PACKET__SET_INFO_LABEL__INFO_LABEL_ACTION__DELETE", 2 },
};
static const ProtobufCIntRange temeshtastic__private_config_packet__set_info_label__info_label_action__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex temeshtastic__private_config_packet__set_info_label__info_label_action__enum_values_by_name[3] =
{
  { "ADD", 0 },
  { "DELETE", 2 },
  { "UPDATE", 1 },
};
const ProtobufCEnumDescriptor temeshtastic__private_config_packet__set_info_label__info_label_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.SetInfoLabel.InfoLabelAction",
  "InfoLabelAction",
  "Temeshtastic__PrivateConfigPacket__SetInfoLabel__InfoLabelAction",
  "temeshtastic",
  3,
  temeshtastic__private_config_packet__set_info_label__info_label_action__enum_values_by_number,
  3,
  temeshtastic__private_config_packet__set_info_label__info_label_action__enum_values_by_name,
  1,
  temeshtastic__private_config_packet__set_info_label__info_label_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__set_info_label__field_descriptors[2] =
{
  {
    "action",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetInfoLabel, action),
    &temeshtastic__private_config_packet__set_info_label__info_label_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info_label",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetInfoLabel, info_label),
    &temeshtastic__private_config_packet__set_info_label__info_label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__set_info_label__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = info_label */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__set_info_label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_info_label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.SetInfoLabel",
  "SetInfoLabel",
  "Temeshtastic__PrivateConfigPacket__SetInfoLabel",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__SetInfoLabel),
  2,
  temeshtastic__private_config_packet__set_info_label__field_descriptors,
  temeshtastic__private_config_packet__set_info_label__field_indices_by_name,
  1,  temeshtastic__private_config_packet__set_info_label__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__set_info_label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__set_sync_wakeup_config__field_descriptors[1] =
{
  {
    "config",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig, config),
    &temeshtastic__sync_wakeup_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__set_sync_wakeup_config__field_indices_by_name[] = {
  0,   /* field[0] = config */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__set_sync_wakeup_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_sync_wakeup_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.SetSyncWakeupConfig",
  "SetSyncWakeupConfig",
  "Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__SetSyncWakeupConfig),
  1,
  temeshtastic__private_config_packet__set_sync_wakeup_config__field_descriptors,
  temeshtastic__private_config_packet__set_sync_wakeup_config__field_indices_by_name,
  1,  temeshtastic__private_config_packet__set_sync_wakeup_config__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__set_sync_wakeup_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__set_company_key_request__field_descriptors[4] =
{
  {
    "company_public_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest, company_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_public_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest, gateway_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_node_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest, gateway_node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__set_company_key_request__field_indices_by_name[] = {
  0,   /* field[0] = company_public_key */
  2,   /* field[2] = gateway_node_id */
  1,   /* field[1] = gateway_public_key */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__set_company_key_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__set_company_key_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.SetCompanyKeyRequest",
  "SetCompanyKeyRequest",
  "Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__SetCompanyKeyRequest),
  4,
  temeshtastic__private_config_packet__set_company_key_request__field_descriptors,
  temeshtastic__private_config_packet__set_company_key_request__field_indices_by_name,
  1,  temeshtastic__private_config_packet__set_company_key_request__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__set_company_key_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__change_admin_request__field_descriptors[4] =
{
  {
    "new_gateway_public_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__ChangeAdminRequest, new_gateway_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_gateway_node_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__ChangeAdminRequest, new_gateway_node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__ChangeAdminRequest, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__ChangeAdminRequest, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__change_admin_request__field_indices_by_name[] = {
  1,   /* field[1] = new_gateway_node_id */
  0,   /* field[0] = new_gateway_public_key */
  3,   /* field[3] = signature */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__change_admin_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__change_admin_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.ChangeAdminRequest",
  "ChangeAdminRequest",
  "Temeshtastic__PrivateConfigPacket__ChangeAdminRequest",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__ChangeAdminRequest),
  4,
  temeshtastic__private_config_packet__change_admin_request__field_descriptors,
  temeshtastic__private_config_packet__change_admin_request__field_indices_by_name,
  1,  temeshtastic__private_config_packet__change_admin_request__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__change_admin_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__request__field_descriptors[10] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Temeshtastic__PrivateConfigPacket__Request, status),
    &temeshtastic__private_config_packet__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, get_config),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_info_labels",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, get_info_labels),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_sync_wakeup",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, get_sync_wakeup),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_admin_key",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, set_admin_key),
    &temeshtastic__private_config_packet__set_admin_key__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_device_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, set_device_name),
    &temeshtastic__private_config_packet__set_device_name__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_info_label",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, set_info_label),
    &temeshtastic__private_config_packet__set_info_label__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_sync_wakeup_config",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, set_sync_wakeup_config),
    &temeshtastic__private_config_packet__set_sync_wakeup_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_company_key",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, set_company_key),
    &temeshtastic__private_config_packet__set_company_key_request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "change_admin",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Request, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Request, change_admin),
    &temeshtastic__private_config_packet__change_admin_request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__request__field_indices_by_name[] = {
  9,   /* field[9] = change_admin */
  1,   /* field[1] = get_config */
  2,   /* field[2] = get_info_labels */
  3,   /* field[3] = get_sync_wakeup */
  4,   /* field[4] = set_admin_key */
  8,   /* field[8] = set_company_key */
  5,   /* field[5] = set_device_name */
  6,   /* field[6] = set_info_label */
  7,   /* field[7] = set_sync_wakeup_config */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.Request",
  "Request",
  "Temeshtastic__PrivateConfigPacket__Request",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__Request),
  10,
  temeshtastic__private_config_packet__request__field_descriptors,
  temeshtastic__private_config_packet__request__field_indices_by_name,
  1,  temeshtastic__private_config_packet__request__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__response__field_descriptors[4] =
{
  {
    "private_config",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Response, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Response, private_config),
    &temeshtastic__private_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_labels",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Response, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Response, device_labels),
    &temeshtastic__device_labels__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_wakeup_config",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Response, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Response, sync_wakeup_config),
    &temeshtastic__sync_wakeup_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company_config",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket__Response, payload_case),
    offsetof(Temeshtastic__PrivateConfigPacket__Response, company_config),
    &temeshtastic__company_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__response__field_indices_by_name[] = {
  3,   /* field[3] = company_config */
  1,   /* field[1] = device_labels */
  0,   /* field[0] = private_config */
  2,   /* field[2] = sync_wakeup_config */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.Response",
  "Response",
  "Temeshtastic__PrivateConfigPacket__Response",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket__Response),
  4,
  temeshtastic__private_config_packet__response__field_descriptors,
  temeshtastic__private_config_packet__response__field_indices_by_name,
  1,  temeshtastic__private_config_packet__response__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue temeshtastic__private_config_packet__status__enum_values_by_number[2] =
{
  { "OK", "TEMESHTASTIC__PRIVATE_CONFIG_PACKET__STATUS__OK", 0 },
  { "ERROR", "TEMESHTASTIC__PRIVATE_CONFIG_PACKET__STATUS__ERROR", 1 },
};
static const ProtobufCIntRange temeshtastic__private_config_packet__status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex temeshtastic__private_config_packet__status__enum_values_by_name[2] =
{
  { "ERROR", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor temeshtastic__private_config_packet__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket.Status",
  "Status",
  "Temeshtastic__PrivateConfigPacket__Status",
  "temeshtastic",
  2,
  temeshtastic__private_config_packet__status__enum_values_by_number,
  2,
  temeshtastic__private_config_packet__status__enum_values_by_name,
  1,
  temeshtastic__private_config_packet__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor temeshtastic__private_config_packet__field_descriptors[2] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket, packet_type_case),
    offsetof(Temeshtastic__PrivateConfigPacket, request),
    &temeshtastic__private_config_packet__request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Temeshtastic__PrivateConfigPacket, packet_type_case),
    offsetof(Temeshtastic__PrivateConfigPacket, response),
    &temeshtastic__private_config_packet__response__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temeshtastic__private_config_packet__field_indices_by_name[] = {
  0,   /* field[0] = request */
  1,   /* field[1] = response */
};
static const ProtobufCIntRange temeshtastic__private_config_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor temeshtastic__private_config_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "temeshtastic.PrivateConfigPacket",
  "PrivateConfigPacket",
  "Temeshtastic__PrivateConfigPacket",
  "temeshtastic",
  sizeof(Temeshtastic__PrivateConfigPacket),
  2,
  temeshtastic__private_config_packet__field_descriptors,
  temeshtastic__private_config_packet__field_indices_by_name,
  1,  temeshtastic__private_config_packet__number_ranges,
  (ProtobufCMessageInit) temeshtastic__private_config_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
